//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 10:33:19 AM MDT 
//


package services.services.com.idfbins.policyxml.policy;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CostData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CostData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Premium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="BaseRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AdjustedRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Basis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NumberDaysRatedTerm" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AudManualPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudStandardPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudTransitionPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudAddMinPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudMBREPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudFinalChargedPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AudFinalChargedPremiumLessMBRE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="AudProRatedPremium" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="InsuredIsPayer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CostData", propOrder = {
    "premium",
    "baseRate",
    "adjustedRate",
    "basis",
    "numberDaysRatedTerm",
    "audManualPremium",
    "audStandardPremium",
    "audTransitionPremium",
    "audAddMinPremium",
    "audMBREPremium",
    "audFinalChargedPremium",
    "audFinalChargedPremiumLessMBRE",
    "audProRatedPremium",
    "insuredIsPayer"
})
public class CostData {

    @XmlElement(name = "Premium", required = true)
    protected BigDecimal premium;
    @XmlElement(name = "BaseRate", required = true)
    protected BigDecimal baseRate;
    @XmlElement(name = "AdjustedRate", required = true)
    protected BigDecimal adjustedRate;
    @XmlElement(name = "Basis", required = true)
    protected String basis;
    @XmlElement(name = "NumberDaysRatedTerm")
    protected int numberDaysRatedTerm;
    @XmlElement(name = "AudManualPremium", required = true)
    protected BigDecimal audManualPremium;
    @XmlElement(name = "AudStandardPremium", required = true)
    protected BigDecimal audStandardPremium;
    @XmlElement(name = "AudTransitionPremium", required = true)
    protected BigDecimal audTransitionPremium;
    @XmlElement(name = "AudAddMinPremium", required = true)
    protected BigDecimal audAddMinPremium;
    @XmlElement(name = "AudMBREPremium", required = true)
    protected BigDecimal audMBREPremium;
    @XmlElement(name = "AudFinalChargedPremium", required = true)
    protected BigDecimal audFinalChargedPremium;
    @XmlElement(name = "AudFinalChargedPremiumLessMBRE")
    protected BigDecimal audFinalChargedPremiumLessMBRE;
    @XmlElement(name = "AudProRatedPremium", required = true)
    protected BigDecimal audProRatedPremium;
    @XmlElement(name = "InsuredIsPayer")
    protected Boolean insuredIsPayer;

    /**
     * Gets the value of the premium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * Sets the value of the premium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPremium(BigDecimal value) {
        this.premium = value;
    }

    /**
     * Gets the value of the baseRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseRate() {
        return baseRate;
    }

    /**
     * Sets the value of the baseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseRate(BigDecimal value) {
        this.baseRate = value;
    }

    /**
     * Gets the value of the adjustedRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdjustedRate() {
        return adjustedRate;
    }

    /**
     * Sets the value of the adjustedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdjustedRate(BigDecimal value) {
        this.adjustedRate = value;
    }

    /**
     * Gets the value of the basis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasis() {
        return basis;
    }

    /**
     * Sets the value of the basis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasis(String value) {
        this.basis = value;
    }

    /**
     * Gets the value of the numberDaysRatedTerm property.
     * 
     */
    public int getNumberDaysRatedTerm() {
        return numberDaysRatedTerm;
    }

    /**
     * Sets the value of the numberDaysRatedTerm property.
     * 
     */
    public void setNumberDaysRatedTerm(int value) {
        this.numberDaysRatedTerm = value;
    }

    /**
     * Gets the value of the audManualPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudManualPremium() {
        return audManualPremium;
    }

    /**
     * Sets the value of the audManualPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudManualPremium(BigDecimal value) {
        this.audManualPremium = value;
    }

    /**
     * Gets the value of the audStandardPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudStandardPremium() {
        return audStandardPremium;
    }

    /**
     * Sets the value of the audStandardPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudStandardPremium(BigDecimal value) {
        this.audStandardPremium = value;
    }

    /**
     * Gets the value of the audTransitionPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudTransitionPremium() {
        return audTransitionPremium;
    }

    /**
     * Sets the value of the audTransitionPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudTransitionPremium(BigDecimal value) {
        this.audTransitionPremium = value;
    }

    /**
     * Gets the value of the audAddMinPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudAddMinPremium() {
        return audAddMinPremium;
    }

    /**
     * Sets the value of the audAddMinPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudAddMinPremium(BigDecimal value) {
        this.audAddMinPremium = value;
    }

    /**
     * Gets the value of the audMBREPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudMBREPremium() {
        return audMBREPremium;
    }

    /**
     * Sets the value of the audMBREPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudMBREPremium(BigDecimal value) {
        this.audMBREPremium = value;
    }

    /**
     * Gets the value of the audFinalChargedPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudFinalChargedPremium() {
        return audFinalChargedPremium;
    }

    /**
     * Sets the value of the audFinalChargedPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudFinalChargedPremium(BigDecimal value) {
        this.audFinalChargedPremium = value;
    }

    /**
     * Gets the value of the audFinalChargedPremiumLessMBRE property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudFinalChargedPremiumLessMBRE() {
        return audFinalChargedPremiumLessMBRE;
    }

    /**
     * Sets the value of the audFinalChargedPremiumLessMBRE property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudFinalChargedPremiumLessMBRE(BigDecimal value) {
        this.audFinalChargedPremiumLessMBRE = value;
    }

    /**
     * Gets the value of the audProRatedPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAudProRatedPremium() {
        return audProRatedPremium;
    }

    /**
     * Sets the value of the audProRatedPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAudProRatedPremium(BigDecimal value) {
        this.audProRatedPremium = value;
    }

    /**
     * Gets the value of the insuredIsPayer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInsuredIsPayer() {
        return insuredIsPayer;
    }

    /**
     * Sets the value of the insuredIsPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsuredIsPayer(Boolean value) {
        this.insuredIsPayer = value;
    }

}
