package persistence.globaldatarepo.entities;

// Generated Sep 22, 2016 1:36:24 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpspecialClassCodes generated by hbm2java
 */
@Entity
@Table(name = "CPSpecialClassCodes", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class CPSpecialClassCodes {

	private int id;
	private String classCode;
	private String itemNumber;
	private String description;
	private String classStatus;

	public CPSpecialClassCodes() {
	}

	public CPSpecialClassCodes(int id) {
		this.id = id;
	}

	public CPSpecialClassCodes(int id, String classCode, String itemNumber, String description, String classStatus) {
		this.id = id;
		this.classCode = classCode;
		this.itemNumber = itemNumber;
		this.description = description;
		this.classStatus = classStatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ClassCode", length = 200)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "ItemNumber", length = 50)
	public String getItemNumber() {
		return this.itemNumber;
	}

	public void setItemNumber(String itemNumber) {
		this.itemNumber = itemNumber;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ClassStatus", length = 200)
	public String getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(String classStatus) {
		this.classStatus = classStatus;
	}

}
