package persistence.globaldatarepo.entities;

// Generated Oct 29, 2015 10:10:08 AM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * StandardAddresses generated by hbm2java
 */
@Entity
@Table(name = "StandardAddresses", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class StandardAddresses {

	private int id;
	private String address;
	private String city;
	private String state;
	private String zip;
	private String zip4;
	private String county;
	private Boolean standardizable;

	public StandardAddresses() {
	}

	public StandardAddresses(int id) {
		this.id = id;
	}

	public StandardAddresses(int id, String address, String city, String state,
			String zip, String zip4, String county, Boolean standardizable) {
		this.id = id;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.zip4 = zip4;
		this.county = county;
		this.standardizable = standardizable;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Zip")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "Zip_4")
	public String getZip4() {
		return this.zip4;
	}

	public void setZip4(String zip4) {
		this.zip4 = zip4;
	}

	@Column(name = "County")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "Standardizable")
	public Boolean getStandardizable() {
		return this.standardizable;
	}

	public void setStandardizable(Boolean standardizable) {
		this.standardizable = standardizable;
	}

}
