package persistence.globaldatarepo.entities;
// Generated Nov 29, 2018 1:09:51 PM by Hibernate Tools 5.2.10.Final

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import persistence.config.PersistenceFactory;
import persistence.enums.HibernateConfigs;

import javax.persistence.*;
import java.util.List;

/**
 * UsersAuthority generated by hbm2java
 */
@Entity
@Table(name = "Users_Authority", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class UsersAuthority {

	private String name;
	private String description;

	public UsersAuthority() {
	}

	public UsersAuthority(String name) {
		this.name = name;
	}

	public UsersAuthority(String name, String description) {
		this.name = name;
		this.description = description;
	}

	@Id

	@Column(name = "NAME", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	
	
	@Transient
	public static void updateAuthorityTable(List<UsersAuthority> userAuthorityList) throws Exception {
		SessionFactory sessionFactory = null;
		Session session = null;
        PersistenceFactory pf = new PersistenceFactory();
		try {
            sessionFactory = pf.getSessionFactory(HibernateConfigs.GlobalDataRepository);
			
			session = sessionFactory.openSession();
			
			session.beginTransaction();
			for(UsersAuthority authority : userAuthorityList) {
				session.save(authority);
			}
			
			session.getTransaction().commit();
		} catch (Exception e) {			
			e.printStackTrace();
			throw new Exception(e.getMessage());
		} finally {
			session.clear();
            pf.close();
		}
		
	}

}
