package repository.gw.enums;

import java.util.*;

public enum BuildingClassCode {

	AccountingServicesCPAsOfficeOnlyLessorsRiskOnly("Accounting Services - CPAs - Office Only (Lessor's Risk Only)", "63630"),
	AccountingServicesCPAsCondominiumOffice("Accounting Services - CPAs Condominium - Office", "63641"),
	AccountingServicesCPAsOffice("Accounting Services - CPAs Office", "63631"),
	AccountingServicesExceptCPAsOfficeOnlyLessorsRiskOnly("Accounting Services - Except CPAs - Office Only (Lessor's Risk Only)", "63610"),
	AccountingServicesExceptCPAsCondominiumOffice("Accounting Services - Except CPAs Condominium - Office", "63621"),
	AccountingServicesExceptCPAsOffice("Accounting Services - Except CPAs Office", "63611"),
	AirConditioningEquipmentRetailOnly("Air Conditioning Equipment - Retail Only", "59999(1)"),
	AntiqueStores("Antique Stores", "59325"),
	ApartmentBuildings4FamiliesorFewerWithNoOfficeOccupancyIncludes3or4FamilyLessorsRiskOnly("Apartment Buildings 4 Families or Fewer With No Office Occupancy - Includes 3 or 4 Family (Lessor's Risk Only)", "65144"),
	ApartmentBuildings4FamiliesorFewerWithOfficeOccupancyIncludes3or4FamilyLessorsRiskOnlyandGardenApartments("Apartment Buildings 4 Families or Fewer With Office Occupancy - Includes 3 or 4 Family (Lessor's Risk Only and Garden Apartments)", "65145"),
	ApartmentBuildingsOver4FamiliesWithMercantileorOfficeOccupancy("Apartment Buildings Over 4 Families With Mercantile or Office Occupancy", "65147"),
	ApartmentBuildingsOver4FamiliesWithNoOfficeOccupancy("Apartment Buildings Over 4 Families With No Office Occupancy", "65146"),
	ApplianceDistributorsHouseholdandHomeFurnishings("Appliance Distributors - Household and Home Furnishings", "50081"),
	ApplianceDistributorsHouseholdTypesRadioTelevisionorCompactDiscPlayers("Appliance Distributors - Household Types - Radio, Television or Compact Disc Players", "50061"),
	ApplianceStoresHouseholdAppliancesandHomeFurnishings("Appliance Stores Household Appliances and Home Furnishings", "57224(1)"),
	ApplianceStoresRadioTelevisionandPhonographicStoresIncludingPartsandSupplies("Appliance Stores Radio, Television and Phonographic Stores - Including Parts and Supplies", "57326(1)"),
	AppliancesandAccesoriesInstallationServicingorRepairCommercialorHousehold("Appliances and Accesories - Installation, Servicing or Repair - Commercial or Household", "71212"),
	ArmyandNavyStores("Army and Navy Stores", "53983"),
	ArtGalleriesNotForProfitandOtherThanNotForProfit("Art Galleries - Not-For-Profit and Other Than Not-For-Profit", "84112"),
	AuctionsOnPremisesOwnedorRentedbytheInsured("Auctions - On Premises Owned or Rented by the Insured", "59999(2)"),
	AutomobilePartsandSuppliesRetailStoresIncludingTires("Automobile Parts and Supplies Retail Stores - Including Tires", "55313"),
	BakeryRetailNoBakingonPremises("Bakery - Retail - No Baking on Premises", "54606"),
	BakeryRetailWithBakingonPremises("Bakery - Retail - With Baking on Premises", "71311"),
	BakeryDistributorsNoBakingonPremises("Bakery Distributors - No Baking on Premises", "50141"),
	BarberorBeautyShopSuppliesDistributors("Barber or Beauty Shop Supplies Distributors", "50171"),
	BarberShops("Barber Shops", "71332"),
	BeautyParlorsandHairStylingSalonsIncludingNailSalons("Beauty Parlors and Hair Styling Salons - Including Nail Salons", "71952(1)"),
	BeverageStoresLiquorBeerandWine("Beverage Stores - Liquor, Beer and Wine", "59215"),
	BicycleShopsRetailIncludingRepairandMaintenanceShopsWithoutRetail("Bicycle Shops Retail - Including Repair and Maintenance Shops Without Retail", "59505"),
	BoardingHousesRoomsIncludingBedandBreakfastMercantileorOfficeOccupancy("Boarding Houses/Rooms - Including Bed and Breakfast - Mercantile or Office Occupancy", "65133(1)"),
	BoardingHousesRoomsIncludingBedandBreakfastNoMercantileorOfficeOccupancy("Boarding Houses/Rooms - Including Bed and Breakfast - No Mercantile or Office Occupancy", "65132(1)"),
	BoardingHousesRoomsIncludingBedandBreakfastThreeorFourFamilyLessorsRisksOnlyMercantileorOfficeOccupancy("Boarding Houses/Rooms - Including Bed and Breakfast - Three or Four Family Lessor's Risks Only - Mercantile or Office Occupancy", "65142(1)"),
	BoardingHousesRoomsIncludingBedandBreakfastThreeorFourFamilyLessorsRisksOnlyNoMercantileorOfficeOccupancy("Boarding Houses/Rooms - Including Bed and Breakfast - Three or Four Family Lessor's Risks Only - No Mercantile or Office Occupancy", "65141(1)"),
	BoneHornandIvoryProductsRetailOnly("Bone, Horn and Ivory Products - Retail Only", "59999(3)"),
	BookbindingandPrintingSuppliesDistributors("Bookbinding and Printing Supplies Distributors", "50201"),
	BookbindingandPrintingSuppliesRetail("Bookbinding and Printing Supplies Retail", "50812"),
	BookkeepingServicesOfficeOnlyLessorsRiskOnly("Bookkeeping Services - Office Only (Lessor's Risk Only)", "63670"),
	BookkeepingServicesCondominiumOffice("Bookkeeping Services Condominium - Office", "63661"),
	BookkeepingServicesOffice("Bookkeeping Services Office", "63671"),
	BooksandMagazinesStoresNewandUsed("Books and Magazines Stores New and Used", "59425"),
	BuildingMaterialsDealersOtherthanSecondhandMaterialPlumbingElectricaletc("Building Materials - Dealers Other than Secondhand Material - Plumbing, Electrical etc.", "52114"),
	CameraandPhotographicEquipmentRetailOnly("Camera and Photographic Equipment - Retail Only", "59955(1)"),
	CandyandConfectioneryManufacturingfromPurchasedChocolateonPremises("Candy and Confectionery - Manufacturing from Purchased Chocolate on Premises", "54467"),
	CandyandConfectioneryManufacturingNonChocolateonPremises("Candy and Confectionery - Manufacturing Non-Chocolate on Premises", "54477"),
	CandyandConfectioneryStoresNoManufacturingonPremises("Candy and Confectionery Stores - No Manufacturing on Premises", "54457"),
	CasualDiningRestaurantsBistrosBrasseriesandCafesWithNoSalesofAlcoholicBeverages("Casual Dining Restaurants - Bistros, Brasseries and Cafes - With No Sales of Alcoholic Beverages", "09611"),
	CasualDiningRestaurantsBistrosBrasseriesandCafesWithSalesofAlcoholicBeveragesUpto50ofTotalSales("Casual Dining Restaurants - Bistros, Brasseries and Cafes - With Sales of Alcoholic Beverages - Up to 50% of Total Sales", "09621"),
	CasualDiningRestaurantsDinersWithNoSalesofAlcoholicBeverages("Casual Dining Restaurants - Diners - With No Sales of Alcoholic Beverages", "09631"),
	CasualDiningRestaurantsDinersWithSalesofAlcoholicBeveragesUpto50ofTotalSales("Casual Dining Restaurants - Diners - With Sales of Alcoholic Beverages - Up to 50% of Total Sales", "09641"),
	CasualDiningRestaurantsFamilyStyleWithNoSalesofAlcoholicBeverages("Casual Dining Restaurants - Family Style - With No Sales of Alcoholic Beverages", "09651"),
	CasualDiningRestaurantsFamilyStyleWithSalesofAlcoholicBeveragesUpto50ofTotalSales("Casual Dining Restaurants - Family Style - With Sales of Alcoholic Beverages - Up to 50% of Total Sales", "09661"),
	CatalogorPremiumCouponRedemptionStores("Catalog or Premium Coupon Redemption Stores", "73905"),
	CeramicsRetailOnly("Ceramics - Retail Only", "59999(4)"),
	ClothingorWearingApparelFabricStoresIncludeMillineryandTrimmings("Clothing or Wearing Apparel - Fabric Stores - Include Millinery and Trimmings", "56311(1)"),
	ClothingorWearingApparelFamilyClothingStores("Clothing or Wearing Apparel - Family Clothing Stores", "56325"),
	ClothingorWearingApparelHaberdasheryandMensFurnishings("Clothing or Wearing Apparel - Haberdashery and Men's Furnishings", "56113"),
	ClothingorWearingApparelHosiery("Clothing or Wearing Apparel - Hosiery", "56313"),
	ClothingorWearingApparelLadiesandGirlsCoatsSuitsandDresses("Clothing or Wearing Apparel - Ladies' and Girls' Coats, Suits and Dresses", "56214"),
	ClothingorWearingApparelLadiesSpecialtyStores("Clothing or Wearing Apparel - Ladies' Specialty Stores", "56319"),
	ClothingorWearingApparelLadiesUndergarmentsandLingerie("Clothing or Wearing Apparel - Ladies' Undergarments and Lingerie", "56312"),
	ClothingorWearingApparelLeatherProductsorHideStores("Clothing or Wearing Apparel - Leather Products or Hide Stores", "56992(1)"),
	ClothingorWearingApparelMensandBoysCoatandSuits("Clothing or Wearing Apparel - Men's and Boy's Coat and Suits", "56114"),
	ClothingorWearingApparelMensandBoysClothingandFurnishingsDistributors("Clothing or Wearing Apparel - Men's and Boys' Clothing and Furnishings Distributors", "50231(1)"),
	ClothingorWearingApparelMensandBoysHatsandCaps("Clothing or Wearing Apparel - Men's and Boys' Hats and Caps", "50333"),
	ClothingorWearingApparelRetailChildrensandInfantsWear("Clothing or Wearing Apparel - Retail Children's and Infants' Wear", "56413"),
	ClothingorWearingApparelShoeStoresChildrensLadiesandMens("Clothing or Wearing Apparel - Shoe Stores - Children's, Ladies' and Men's", "56613(1)"),
	ClothingorWearingApparelSportingGoodsandAthleticApparel("Clothing or Wearing Apparel - Sporting Goods and Athletic Apparel", "59526(1)"),
	ClothingorWearingApparelWigs("Clothing or Wearing Apparel - Wigs", "59993(1)"),
	ClothingorWearingApparelWomensChildrensandInfantsClothingandAccessoriesDistributors("Clothing or Wearing Apparel - Women's, Children's and Infants' Clothing and Accessories Distributors", "50231(2)"),
	CollectiblesandMemorabiliaDistributors("Collectibles and Memorabilia - Distributors", "50261"),
	CollectiblesandMemorabiliaRetail("Collectibles and Memorabilia - Retail", "59992"),
	CollectionAgenciesOfficeOnlyLessorsRiskOnly("Collection Agencies - Office Only (Lessor's Risk Only)", "63690"),
	CollectionAgenciesCondominiumOffice("Collection Agencies Condominium - Office", "63711"),
	CollectionAgenciesOffice("Collection Agencies Office", "63691"),
	CommercialCondominiumAssociationRiskOnly("Commercial Condominium - Association Risk Only", "60989"),
	ComputerStores("Computer Stores", "57326(2)"),
	ConvenienceFoodStoresWithFastFoodRestaurantNoGasolineSales("Convenience Food Stores - With Fast Food Restaurant - No Gasoline Sales", "09341"),
	ConvenienceFoodStoresWithFastFoodRestaurantWithGasolineSales("Convenience Food Stores - With Fast Food Restaurant - With Gasoline Sales", "09361"),
	ConvenienceFoodStoresWithGasolineSalesNoRestaurant("Convenience Food Stores - With Gasoline Sales - No Restaurant", "09321"),
	ConvenienceFoodStoresWithLimitedCookingRestaurantNoGasolineSales("Convenience Food Stores - With Limited Cooking Restaurant - No Gasoline Sales", "09331"),
	ConvenienceFoodStoresWithLimitedCookingRestaurantWithGasolineSales("Convenience Food Stores - With Limited Cooking Restaurant - With Gasoline Sales", "09351"),
	ConvenienceFoodStoresWithoutGasolineSalesNoRestaurant("Convenience Food Stores - Without Gasoline Sales - No Restaurant", "54136(1)"),
	CopyingandDuplicatingStores("Copying and Duplicating Stores", "71877"),
	CosmeticHairorSkinPreparationRetailOnly("Cosmetic, Hair or Skin Preparation - Retail Only", "59991"),
	CreditReportingAgenciesOfficeOnlyLessorsRiskOnly("Credit Reporting Agencies - Office Only (Lessor's Risk Only)", "63720"),
	CreditReportingAgenciesCondominiumOffice("Credit Reporting Agencies Condominium - Office", "63731"),
	CreditReportingAgenciesOffice("Credit Reporting Agencies Office", "63721"),
	DairyProductsorButterandEggStoresIncludingIceCream("Dairy Products or Butter and Egg Stores - Including Ice Cream", "54516"),
	DelicatessensPrimarilyRetailingaRangeofGroceryItemsandMeatsUseFastFoodorLimitedCookingRestaurantClassificationforDelicatessenRestaurants("Delicatessens - Primarily Retailing a Range of Grocery Items and Meats (Use Fast Food or Limited Cooking Restaurant Classification for Delicatessen Restaurants)", "54116"),
	DentalLaboratories("Dental Laboratories", "71444"),
	DepartmentStores("Department Stores", "53127"),
	DetectiveorInvestigativeAgenciesPrivateCondominiumOffice("Detective or Investigative Agencies - Private Condominium - Office", "63751"),
	DetectiveorInvestigativeAgenciesPrivateOffice("Detective or Investigative Agencies - Private Office", "63741"),
	DetectiveorInvestigativeAgenciesPrivateOfficeLessorsRiskOnly("Detective or Investigative Agencies - Private Office (Lessor's Risk Only)", "63740"),
	DrugDistributors("Drug Distributors", "50291"),
	Drugstores("Drugstores", "59116"),
	DryGoodsDealersRetailIncludingFabricsYarnandPieceGoodsNewGoodsOnly("Dry Goods Dealers - Retail - Including Fabrics, Yarn and Piece Goods - New Goods Only", "53985"),
	DwellingsOneFourFamilyLessorsRiskOnlyNoMercantileOccupancy("Dwellings - One - Four Family (Lessor's Risk Only) No Mercantile Occupancy", "65141(2)"),
	DwellingsOneFourFamilyLessorsRiskOnlyResidentialCondominiums("Dwellings - One - Four Family (Lessor's Risk Only) Residential Condominiums", "69145(1)"),
	DwellingsOneFourFamilyLessorsRiskOnlyWithMercantileOccupancy("Dwellings - One - Four Family (Lessor's Risk Only) With Mercantile Occupancy", "65142(2)"),
	ElectricalLightingStores("Electrical Lighting Stores", "59999(5)"),
	ElectronicsStores("Electronics Stores", "57326(3)"),
	EmploymentAgenciesOfficeOnlyLessorsRiskOnly("Employment Agencies - Office Only (Lessor's Risk Only)", "63760"),
	EmploymentAgenciesCondominiumOffice("Employment Agencies Condominium - Office", "63771"),
	EmploymentAgenciesOffice("Employment Agencies Office", "63761"),
	EngineersorArchitectsConsultingNotEngagedinActualConstructionCondominiumOffice("Engineers or Architects - Consulting - Not Engaged in Actual Construction Condominium - Office", "63791"),
	EngineersorArchitectsConsultingNotEngagedinActualConstructionOffice("Engineers or Architects - Consulting - Not Engaged in Actual Construction Office", "63781"),
	EngineersorArchitectsConsultingNotEngagedinActualConstructionOfficeOnlyLessorsRiskOnly("Engineers or Architects - Consulting Not Engaged in Actual Construction - Office Only (Lessor's Risk Only)", "63780"),
	Engraving("Engraving", "71842"),
	EquipmentFixturesorSuppliesDistributorsOfficeandStoreEquipment("Equipment, Fixtures or Supplies Distributors Office and Store Equipment", "50813(1)"),
	EquipmentFixturesorSuppliesDistributorsRestaurantBarsandHotelEquipment("Equipment, Fixtures or Supplies Distributors Restaurant, Bars and Hotel Equipment", "50813(2)"),
	EstheticiansSkinCareSpecialist("Estheticians - Skin Care Specialist", "71952(2)"),
	FabricDistributors("Fabric Distributors", "50321"),
	FabricStores("Fabric Stores", "56311(2)"),
	FastFoodRestaurantsCafes("Fast Food Restaurants - Cafes", "09001"),
	FastFoodRestaurantsCafeteriaStyleBuffet("Fast Food Restaurants - Cafeteria Style - Buffet", "09021"),
	FastFoodRestaurantsChicken("Fast Food Restaurants - Chicken", "09031"),
	FastFoodRestaurantsConcessionStandsSnackBars("Fast Food Restaurants - Concession Stands/Snack Bars", "09051"),
	FastFoodRestaurantsDelicatessensandSandwichShops("Fast Food Restaurants - Delicatessens and Sandwich Shops", "09071"),
	FastFoodRestaurantsDonutShopsIncludingBakingWithFryingOperations("Fast Food Restaurants - Donut Shops - Including Baking With Frying Operations", "09091"),
	FastFoodRestaurantsDriveinsServiceinCar("Fast Food Restaurants - Drive-ins/Service in Car", "09111"),
	FastFoodRestaurantsDrugStores("Fast Food Restaurants - Drug Stores", "09131"),
	FastFoodRestaurantsHamburgerMaltShops("Fast Food Restaurants - Hamburger/Malt Shops", "09151"),
	FastFoodRestaurantsHotdogShops("Fast Food Restaurants - Hotdog Shops", "09161"),
	FastFoodRestaurantsOrientalStyleChineseJapaneseThaietc("Fast Food Restaurants - Oriental Style (Chinese, Japanese, Thai, etc.)", "09181"),
	FastFoodRestaurantsOtherEthnicStyleItalianMexicanGreeketc("Fast Food Restaurants - Other Ethnic Style (Italian, Mexican, Greek, etc.)", "09191"),
	FastFoodRestaurantsPizzaShops("Fast Food Restaurants - Pizza Shops", "09201"),
	FastFoodRestaurantsRoastBeef("Fast Food Restaurants - Roast Beef", "09221"),
	FastFoodRestaurantsSeafood("Fast Food Restaurants - Seafood", "09241"),
	FastFoodRestaurantsTakeOutOnlyRestaurantsNoOnPremisesConsumptionofFood("Fast Food Restaurants - Take Out Only Restaurants - No On-Premises Consumption of Food", "09251"),
	FeedorGrainDealersPrepackagedMerchandiseOnlyRetail("Feed or Grain Dealers - Prepackaged Merchandise Only - Retail", "59625"),
	FenceDealers("Fence Dealers", "59999(6)"),
	FineDiningRestaurantsWithNoSalesofAlcoholicBeverages("Fine Dining Restaurants - With No Sales of Alcoholic Beverages", "09421"),
	FineDiningRestaurantsWithSalesofAlcoholicBeveragesMoreThan30upto75("Fine Dining Restaurants - With Sales of Alcoholic Beverages - More Than 30% up to 75%", "09441"),
	FineDiningRestaurantsWithSalesofAlcoholicBeveragesUpto30ofTotalSales("Fine Dining Restaurants - With Sales of Alcoholic Beverages - Up to 30% of Total Sales", "09431"),
	FireProtectionEquipmentDealersRetailOnly("Fire Protection Equipment Dealers Retail Only", "59999(7)"),
	FloorCoveringDistributors("Floor Covering Distributors", "50351"),
	FloorCoveringStoresWoodorCeramicTileOnly("Floor Covering Stores - Wood or Ceramic Tile Only", "57134(1)"),
	FloristDistributors("Florist Distributors", "50381"),
	FloristRetail("Florist Retail", "59685"),
	FruitorVegetableDealers("Fruit or Vegetable Dealers", "54315"),
	FruitorVegetableDistributors("Fruit or Vegetable Distributors", "50391"),
	FuneralHomesorChapelsIncludingCrematories("Funeral Homes or Chapels - Including Crematories", "71865"),
	FurnitureUpholsteredRetailOnly("Furniture Upholstered - Retail Only", "57121"),
	FurnitureWoodorMetalRetailOnly("Furniture Wood or Metal - Retail Only", "57128"),
	GardeningandLightFarmingSupplyDistributors("Gardening and Light Farming Supply Distributors", "50471"),
	GardeningandLightFarmingSupplyRetail("Gardening and Light Farming Supply Retail", "59698"),
	GiftShops("Gift Shops", "59994"),
	GlassDealersandGlaziersRetailOnly("Glass Dealers and Glaziers - Retail Only", "57155"),
	GroceryDistributors("Grocery Distributors", "50481"),
	GroceryStoresWithanAreaatLeast4000SquareFeetWithGasolineSales("Grocery Stores - With an Area at Least 4,000 Square Feet - With Gasoline Sales", "54331"),
	GroceryStoresWithanAreaatLeast4000SquareFeetWithoutGasolineSales("Grocery Stores - With an Area at Least 4,000 Square Feet - Without Gasoline Sales", "54321"),
	GroceryStoresWithanAreaLessThan4000SquareFeetWithGasolineSales("Grocery Stores - With an Area Less Than 4,000 Square Feet - With Gasoline Sales", "54351"),
	GroceryStoresWithanAreaLessThan4000SquareFeetWithoutGasolineSales("Grocery Stores - With an Area Less Than 4,000 Square Feet - Without Gasoline Sales", "54341"),
	HardwareandToolsDistributors("Hardware and Tools Distributors", "50501"),
	HardwareandToolsRetail("Hardware and Tools Retail", "52512(1)"),
	HealthMaintenanceOrganizationsOfficeOnlyLessorsRiskOnly("Health Maintenance Organizations - Office Only (Lessor's Risk Only)", "63810"),
	HealthMaintenanceOrganizationsCondominiumOffice("Health Maintenance Organizations Condominium - Office", "63821"),
	HealthMaintenanceOrganizationsOffice("Health Maintenance Organizations Office", "63811"),
	HealthorNaturalFoodStoresWithanAreaatLeast4000SquareFeet("Health or Natural Food Stores - With an Area at Least 4,000 Square Feet", "54127"),
	HealthorNaturalFoodStoresWithanAreaLessThan4000SquareFeet("Health or Natural Food Stores - With an Area Less Than 4,000 Square Feet", "54136(2)"),
	HearingAidDistributors("Hearing Aid Distributors", "50571"),
	HearingAidRetail("Hearing Aid Retail", "59974"),
	HeatingorcombinedHeatingandAirConditioningEquipmentDistributorsOnly("Heating or combined Heating and Air Conditioning Equipment - Distributors Only", "50581"),
	HobbyCraftorArtistsSupplyDistributors("Hobby, Craft or Artists' Supply Distributors", "50641"),
	HobbyCraftorArtistsSupplyRetail("Hobby, Craft or Artists' Supply Retail", "59995"),
	HomeFurnishingsStores("Home Furnishings Stores", "57224(2)"),
	HomeImprovementStores("Home Improvement Stores", "53989"),
	InspectionandAppraisalCompaniesInspectingforInsuranceorValuationPurposesCondominiumOffice("Inspection and Appraisal Companies - Inspecting for Insurance or Valuation Purposes - Condominium - Office", "63841"),
	InspectionandAppraisalCompaniesInspectingforInsuranceorValuationPurposesOfficeOnlyLessorsRiskAnalysis("Inspection and Appraisal Companies - Inspecting for Insurance or Valuation Purposes - Office Only (Lessor's Risk Analysis)", "63830"),
	InspectionandAppraisalCompaniesInspectingforInsuranceorValuationPurposesOffice("Inspection and Appraisal Companies - Inspecting for Insurance or Valuation Purposes Office", "63831"),
	InsuranceAgentsCondominiumOffice("Insurance Agents - Condominium Office", "63861"),
	InsuranceAgentsOffice("Insurance Agents - Office", "63851"),
	InsuranceAgentsOfficeOnlyLessorsRiskOnly("Insurance Agents - Office Only (Lessor's Risk Only)", "63850"),
	InteriorDecoratorsLessorsRiskOnly("Interior Decorators (Lessor's Risk Only)", "63870"),
	InteriorDecoratorsOffice("Interior Decorators - Office", "63871"),
	InteriorDecoratorsCondominiumOffice("Interior Decorators Condominium - Office", "63881"),
	LaborUnionCondominiumOffice("Labor Union - Condominium Office", "63911"),
	LaborUnionOffice("Labor Union - Office", "63891"),
	LaborUnionOfficeOnlyLessorsRiskOnly("Labor Union - Office Only (Lessor's Risk Only)", "63890"),
	LaundromatSelfServiceNonSupervised("Laundromat (Self-Service) Non-Supervised", "09541"),
	LaundromatSelfServiceSupervised("Laundromat (Self-Service) Supervised", "09531"),
	LaundryandDryCleaningorDyeingReceivingStations("Laundry and Dry Cleaning or Dyeing Receiving Stations", "71811"),
	LaundryandDryCleaningStoresUsingPetroleumSolventsIncludingStoddardTypeSolventsandOtherCombustibleHydrocarbonSolventsandHavingLessThan3PickUpStations("Laundry and Dry Cleaning Stores - Using Petroleum Solvents (Including Stoddard Type Solvents and Other Combustible Hydrocarbon Solvents) and Having Less Than 3 Pick-Up Stations", "09501"),
	LaundryandDryCleaningStoresUsingSyntheticSolventsIncludingPerchloroethyleneorOtherSyntheticSolventsandHavingLessThan3PickUpStations("Laundry and Dry Cleaning Stores - Using Synthetic Solvents (Including Perchloroethylene or Other Synthetic Solvents) and Having Less Than 3 Pick-Up Stations", "09521"),
	LawyersOfficeOnlyLessorsRiskOnly("Lawyers - Office Only - (Lessor's Risk Only)", "63920"),
	LawyersOfficeCondominium("Lawyers Office (Condominium)", "63931"),
	LawyersOfficeOnly("Lawyers Office Only", "63921"),
	LeatherProductsorHideStoresRetailOnly("Leather Products or Hide Stores - Retail Only", "56992(2)"),
	LimitedCookingRestaurantsCoffeeBarsorShops("Limited Cooking Restaurants - Coffee Bars or Shops", "09041"),
	LimitedCookingRestaurantsConcessionStandsSnackBars("Limited Cooking Restaurants - Concession Stands/Snack Bars", "09061"),
	LimitedCookingRestaurantsDelicatessensandSandwichShops("Limited Cooking Restaurants - Delicatessens and Sandwich Shops", "09081"),
	LimitedCookingRestaurantsDonutShops("Limited Cooking Restaurants - Donut Shops", "09101"),
	LimitedCookingRestaurantsDriveinsServiceinCar("Limited Cooking Restaurants - Drive-ins/Service in Car", "09121"),
	LimitedCookingRestaurantsDrugStores("Limited Cooking Restaurants - Drug Stores", "09141"),
	LimitedCookingRestaurantsIceCreamandYogurtStores("Limited Cooking Restaurants - Ice Cream and Yogurt Stores", "09171"),
	LimitedCookingRestaurantsPizzaShops("Limited Cooking Restaurants - Pizza Shops", "09211"),
	LimitedCookingRestaurantsSaladBars("Limited Cooking Restaurants - Salad Bars", "09231"),
	LimitedCookingRestaurantsTakeOutOnlyRestaurantsNoOnPremisesConsumptionofFood("Limited Cooking Restaurants - Take Out Only Restaurants - No On-Premises Consumption of Food", "09261"),
	LimitedCookingRestaurantsCafes("Limited Cooking Restaurants Cafes", "09011"),
	Lithographing("Lithographing", "71855"),
	LocksmithsIncludingRetailSales("Locksmiths - Including Retail Sales", "52512(2)"),
	LuggageGoodsRetailOnly("Luggage Goods - Retail Only", "59999(8)"),
	MailBoxorPackagingStoresPackagingServicesExceptPackingandCratingforTransportation("Mail Box or Packaging Stores Packaging Services - Except Packing and Crating for Transportation", "71837(1)"),
	MailBoxorPackagingStoresPackingandPreparingGoodsforShipping("Mail Box or Packaging Stores Packing and Preparing Goods for Shipping", "71837(2)"),
	MailOrderHousesRetailOnly("Mail Order Houses - Retail Only", "59999(9)"),
	MailingorAddressingCompaniesDirectMailingCompanies("Mailing or Addressing Companies Direct Mailing Companies", "71837(3)"),
	MailingorAddressingCompaniesMailingListCompilingServicesMailingListPublishers("Mailing or Addressing Companies Mailing List Compiling Services/Mailing List Publishers", "71837(4)"),
	ManufacturersRepresentativesOfficeOnlyLessorsRiskOnly("Manufacturers' Representatives - Office Only (Lessor's Risk Only)", "63940"),
	ManufacturersRepresentativesCondominiumOffice("Manufacturers' Representatives Condominium - Office", "63591"),
	ManufacturersRepresentativesOffice("Manufacturers' Representatives Office", "63941"),
	MarbleProductsRetailOnly("Marble Products - Retail Only", "59999(10)"),
	MassageTherapy("Massage Therapy", "71952(3)"),
	MeatFishPoultryorSeafoodRetailOnlyFishorSeafood("Meat, Fish, Poultry or Seafood Retail Only - Fish or Seafood", "54216(1)"),
	MeatFishPoultryorSeafoodRetailOnlyMeatorPoultry("Meat, Fish, Poultry or Seafood Retail Only - Meat or Poultry", "54216(2)"),
	MedicalOfficeCondominiumOffice("Medical Office Condominium - Office", "63991"),
	MedicalOfficesOffice("Medical Offices - Office", "63981"),
	MedicalOfficesOfficeOnlyLessorsRiskOnly("Medical Offices - Office Only (Lessor's Risk Only)", "63980"),
	MedicalHospitalandSurgicalSupplyRetailOnly("Medical, Hospital and Surgical Supply - Retail Only", "50815"),
	MotelsNoRestaurants("Motels No Restaurants", "69151"),
	MotelsWithFastFoodRestaurants("Motels With Fast Food Restaurants", "69171"),
	MotelsWithLimitedCookingRestaurants("Motels With Limited Cooking Restaurants", "69161"),
	MusicStoresPreRecorded("Music Stores - Pre-Recorded", "57338(1)"),
	MusicalInstrumentStores("Musical Instrument Stores", "57334"),
	Newsstands("Newsstands", "59935"),
	OfficeCondominiumAssociationRiskOnly("Office Condominium (Association Risk Only)", "60999"),
	OfficeMachinesorAppliancesDistributorsNoRepair("Office Machines or Appliances Distributors - No Repair", "50691"),
	OfficeMachinesorAppliancesRetailNoRepair("Office Machines or Appliances Retail - No Repair", "50925"),
	OfficesLessorsRiskOnlyNotOtherwiseClassified("Offices - (Lessor's Risk Only) Not Otherwise Classified", "65170"),
	OfficesCondominiumNotOtherwiseClassified("Offices - Condominium - Not Otherwise Classified", "65231"),
	OfficesNotOtherwiseClassified("Offices - Not Otherwise Classified", "65171"),
	OpticalGoodsDistributors("Optical Goods - Distributors", "50721"),
	OpticalGoodsRetailIncludingOpticians("Optical Goods - Retail Including Opticians", "59954"),
	PaintWallpaperorWallCoveringStores("Paint, Wallpaper or Wall Covering Stores", "52322"),
	PaintingPictureorFrameStores("Painting, Picture or Frame Stores", "59999(11)"),
	PawnShops("Pawn Shops", "59982"),
	PayrollAccountingServicesOffice("Payroll Accounting Services - Office", "64011"),
	PayrollAccountingServicesOfficeOnlyLessorsRiskOnly("Payroll Accounting Services - Office Only (Lessor's Risk Only)", "64010"),
	PayrollAccountingServicesCondominiumOffice("Payroll Accounting Services Condominium - Office", "64021"),
	PetStores("Pet Stores", "59997"),
	Photoengraving("Photoengraving", "71888"),
	PhotographersStudio("Photographers - Studio", "71899"),
	PhotographicEquipmentRetailOnly("Photographic Equipment - Retail Only", "59955(2)"),
	PlumbingSuppliesandFixturesDistributors("Plumbing Supplies and Fixtures Distributors", "50741"),
	PlumbingSuppliesandFixturesRetail("Plumbing Supplies and Fixtures Retail", "59999(12)"),
	PoliticalCampaignHeadquartersorOfficesLessorsRiskOnly("Political Campaign Headquarters or Offices (Lessor's Risk Only)", "64030"),
	PoliticalCampaignHeadquartersorOfficesCondominiumOffice("Political Campaign Headquarters or Offices - Condominium Office", "64051"),
	PoliticalCampaignHeadquartersorOfficesOffice("Political Campaign Headquarters or Offices - Office", "64031"),
	PrecisionandScientificToolsandInstrumentsRetail("Precision and Scientific Tools and Instruments - Retail", "50811"),
	PrintingandDuplicating("Printing and Duplicating", "71912"),
	RealEstateAgentsCondominiumOffice("Real Estate Agents - Condominium Office", "64071"),
	RealEstateAgentsOffice("Real Estate Agents - Office", "64061"),
	RealEstateAgentsOfficeOnlyLessorsRiskOnly("Real Estate Agents - Office Only (Lessor's Risk Only)", "64060"),
	RefrigerationEquipmentCommercialDistributors("Refrigeration Equipment - Commercial Distributors", "50771"),
	RefrigerationEquipmentRetail("Refrigeration Equipment - Retail", "59983"),
	ResidentialCondominiumAssociationRiskOnly("Residential Condominium (Association Risk Only)", "69145(2)"),
	RetailStoresNotOtherwiseClassified("Retail Stores - Not Otherwise Classified", "59999(13)"),
	SecondhandorSalvageDealersRetailOnly("Secondhand or Salvage Dealers - Retail Only", "59999(14)"),
	SecurityandPatrolAgenciesCondominiumOffice("Security and Patrol Agencies - Condominium Office", "64091"),
	SecurityandPatrolAgenciesOffice("Security and Patrol Agencies - Office", "64081"),
	SecurityandPatrolAgenciesOfficeOnlyLessorsRiskOnly("Security and Patrol Agencies - Office Only (Lessor's Risk Only)", "64080"),
	SelfStorageFacilityMiniStorageHouseholdGoodsOnly("Self Storage Facility Mini-Storage - Household Goods Only", "09411"),
	SewingMachineStores("Sewing Machine Stores", "57223"),
	ShipChandlerStores("Ship Chandler Stores", "59999(15)"),
	ShoeStoresRepair("Shoe Stores Repair", "71926"),
	ShoeStoresRetail("Shoe Stores Retail", "56613(2)"),
	SportingGoodsorAthleticEquipmentStoresIncludingApparel("Sporting Goods or Athletic Equipment Stores - Including Apparel", "59526(2)"),
	StationeryorPaperProductsRetail("Stationery or Paper Products - Retail", "59435"),
	StationeryorPaperProductsDistributorsPaperegfineprintingwritingBulkWholesaling("Stationery or Paper Products Distributors Paper (e.g., fine, printing, writing) - Bulk, Wholesaling", "50801(1)"),
	StationeryorPaperProductsPaperExceptOfficeSuppliesPrintingPaperStationeryWritingPaperWholesaling("Stationery or Paper Products Paper - Except Office Supplies, Printing Paper, Stationery, Writing Paper, Wholesaling", "50801(2)"),
	StoresExceptWoodorCeramicTileOnly("Stores - Except Wood or Ceramic Tile Only", "57134(2)"),
	SupermarketsWithanAreaatLeast4000SquareFeetWithGasolineSales("Supermarkets - With an Area at Least 4,000 Square Feet - With Gasoline Sales", "54231"),
	SupermarketsWithanAreaatLeast4000SquareFeetWithoutGasolineSales("Supermarkets - With an Area at Least 4,000 Square Feet - Without Gasoline Sales", "54221"),
	SupermarketsWithanAreaLessThan4000SquareFeetWithGasolineSales("Supermarkets - With an Area Less Than 4,000 Square Feet - With Gasoline Sales", "54251"),
	SupermarketsWithanAreaLessThan4000SquareFeetWithoutGasolineSales("Supermarkets - With an Area Less Than 4,000 Square Feet - Without Gasoline Sales", "54241"),
	TailoringorDressmakingEstablishmentsCustomOrdersOnly("Tailoring or Dressmaking Establishments - Custom Orders Only", "71961"),
	Taxidermists("Taxidermists", "71976"),
	TelevisionorRadioReceivingSetInstallationorRepair("Television or Radio Receiving Set - Installation or Repair", "71921"),
	TicketAgenciesOtherThanTheatricalOfficeOnlyLessorsRiskOnly("Ticket Agencies - Other Than Theatrical - Office Only (Lessor's Risk Only)", "64140"),
	TicketAgenciesOtherThanTheatricalCondominiumOffice("Ticket Agencies - Other Than Theatrical Condominium Office", "64151"),
	TicketAgenciesOtherThanTheatricalOffice("Ticket Agencies - Other Than Theatrical Office", "64141"),
	TicketAgenciesTheatricalOfficeOnlyLessorsRiskOnly("Ticket Agencies - Theatrical - Office Only (Lessor's Risk Only)", "64120"),
	TicketAgenciesTheatricalCondominiumOffice("Ticket Agencies - Theatrical Condominium - Office", "64131"),
	TicketAgenciesTheatricalOffice("Ticket Agencies - Theatrical Office", "64121"),
	TitleAgentsOfficeOnlyLessorsRiskOnly("Title Agents' - Office Only (Lessor's Risk Only)", "64160"),
	TitleAgentsCondominiumOffice("Title Agents' Condominium - Office", "64171"),
	TitleAgentsOffice("Title Agents' Office", "64161"),
	TobaccoProductsDistributorsExceptLeaf("Tobacco Products Distributors - Except Leaf", "50821(1)"),
	TobaccoProductsDistributorsLeaf("Tobacco Products Distributors - Leaf", "50821(2)"),
	TobaccoProductsDistributorsRetail("Tobacco Products Distributors - Retail", "59906"),
	TownhousesorSimilarAssociations4FamiliesorFewerWithMercantileorOfficeOccupancyIncludes3or4FamilyLessorsRiskOnlyandGardenApartments("Townhouses or Similar Associations - 4 Families or Fewer With Mercantile or Office Occupancy - Includes 3 or 4 Family (Lessor's Risk Only and Garden Apartments)", "65142(3)"),
	TownhousesorSimilarAssociations4FamiliesorFewerWithNoMercantileorOfficeOccupancyIncludes3or4FamilyLessorsRiskOnly("Townhouses or Similar Associations - 4 Families or Fewer With No Mercantile or Office Occupancy - Includes 3 or 4 Family (Lessor's Risk Only)", "65141(3)"),
	TownhousesorSimilarAssociationsOver4FamiliesWithMercantileorOfficeOccupancy("Townhouses or Similar Associations - Over 4 Families With Mercantile or Office Occupancy", "65133(2)"),
	TownhousesorSimilarAssociationsOver4FamiliesWithNoMercantileorOfficeOccupancy("Townhouses or Similar Associations - Over 4 Families With No Mercantile or Office Occupancy", "65132(2)"),
	ToysDistributors("Toys Distributors", "50901"),
	ToysRetail("Toys Retail", "59998"),
	TrophyStores("Trophy Stores", "59996"),
	VarietyStoresDiscountHouses("Variety Stores Discount Houses", "53315"),
	VarietyStoresFiveandTenCentStores("Variety Stores Five and Ten Cent Stores", "53317"),
	VeterinariansOffice("Veterinarians' Office", "64181"),
	VeterinariansOfficeLessorsRiskOnly("Veterinarians' Office (Lessor's Risk Only)", "64180"),
	VeterinariansOfficeCondominiumOffice("Veterinarians' Office Condominium - Office", "64191"),
	VideoStoresRental("Video Stores - Rental", "57338(2)"),
	VideoStoresSales("Video Stores - Sales", "57338(3)"),
	WaterCompaniesOfficeOnlyLessorsRiskOnly("Water Companies - Office Only (Lessor's Risk Only)", "65110"),
	WigsRetailOnly("Wigs - Retail Only", "59993(2)"),
	WoodProductsNotOtherwiseClassifiedRetailOnly("Wood Products - Not Otherwise Classified - Retail Only", "50943");

	
	
	private String Classification;
	private String classCode;
	private static final Map<String, BuildingClassCode> BULDING_BY_CODE = new HashMap<String, BuildingClassCode>();
	

	static {
		for (BuildingClassCode building : values()) {
			BULDING_BY_CODE.put(building.getClassCode(), building);
		}
	}
	
	private BuildingClassCode(String Classification, String classCode) {
		this.Classification = Classification;
		this.classCode = classCode;
	}

	public String getClassCode() {
		return classCode;
	}
	
	public String getClassification() {
		return Classification;
	}

	public static BuildingClassCode valueOfClassCode(final String classCode) {
		final BuildingClassCode building = BULDING_BY_CODE.get(classCode);
		if (building != null) {
			return building;
		} else {
			return null;
		}
	}

	public static BuildingClassCode valueOfClassification(final String name) {
		final String enumName = name.toUpperCase().replaceAll(" ", "_");
		try {
			return valueOf(enumName);
		} catch (final IllegalArgumentException e) {
			return null;
		}
	}
	
	private static final List<BuildingClassCode> VALUES = Collections.unmodifiableList(Arrays.asList(values()));
	public static BuildingClassCode random()  {
		return VALUES.get(new Random().nextInt(VALUES.size()));
	}
	
}
