package repository.gw.enums;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public enum Permissions_Underwriter {
	
	Access_account_information("accessaccountinfo"),
	Access_policy_information("accesspolicyinfo"),
	Advance_cancellation("advancecancellation"),
	Advance_issuance("advanceissuance"),
	Advance_policy_change("advancepolchange"),
	Advance_reinstatement("advancereinstate"),
	Advance_renewal("advancerenewal"),
	Advance_rewrite("advancerewrite"),
	Advance_rewrite_new_account("advancerewrnewacct"),
	Advance_submission("advancesubmission"),
	Approve_policy_activity("actpolicyapprove"),
	Assign_activities("assignactivities"),
	Assign_my_activities("assignMyActivities"),
	Bind_cancellation("bindcancellation"),
	Bind_issuance("bindissuance"),
	Bind_policy_change("bindpolchange"),
	Bind_reinstatement("bindreinstate"),
	Bind_renewal("bindrenewal"),
	Bind_rewrite("bindrewrite"),
	Bind_rewrite_new_account("bindrewrnewacct"),
	Bind_submission("bindsubmission"),
	Cancellation_override_effective_date("cancelovereffdate"),
	Cancellation_rescind("cancelrescind"),
	Cancellation_schedule("cancelreschedule"),
	Complete_audit("completeaudit"),
	Copy_job("jobcopy"),
	Copy_policy_data("copypolicydata"),
	Create_account("accountcreate"),
	Create_activities("actcreate"),
	Create_address_book_contacts("abcreate"),
	Create_audit("createaudit"),
	Create_cancellation("createcancellation"),
	Create_contact_with_any_tag("anytagcreate"),
	Create_Date_of_Birth("createdatebirth"),
	Create_documents("doccreate"),
	Create_document_Template("templatecreate"),
	Create_Gender("creategender"),
	Create_issuance("createissuance"),
	Create_Liability_Property_Manuscript_Endorsement("createLiabPropManuscript"),
	Create_local_contacts("ctccreate"),
	Create_manual_UW_issue("createmanualuwissue"),
	Create_notes("notecreate"),
	Create_Pending_Cancel("creatependingcancel"),
	Create_policy_change("createpolchange"),
	Create_referral_reason("createreferralreason"),
	Create_reinstatement("createreinstate"),
	Create_renewal("createrenewal"),
	Create_rewrite("createrewrite"),
	Create_rewrite_new_account("createrewrnewacct"),
	Create_Social_Security_Number("createssn"),
	Create_submission("createsubmission"),
	Create_UW_Issue("createevalissue"),
	Decline_submission("declinesubmission"),
	Disable_archiving_for_a_policy("archivedisable"),
	Edit_account("editaccountsummary"),
	Edit_Additional_Named_Insured("editAddlNamedInsured"),
	Edit_Building_Additional_Coverage("editBuildingAddlCov"),
	Edit_Building_Additional_Interest("editBuildingAddlInterest"),
	Edit_Building_Characteristics("editbldgchar"),
	Edit_Building_Existing_Damage("editBuildingExistDamage"),
	Edit_Building_Heating("editBuildingHeating"),
	Edit_Building_Plumbing("editBuildingPlumbing"),
	Edit_Building_Roofing("editBuildingRoofing"),
	Edit_Building_Wiring("editBuildingWiring"),
	Edit_Building_Within_100_Feet("editBuilding100Feet"),
	Edit_Business_Operations("editBusinessOperations"),
	Edit_Business_Owners_Line_Additional_Coverages("editBOPAddlCov"),
	Edit_Business_Owners_Line_Additional_Insured("editBOPAddlInsured"),
	Edit_Business_Personal_Property_Limit("editBPPLimit"),
	Edit_Business_Year_Start("editBusinessYearStart"),
	Edit_cancellation("editcancellation"),
	Edit_commission_holds("editcommissionholds"),
	Edit_covered_auto_symbols("editautosymbol"),
	Edit_Date_of_Birth("editdatebirth"),
	Edit_DBA("editDBA"),
	Edit_documents("docedit"),
	Edit_document_template("templateedit"),
	Edit_Expiration_Date("editExpDate"),
	Edit_File_Markers("editfilemarkers"),
	Edit_for_Agents_and_Underwriters("editagtuw"),
	Edit_for_Underwriters("edituw"),
	Edit_Gender("editgender"),
	Edit_Gross_Receipts("editGrossReceipts"),
	Edit_issuance("editissuance"),
	Edit_job_roles("editjobroles"),
	Edit_Liability_Limits("editLiabilityLimits"),
	Edit_Life_Safety_Questions("editlifesafety"),
	Edit_Location_Additional_Coverages("EditLocAddlCov"),
	Edit_Location_Additional_Insured("editLocAddlInsured"),
	Edit_Lock_Override("editlockoverride"),
	Edit_Mailing_Address("editMailingAddress"),
	Edit_Membership_Dues("editMembershipDues"),
	Edit_nonrenew_explanation("editnonrenewexp"),
	Edit_Parking_Lot_Questions("editparkinglot"),
	Edit_policy_change("editpolchange"),
	Edit_Premises_Medical("editPremisesMedical"),
	Edit_prerenewal("editprerenewal"),
	Edit_Property_Deductible("editPropertyDeductible"),
	Edit_rate_and_premium_overrides("editratingoverrides"),
	Edit_Rate_as_of_Date("editrateasofdate"),
	Edit_reinstatement("editreinstate"),
	Edit_renewal("editrenewal"),
	Edit_rewrite("editrewrite"),
	Edit_rewrite_new_account("editrewrnewacct"),
	Edit_Small_Business_Type("editSmallBusinessType"),
	Edit_Social_Security_Number("editssn"),
	Edit_submission("editsubmission"),
	Edit_Term_Type("editTermType"),
	Edit_Transition_Renewal("editTransitionRenewal"),
	Edit_unowned_activities("acteditunowned"),
	Edit_written_date("editwrittendate"),
	Enable_archiving_for_a_policy("archiveenable"),
	Get_next_activity_from_queue("actqueuenext"),
	Issue_renewal("issuerenewal"),
	Issuing("issue"),
	Move_policies("accountmovepolicies"),
	Nonrenewal("nonrenew"),
	Nottaken_renewal("nottakenrenewal"),
	OOS_Override_Available("OOSOverrideAvailable"),
	Own_activity("actown"),
	Quote("quote"),
	Quote_Hide_Override("quotehideoverride"),
	Reassign_owned_activities("actraown"),
	Reassign_unowned_activities("actraunown"),
	Reject_UW_Issues("uwreject"),
	Reopen_account("accountreopen"),
	Reopen_UW_issues("uwreopen"),
	Restore_from_archive("restorefromarchive"),
	Rewrite_policies_to_account("accountrewritepolicies"),
	Search_accounts("searchaccounts"),
	Search_activities("searchactivities"),
	Search_producer_codes("searchprodcodes"),
	Search_for_Related_Claims("searchrelatedclaims"),
	Search_related_contacts("searchcontacts"),
	Search_related_policies("searchpols"),
	Select_nonrenew_as_a_prerenewal_direction("selectnonrenew"),
	Send_Email("sendemail"),
	Show_the_edit_document_button("show_edit_doc_button"),
	Split_or_Spin_Policies("splitpolicy"),
	Start_a_New_Submission_on_any_Account("CanStartSubmissionOnAnyAccount"),
	View_account("viewaccount"),
	View_account_file_contacts("accountcontacts"),
	View_account_file_documents("accountdocs"),
	View_account_file_history("accounthistory"),
	View_account_file_notes("accountnotes"),
	View_account_file_related_accounts("accountrelations"),
	View_account_file_roles("accountroles"),
	View_account_files_summary("accountsummary"),
	View_account_file_work_orders("accountworkorders"),
	View_activities("actview"),
	View_Add_on_Related_Accounts("viewAddRelAcctButtons"),
	View_address_book_contacts("abview"),
	View_address_book_contact_search_pages("abviewsearch"),
	View_address_line("viewaddressline"),
	View_All_Agents("viewallagents"),
	View_assign_activities("viewAssignActivities"),
	View_audit("viewaudit"),
	View_billing_system("viewbillingsystem"),
	View_cancellation("viewcancellation"),
	View_Change_To_Link("viewchangetolink"),
	View_Claim_Details("viewClaimDetails"),
	View_claim_system("viewclaimsystem"),
	View_contact_file_claims("contactclaims"),
	View_contact_with_any_tag("anytagview"),
	View_Date_of_Birth("viewdatebirth"),
	View_Declination_Reason("viewdeclination"),
	View_documents("docview"),
	View_Drivers_License_Number("viewdrivlicnum"),
	View_Gender("viewgender"),
	View_History("viewhist"),
	View_Include_Hidden_Documents("viewhiddendocs"),
	View_issuance("viewissuance"),
	View_Lienholder_Billing("viewlienholderbilling"),
	View_local_contacts("ctcview"),
	View_Modifiers("viewmodifiers"),
	View_my_accounts("viewmyaccounts"),
	View_my_activities("viewmyactivites"),
	View_my_policy_changes("viewmypolicychanges"),
	View_my_queues("viewmyqueues"),
	View_my_renewals("viewmyrenewals"),
	View_my_submissions("viewmysubmissions"),
	View_notes("noteview"),
	View_Participants("viewparticipants"),
	View_Pending_Cancel("viewpendingcancel"),
	View_policy_change("viewpolchange"),
	View_policy_file("viewpolfile"),
	View_policy_file_contacts("pfilecontacts"),
	View_policy_file_details("pfiledetails"),
	View_policy_file_payments("pfilepayments"),
	View_policy_file_pricing("pfilepricing"),
	View_policy_file_summary("pfilesummary"),
	View_policy_file_work_orders("pfileworkorders"),
	View_policy_hold("polholdview"),
	View_prerenewal("viewprerenewal"),
	View_producer_style_desktop_details("viewproducerstyledesktopdetails"),
	View_rate_and_premium_overrides("viewratingoverrides"),
	View_rate_books_and_tables("ratebookview"),
	View_reinstatement("viewreinstate"),
	View_Remove_on_Related_Accounts("viewRmvRelAcctButtons"),
	View_renewal("viewrenewal"),
	View_rewrite("viewrewrite"),
	View_rewrite_new_account("viewrewrnewacct"),
	View_RI_policies("viewreinsuranceforpolicy"),
	View_risk_analysis_claims("viewriskclaims"),
	View_risk_analysis_prior_losses("viewriskpriorlosses"),
	View_risk_analysis_prior_policies("viewriskpriorpolicies"),
	View_risk_analysis_referral_reasons("viewrefreasons"),
	View_risk_analysis_UW_issues("viewriskevalissues"),
	View_Social_Security_Number("viewssn"),
	View_submission("viewsubmission"),
	View_the_Loss_Ratio_tabs("viewlossratios"),
	View_Workplan("viewworkplan"),
	Withdraw("withdraw");
String value;
	
	
	private Permissions_Underwriter(String value){
		this.value = value;
	}
	
	public String getValue(){
		return this.value;
	}
	
	public static Permissions_Underwriter valueOfName(final String name) {
		final String enumName = name.replaceAll(" ", "");
		try {
			return valueOf(enumName);
		} catch (final IllegalArgumentException e) {
			return null;
		}
	}
	
	private static final List<Permissions_Underwriter> VALUES = Collections.unmodifiableList(Arrays.asList(values()));

	public static Permissions_Underwriter randomGender()  {
		return VALUES.get(new Random().nextInt(VALUES.size()));
	}
	
	
	
	
	
	
	
	
	
	
	
}
