
package services.services.com.idfbins.disbursementcheckstatusapi.gw.bc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DisbursementCheckStatusAPIPortType", targetNamespace = "http://www.idfbins.com/gw/bc")
@XmlSeeAlso({
	ObjectFactory.class,
    services.services.com.idfbins.disbursementcheckstatusapi.ws.soapheaders.ObjectFactory.class,
    services.services.com.idfbins.disbursementcheckstatusapi.billingcenter.ropexportresponsetobc.ObjectFactory.class,
    services.services.com.idfbins.disbursementcheckstatusapi.common.servicestatus.ObjectFactory.class
})
public interface DisbursementCheckStatusAPIPortType {


    /**
     * 
     * @param response
     * @return
     *     returns com.idfbins.gw.bc.UpdateCheckStatusResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "http://www.idfbins.com/gw/bc")
    @RequestWrapper(localName = "updateCheckStatus", targetNamespace = "http://www.idfbins.com/gw/bc", className = "com.idfbins.gw.bc.UpdateCheckStatus")
    @ResponseWrapper(localName = "updateCheckStatusResponse", targetNamespace = "http://www.idfbins.com/gw/bc", className = "com.idfbins.gw.bc.UpdateCheckStatusResponse")
    public UpdateCheckStatusResponse.Return updateCheckStatus(
        @WebParam(name = "response", targetNamespace = "http://www.idfbins.com/gw/bc")
        UpdateCheckStatus.Response response);

}
