package persistence.globaldatarepo.entities;

// Generated Sep 22, 2016 1:01:26 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.sql.Clob;

/**
 * CpclassCodes generated by hbm2java
 */
@Entity
@Table(name = "CPClassCodes", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class CPClassCodes {

	private int id;
	private String classCode;
	private String description;
	private String restricted;
	private String rated;
	private Clob notes;

	public CPClassCodes() {
	}

	public CPClassCodes(int id) {
		this.id = id;
	}

	public CPClassCodes(int id, String classCode, String description, String restricted, String rated, Clob notes) {
		this.id = id;
		this.classCode = classCode;
		this.description = description;
		this.restricted = restricted;
		this.rated = rated;
		this.notes = notes;
	}
	
	public CPClassCodes(String classCode, String description, String restricted, String rated) {
		this.classCode = classCode;
		this.description = description;
		this.restricted = restricted;
		this.rated = rated;
	}
	
	public CPClassCodes(String classCode) {
		this.classCode = classCode;
	}
	

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ClassCode", length = 200)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Restricted", length = 200)
	public String getRestricted() {
		return this.restricted;
	}

	public void setRestricted(String restricted) {
		this.restricted = restricted;
	}

	@Column(name = "Rated", length = 200)
	public String getRated() {
		return this.rated;
	}

	public void setRated(String rated) {
		this.rated = rated;
	}

	@Column(name = "Notes")
	public Clob getNotes() {
		return this.notes;
	}

	public void setNotes(Clob notes) {
		this.notes = notes;
	}

}
