package persistence.globaldatarepo.entities;
// default package
// Generated Jun 12, 2017 11:21:30 AM by Hibernate Tools 5.2.0.Beta1

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import persistence.config.PersistenceFactory;
import persistence.enums.HibernateConfigs;

import javax.persistence.*;

/**
 * PcRolesBak generated by hbm2java
 */
@Entity
@Table(name = "PC_RolesBAK", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class PcRolesBak{

	private String role;

	public PcRolesBak() {
	}

	public PcRolesBak(String role) {
		this.role = role;
	}

	@Id

	@Column(name = "Role", unique = true, nullable = false, length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	@Transient
	public static void createNewRole(String role) throws Exception {
		SessionFactory sessionFactory = null;
		Session session = null;
        PersistenceFactory pf = new PersistenceFactory();
		try {
            sessionFactory = pf.getSessionFactory(HibernateConfigs.GlobalDataRepository);

			session = sessionFactory.openSession();
			session.beginTransaction();

			PcRolesBak pcRole = new PcRolesBak(role);

			session.save(pcRole);

			session.getTransaction().commit();
		} catch (Exception e) {			
			e.printStackTrace();
			throw new Exception(e.getMessage());
		} finally {
			session.clear();
            pf.close();
		}
	}

}
