package persistence.globaldatarepo.entities;
// Generated Nov 29, 2018 1:21:47 PM by Hibernate Tools 5.2.10.Final

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import persistence.config.PersistenceFactory;
import persistence.enums.HibernateConfigs;

import javax.persistence.*;
import java.util.List;

/**
 * UsersRole generated by hbm2java
 */
@Entity
@Table(name = "Users_Role", schema = "dbo", catalog = "QAWIZPROGlobalDataRepository")
public class UsersRole {

	private String name;
	private String description;
	private String type;

	public UsersRole() {
	}

	public UsersRole(String name) {
		this.name = name;
	}

	public UsersRole(String name, String description, String type) {
		this.name = name;
		this.description = description;
		this.type = type;
	}

	@Id

	@Column(name = "NAME", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TYPE", length = 200)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	
	
	
	@Transient
	public static void updateRolesTable(List<UsersRole> userRoleList) throws Exception {
		SessionFactory sessionFactory = null;
		Session session = null;
        PersistenceFactory pf = new PersistenceFactory();
		try {
            sessionFactory = pf.getSessionFactory(HibernateConfigs.GlobalDataRepository);
			
			session = sessionFactory.openSession();
			
			session.beginTransaction();
			for(UsersRole role : userRoleList) {
				session.save(role);
			}
			
			session.getTransaction().commit();
		} catch (Exception e) {			
			e.printStackTrace();
			throw new Exception(e.getMessage());
		} finally {
			session.clear();
            pf.close();
		}
		
	}

	
	
	
	
	
	
	
	
	
	
	
}
