//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:05:28 PM MDT 
//


package services.verisk.tu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CO_SEG_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}CO_SEG_LENGTH" minOccurs="0"/>
 *         &lt;element ref="{}INFO_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}SUBS_NAME" minOccurs="0"/>
 *         &lt;element ref="{}ACC_NUM" minOccurs="0"/>
 *         &lt;element ref="{}REM_TYPE_CODE" minOccurs="0"/>
 *         &lt;element ref="{}WORDING_OF_REM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cosegtype",
    "coseglength",
    "infotype",
    "subsname",
    "accnum",
    "remtypecode",
    "wordingofrem"
})
@XmlRootElement(name = "COMPLIANCE")
public class COMPLIANCE {

    @XmlElement(name = "CO_SEG_TYPE")
    protected String cosegtype;
    @XmlElement(name = "CO_SEG_LENGTH")
    protected String coseglength;
    @XmlElement(name = "INFO_TYPE")
    protected String infotype;
    @XmlElement(name = "SUBS_NAME")
    protected String subsname;
    @XmlElement(name = "ACC_NUM")
    protected String accnum;
    @XmlElement(name = "REM_TYPE_CODE")
    protected String remtypecode;
    @XmlElement(name = "WORDING_OF_REM")
    protected String wordingofrem;

    /**
     * Gets the value of the cosegtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSEGTYPE() {
        return cosegtype;
    }

    /**
     * Sets the value of the cosegtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSEGTYPE(String value) {
        this.cosegtype = value;
    }

    /**
     * Gets the value of the coseglength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSEGLENGTH() {
        return coseglength;
    }

    /**
     * Sets the value of the coseglength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSEGLENGTH(String value) {
        this.coseglength = value;
    }

    /**
     * Gets the value of the infotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOTYPE() {
        return infotype;
    }

    /**
     * Sets the value of the infotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOTYPE(String value) {
        this.infotype = value;
    }

    /**
     * Gets the value of the subsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBSNAME() {
        return subsname;
    }

    /**
     * Sets the value of the subsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBSNAME(String value) {
        this.subsname = value;
    }

    /**
     * Gets the value of the accnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCNUM() {
        return accnum;
    }

    /**
     * Sets the value of the accnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCNUM(String value) {
        this.accnum = value;
    }

    /**
     * Gets the value of the remtypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMTYPECODE() {
        return remtypecode;
    }

    /**
     * Sets the value of the remtypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMTYPECODE(String value) {
        this.remtypecode = value;
    }

    /**
     * Gets the value of the wordingofrem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWORDINGOFREM() {
        return wordingofrem;
    }

    /**
     * Sets the value of the wordingofrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWORDINGOFREM(String value) {
        this.wordingofrem = value;
    }

}
