//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:05:28 PM MDT 
//


package services.verisk.tu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EN_SEG_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}EN_SEG_LENGTH" minOccurs="0"/>
 *         &lt;element ref="{}EN_TOT_NO_SEG" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ensegtype",
    "enseglength",
    "entotnoseg"
})
@XmlRootElement(name = "ENDS")
public class ENDS {

    @XmlElement(name = "EN_SEG_TYPE")
    protected String ensegtype;
    @XmlElement(name = "EN_SEG_LENGTH")
    protected String enseglength;
    @XmlElement(name = "EN_TOT_NO_SEG")
    protected String entotnoseg;

    /**
     * Gets the value of the ensegtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENSEGTYPE() {
        return ensegtype;
    }

    /**
     * Sets the value of the ensegtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENSEGTYPE(String value) {
        this.ensegtype = value;
    }

    /**
     * Gets the value of the enseglength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENSEGLENGTH() {
        return enseglength;
    }

    /**
     * Sets the value of the enseglength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENSEGLENGTH(String value) {
        this.enseglength = value;
    }

    /**
     * Gets the value of the entotnoseg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTOTNOSEG() {
        return entotnoseg;
    }

    /**
     * Sets the value of the entotnoseg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTOTNOSEG(String value) {
        this.entotnoseg = value;
    }

}
