//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 04:26:02 PM MDT 
//


package services.broker.objects.lexisnexis.mvr.response.actual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for violationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="violationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Accident"/>
 *               &lt;enumeration value="Cancellation"/>
 *               &lt;enumeration value="Conviction"/>
 *               &lt;enumeration value="Departmental"/>
 *               &lt;enumeration value="Disqualified"/>
 *               &lt;enumeration value="Financial Responsibility"/>
 *               &lt;enumeration value="Miscellaneous"/>
 *               &lt;enumeration value="Probation"/>
 *               &lt;enumeration value="Reinstatement"/>
 *               &lt;enumeration value="Revocation"/>
 *               &lt;enumeration value="Suspension"/>
 *               &lt;enumeration value="Violation"/>
 *               &lt;enumeration value="Warning"/>
 *               &lt;enumeration value="Unclassified(unknown)"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="violation_suspension_date" type="{http://cp.com/rules/client}LenientDateType" minOccurs="0"/>
 *         &lt;element name="conviction_reinstatement_date" type="{http://cp.com/rules/client}LenientDateType" minOccurs="0"/>
 *         &lt;element name="descriptions" type="{http://cp.com/rules/client}mvrViolationDescriptionType" minOccurs="0"/>
 *         &lt;element name="state_violation_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="points" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="standard_violations" type="{http://cp.com/rules/client}MvrStandardViolationsListType" minOccurs="0"/>
 *         &lt;element name="unidentifiable_raw_data" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "violationType", propOrder = {
    "description",
    "type",
    "violationSuspensionDate",
    "convictionReinstatementDate",
    "descriptions",
    "stateViolationCode",
    "points",
    "standardViolations",
    "unidentifiableRawData"
})
public class ViolationType {

    protected ViolationType.MvrViolationEnum description;
    protected String type;
    @XmlElement(name = "violation_suspension_date")
    protected String violationSuspensionDate;
    @XmlElement(name = "conviction_reinstatement_date")
    protected String convictionReinstatementDate;
    protected MvrViolationDescriptionType descriptions;
    @XmlElement(name = "state_violation_code")
    protected String stateViolationCode;
    protected String points;
    @XmlElement(name = "standard_violations")
    protected MvrStandardViolationsListType standardViolations;
    @XmlElement(name = "unidentifiable_raw_data")
    protected String unidentifiableRawData;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link ViolationType.MvrViolationEnum }
     *     
     */
    public ViolationType.MvrViolationEnum getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViolationType.MvrViolationEnum }
     *     
     */
    public void setDescription(ViolationType.MvrViolationEnum value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the violationSuspensionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationSuspensionDate() {
        return violationSuspensionDate;
    }

    /**
     * Sets the value of the violationSuspensionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationSuspensionDate(String value) {
        this.violationSuspensionDate = value;
    }

    /**
     * Gets the value of the convictionReinstatementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvictionReinstatementDate() {
        return convictionReinstatementDate;
    }

    /**
     * Sets the value of the convictionReinstatementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvictionReinstatementDate(String value) {
        this.convictionReinstatementDate = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link MvrViolationDescriptionType }
     *     
     */
    public MvrViolationDescriptionType getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MvrViolationDescriptionType }
     *     
     */
    public void setDescriptions(MvrViolationDescriptionType value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the stateViolationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateViolationCode() {
        return stateViolationCode;
    }

    /**
     * Sets the value of the stateViolationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateViolationCode(String value) {
        this.stateViolationCode = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoints(String value) {
        this.points = value;
    }

    /**
     * Gets the value of the standardViolations property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.MvrStandardViolationsListType }
     *     
     */
    public MvrStandardViolationsListType getStandardViolations() {
        return standardViolations;
    }

    /**
     * Sets the value of the standardViolations property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.MvrStandardViolationsListType }
     *     
     */
    public void setStandardViolations(MvrStandardViolationsListType value) {
        this.standardViolations = value;
    }

    /**
     * Gets the value of the unidentifiableRawData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidentifiableRawData() {
        return unidentifiableRawData;
    }

    /**
     * Sets the value of the unidentifiableRawData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidentifiableRawData(String value) {
        this.unidentifiableRawData = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="Accident"/>
     *     &lt;enumeration value="Cancellation"/>
     *     &lt;enumeration value="Conviction"/>
     *     &lt;enumeration value="Departmental"/>
     *     &lt;enumeration value="Disqualified"/>
     *     &lt;enumeration value="Financial Responsibility"/>
     *     &lt;enumeration value="Miscellaneous"/>
     *     &lt;enumeration value="Probation"/>
     *     &lt;enumeration value="Reinstatement"/>
     *     &lt;enumeration value="Revocation"/>
     *     &lt;enumeration value="Suspension"/>
     *     &lt;enumeration value="Violation"/>
     *     &lt;enumeration value="Warning"/>
     *     &lt;enumeration value="Unclassified(unknown)"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum MvrViolationEnum {

        @XmlEnumValue("Accident")
        ACCIDENT("Accident"),
        @XmlEnumValue("Cancellation")
        CANCELLATION("Cancellation"),
        @XmlEnumValue("Conviction")
        CONVICTION("Conviction"),
        @XmlEnumValue("Departmental")
        DEPARTMENTAL("Departmental"),
        @XmlEnumValue("Disqualified")
        DISQUALIFIED("Disqualified"),
        @XmlEnumValue("Financial Responsibility")
        FINANCIAL_RESPONSIBILITY("Financial Responsibility"),
        @XmlEnumValue("Miscellaneous")
        MISCELLANEOUS("Miscellaneous"),
        @XmlEnumValue("Probation")
        PROBATION("Probation"),
        @XmlEnumValue("Reinstatement")
        REINSTATEMENT("Reinstatement"),
        @XmlEnumValue("Revocation")
        REVOCATION("Revocation"),
        @XmlEnumValue("Suspension")
        SUSPENSION("Suspension"),
        @XmlEnumValue("Violation")
        VIOLATION("Violation"),
        @XmlEnumValue("Warning")
        WARNING("Warning"),
        @XmlEnumValue("Unclassified(unknown)")
        UNCLASSIFIED_UNKNOWN("Unclassified(unknown)");
        private final String value;

        MvrViolationEnum(String v) {
            value = v;
        }

        public String value() {
            return value;
        }

        public static ViolationType.MvrViolationEnum fromValue(String v) {
            for (ViolationType.MvrViolationEnum c: ViolationType.MvrViolationEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
            throw new IllegalArgumentException(v);
        }

    }

}
