//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 01:50:47 PM MST 
//


package services.broker.objects.lexisnexis.cbr.response.actual;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date_file_established" type="{http://cp.com/rules/client}USDateType" minOccurs="0"/>
 *         &lt;element name="date_oldest_trade" type="{http://cp.com/rules/client}USDateType" minOccurs="0"/>
 *         &lt;element name="date_latest_trade" type="{http://cp.com/rules/client}USDateType" minOccurs="0"/>
 *         &lt;element name="date_latest_activity" type="{http://cp.com/rules/client}USDateType" minOccurs="0"/>
 *         &lt;element name="includes_bankruptcies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="flag" use="required" type="{http://cp.com/rules/client}true_false" />
 *                 &lt;attribute name="date" type="{http://cp.com/rules/client}USDateType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="includes_other_records">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="public_records" type="{http://cp.com/rules/client}true_false" />
 *                 &lt;attribute name="collection" type="{http://cp.com/rules/client}true_false" />
 *                 &lt;attribute name="consumer_statement" type="{http://cp.com/rules/client}true_false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="credit_range">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="high" type="{http://cp.com/rules/client}whole_dollar" />
 *                 &lt;attribute name="low" type="{http://cp.com/rules/client}whole_dollar" />
 *                 &lt;attribute name="number_trade_lines" type="{http://cp.com/rules/client}counter" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="account_status_counters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account" maxOccurs="18" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                           &lt;attribute name="type">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="current"/>
 *                                 &lt;enumeration value="former"/>
 *                                 &lt;enumeration value="unknown"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="description" use="required" type="{http://cp.com/rules/client}summary_account_codes" />
 *                           &lt;attribute name="status">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;pattern value="[ 0-9]"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="account_summaries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account" maxOccurs="9" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="number_accounts" type="{http://cp.com/rules/client}counter" minOccurs="0"/>
 *                             &lt;element name="total_owed" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
 *                             &lt;element name="total_past_due" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
 *                             &lt;element name="high_amount" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://cp.com/rules/client}financial_accounts" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inquiry_history" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="count" type="{http://cp.com/rules/client}counter" />
 *                 &lt;attribute name="since" type="{http://cp.com/rules/client}USDateType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateFileEstablished",
    "dateOldestTrade",
    "dateLatestTrade",
    "dateLatestActivity",
    "includesBankruptcies",
    "includesOtherRecords",
    "creditRange",
    "accountStatusCounters",
    "accountSummaries",
    "inquiryHistory"
})
@XmlRootElement(name = "summary")
public class Summary {

    @XmlElement(name = "date_file_established")
    protected String dateFileEstablished;
    @XmlElement(name = "date_oldest_trade")
    protected String dateOldestTrade;
    @XmlElement(name = "date_latest_trade")
    protected String dateLatestTrade;
    @XmlElement(name = "date_latest_activity")
    protected String dateLatestActivity;
    @XmlElement(name = "includes_bankruptcies", required = true)
    protected Summary.IncludesBankruptcies includesBankruptcies;
    @XmlElement(name = "includes_other_records", required = true)
    protected Summary.IncludesOtherRecords includesOtherRecords;
    @XmlElement(name = "credit_range", required = true)
    protected Summary.CreditRange creditRange;
    @XmlElement(name = "account_status_counters")
    protected Summary.AccountStatusCounters accountStatusCounters;
    @XmlElement(name = "account_summaries", required = true)
    protected Summary.AccountSummaries accountSummaries;
    @XmlElement(name = "inquiry_history")
    protected Summary.InquiryHistory inquiryHistory;

    /**
     * Gets the value of the dateFileEstablished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFileEstablished() {
        return dateFileEstablished;
    }

    /**
     * Sets the value of the dateFileEstablished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFileEstablished(String value) {
        this.dateFileEstablished = value;
    }

    /**
     * Gets the value of the dateOldestTrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOldestTrade() {
        return dateOldestTrade;
    }

    /**
     * Sets the value of the dateOldestTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOldestTrade(String value) {
        this.dateOldestTrade = value;
    }

    /**
     * Gets the value of the dateLatestTrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLatestTrade() {
        return dateLatestTrade;
    }

    /**
     * Sets the value of the dateLatestTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLatestTrade(String value) {
        this.dateLatestTrade = value;
    }

    /**
     * Gets the value of the dateLatestActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLatestActivity() {
        return dateLatestActivity;
    }

    /**
     * Sets the value of the dateLatestActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLatestActivity(String value) {
        this.dateLatestActivity = value;
    }

    /**
     * Gets the value of the includesBankruptcies property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.IncludesBankruptcies }
     *     
     */
    public Summary.IncludesBankruptcies getIncludesBankruptcies() {
        return includesBankruptcies;
    }

    /**
     * Sets the value of the includesBankruptcies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.IncludesBankruptcies }
     *     
     */
    public void setIncludesBankruptcies(Summary.IncludesBankruptcies value) {
        this.includesBankruptcies = value;
    }

    /**
     * Gets the value of the includesOtherRecords property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.IncludesOtherRecords }
     *     
     */
    public Summary.IncludesOtherRecords getIncludesOtherRecords() {
        return includesOtherRecords;
    }

    /**
     * Sets the value of the includesOtherRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.IncludesOtherRecords }
     *     
     */
    public void setIncludesOtherRecords(Summary.IncludesOtherRecords value) {
        this.includesOtherRecords = value;
    }

    /**
     * Gets the value of the creditRange property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.CreditRange }
     *     
     */
    public Summary.CreditRange getCreditRange() {
        return creditRange;
    }

    /**
     * Sets the value of the creditRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.CreditRange }
     *     
     */
    public void setCreditRange(Summary.CreditRange value) {
        this.creditRange = value;
    }

    /**
     * Gets the value of the accountStatusCounters property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.AccountStatusCounters }
     *     
     */
    public Summary.AccountStatusCounters getAccountStatusCounters() {
        return accountStatusCounters;
    }

    /**
     * Sets the value of the accountStatusCounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.AccountStatusCounters }
     *     
     */
    public void setAccountStatusCounters(Summary.AccountStatusCounters value) {
        this.accountStatusCounters = value;
    }

    /**
     * Gets the value of the accountSummaries property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.AccountSummaries }
     *     
     */
    public Summary.AccountSummaries getAccountSummaries() {
        return accountSummaries;
    }

    /**
     * Sets the value of the accountSummaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.AccountSummaries }
     *     
     */
    public void setAccountSummaries(Summary.AccountSummaries value) {
        this.accountSummaries = value;
    }

    /**
     * Gets the value of the inquiryHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Summary.InquiryHistory }
     *     
     */
    public Summary.InquiryHistory getInquiryHistory() {
        return inquiryHistory;
    }

    /**
     * Sets the value of the inquiryHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary.InquiryHistory }
     *     
     */
    public void setInquiryHistory(Summary.InquiryHistory value) {
        this.inquiryHistory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="account" maxOccurs="18" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *                 &lt;attribute name="type">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="current"/>
     *                       &lt;enumeration value="former"/>
     *                       &lt;enumeration value="unknown"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="description" use="required" type="{http://cp.com/rules/client}summary_account_codes" />
     *                 &lt;attribute name="status">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;pattern value="[ 0-9]"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class AccountStatusCounters {

        protected List<Summary.AccountStatusCounters.Account> account;

        /**
         * Gets the value of the account property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the account property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccount().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Summary.AccountStatusCounters.Account }
         * 
         * 
         */
        public List<Summary.AccountStatusCounters.Account> getAccount() {
            if (account == null) {
                account = new ArrayList<Summary.AccountStatusCounters.Account>();
            }
            return this.account;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
         *       &lt;attribute name="type">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="current"/>
         *             &lt;enumeration value="former"/>
         *             &lt;enumeration value="unknown"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="description" use="required" type="{http://cp.com/rules/client}summary_account_codes" />
         *       &lt;attribute name="status">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;pattern value="[ 0-9]"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Account {

            @XmlValue
            protected BigInteger value;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "description", required = true)
            protected SummaryAccountTypesEnum description;
            @XmlAttribute(name = "status")
            protected String status;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setValue(BigInteger value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link broker.objects.lexisnexis.cbr.response.actual.SummaryAccountTypesEnum }
             *     
             */
            public SummaryAccountTypesEnum getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link broker.objects.lexisnexis.cbr.response.actual.SummaryAccountTypesEnum }
             *     
             */
            public void setDescription(SummaryAccountTypesEnum value) {
                this.description = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="account" maxOccurs="9" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="number_accounts" type="{http://cp.com/rules/client}counter" minOccurs="0"/>
     *                   &lt;element name="total_owed" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
     *                   &lt;element name="total_past_due" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
     *                   &lt;element name="high_amount" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://cp.com/rules/client}financial_accounts" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class AccountSummaries {

        protected List<Summary.AccountSummaries.Account> account;

        /**
         * Gets the value of the account property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the account property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccount().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Summary.AccountSummaries.Account }
         * 
         * 
         */
        public List<Summary.AccountSummaries.Account> getAccount() {
            if (account == null) {
                account = new ArrayList<Summary.AccountSummaries.Account>();
            }
            return this.account;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="number_accounts" type="{http://cp.com/rules/client}counter" minOccurs="0"/>
         *         &lt;element name="total_owed" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
         *         &lt;element name="total_past_due" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
         *         &lt;element name="high_amount" type="{http://cp.com/rules/client}whole_dollar" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://cp.com/rules/client}financial_accounts" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numberAccounts",
            "totalOwed",
            "totalPastDue",
            "highAmount"
        })
        public static class Account {

            @XmlElement(name = "number_accounts")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer numberAccounts;
            @XmlElement(name = "total_owed")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer totalOwed;
            @XmlElement(name = "total_past_due")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer totalPastDue;
            @XmlElement(name = "high_amount")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected Integer highAmount;
            @XmlAttribute(name = "type")
            protected FinancialAccountTypesEnum type;

            /**
             * Gets the value of the numberAccounts property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumberAccounts() {
                return numberAccounts;
            }

            /**
             * Sets the value of the numberAccounts property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumberAccounts(Integer value) {
                this.numberAccounts = value;
            }

            /**
             * Gets the value of the totalOwed property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalOwed() {
                return totalOwed;
            }

            /**
             * Sets the value of the totalOwed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalOwed(Integer value) {
                this.totalOwed = value;
            }

            /**
             * Gets the value of the totalPastDue property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalPastDue() {
                return totalPastDue;
            }

            /**
             * Sets the value of the totalPastDue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalPastDue(Integer value) {
                this.totalPastDue = value;
            }

            /**
             * Gets the value of the highAmount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHighAmount() {
                return highAmount;
            }

            /**
             * Sets the value of the highAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHighAmount(Integer value) {
                this.highAmount = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link broker.objects.lexisnexis.cbr.response.actual.FinancialAccountTypesEnum }
             *     
             */
            public FinancialAccountTypesEnum getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link broker.objects.lexisnexis.cbr.response.actual.FinancialAccountTypesEnum }
             *     
             */
            public void setType(FinancialAccountTypesEnum value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="high" type="{http://cp.com/rules/client}whole_dollar" />
     *       &lt;attribute name="low" type="{http://cp.com/rules/client}whole_dollar" />
     *       &lt;attribute name="number_trade_lines" type="{http://cp.com/rules/client}counter" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CreditRange {

        @XmlAttribute(name = "high")
        protected Integer high;
        @XmlAttribute(name = "low")
        protected Integer low;
        @XmlAttribute(name = "number_trade_lines")
        protected Integer numberTradeLines;

        /**
         * Gets the value of the high property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHigh(Integer value) {
            this.high = value;
        }

        /**
         * Gets the value of the low property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLow(Integer value) {
            this.low = value;
        }

        /**
         * Gets the value of the numberTradeLines property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberTradeLines() {
            return numberTradeLines;
        }

        /**
         * Sets the value of the numberTradeLines property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberTradeLines(Integer value) {
            this.numberTradeLines = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="flag" use="required" type="{http://cp.com/rules/client}true_false" />
     *       &lt;attribute name="date" type="{http://cp.com/rules/client}USDateType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncludesBankruptcies {

        @XmlAttribute(name = "flag", required = true)
        protected TrueFalseEnum flag;
        @XmlAttribute(name = "date")
        protected String date;

        /**
         * Gets the value of the flag property.
         * 
         * @return
         *     possible object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public TrueFalseEnum getFlag() {
            return flag;
        }

        /**
         * Sets the value of the flag property.
         * 
         * @param value
         *     allowed object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public void setFlag(TrueFalseEnum value) {
            this.flag = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="public_records" type="{http://cp.com/rules/client}true_false" />
     *       &lt;attribute name="collection" type="{http://cp.com/rules/client}true_false" />
     *       &lt;attribute name="consumer_statement" type="{http://cp.com/rules/client}true_false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncludesOtherRecords {

        @XmlAttribute(name = "public_records")
        protected TrueFalseEnum publicRecords;
        @XmlAttribute(name = "collection")
        protected TrueFalseEnum collection;
        @XmlAttribute(name = "consumer_statement")
        protected TrueFalseEnum consumerStatement;

        /**
         * Gets the value of the publicRecords property.
         * 
         * @return
         *     possible object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public TrueFalseEnum getPublicRecords() {
            return publicRecords;
        }

        /**
         * Sets the value of the publicRecords property.
         * 
         * @param value
         *     allowed object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public void setPublicRecords(TrueFalseEnum value) {
            this.publicRecords = value;
        }

        /**
         * Gets the value of the collection property.
         * 
         * @return
         *     possible object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public TrueFalseEnum getCollection() {
            return collection;
        }

        /**
         * Sets the value of the collection property.
         * 
         * @param value
         *     allowed object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public void setCollection(TrueFalseEnum value) {
            this.collection = value;
        }

        /**
         * Gets the value of the consumerStatement property.
         * 
         * @return
         *     possible object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public TrueFalseEnum getConsumerStatement() {
            return consumerStatement;
        }

        /**
         * Sets the value of the consumerStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link broker.objects.lexisnexis.cbr.response.actual.TrueFalseEnum }
         *     
         */
        public void setConsumerStatement(TrueFalseEnum value) {
            this.consumerStatement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="count" type="{http://cp.com/rules/client}counter" />
     *       &lt;attribute name="since" type="{http://cp.com/rules/client}USDateType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InquiryHistory {

        @XmlAttribute(name = "count")
        protected Integer count;
        @XmlAttribute(name = "since")
        protected String since;

        /**
         * Gets the value of the count property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCount(Integer value) {
            this.count = value;
        }

        /**
         * Gets the value of the since property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSince() {
            return since;
        }

        /**
         * Sets the value of the since property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSince(String value) {
            this.since = value;
        }

    }

}
