//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:19:26 PM MDT 
//


package services.verisk.iso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADDRESS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADDRESS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ParsedAddress" type="{}ParsedAddress"/>
 *           &lt;element name="UnparsedAddress" type="{}UnparsedAddress"/>
 *         &lt;/choice>
 *         &lt;element name="ScrubbedAddress" type="{}ScrubbedAddress" minOccurs="0"/>
 *         &lt;element ref="{}ReportOptions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADDRESS", propOrder = {
    "parsedAddress",
    "unparsedAddress",
    "scrubbedAddress",
    "reportOptions"
})
public class ADDRESS {

    @XmlElement(name = "ParsedAddress")
    protected ParsedAddress parsedAddress;
    @XmlElement(name = "UnparsedAddress")
    protected UnparsedAddress unparsedAddress;
    @XmlElement(name = "ScrubbedAddress")
    protected ScrubbedAddress scrubbedAddress;
    @XmlElement(name = "ReportOptions")
    protected ReportOptions reportOptions;

    /**
     * Gets the value of the parsedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ParsedAddress }
     *     
     */
    public ParsedAddress getParsedAddress() {
        return parsedAddress;
    }

    /**
     * Sets the value of the parsedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParsedAddress }
     *     
     */
    public void setParsedAddress(ParsedAddress value) {
        this.parsedAddress = value;
    }

    /**
     * Gets the value of the unparsedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link UnparsedAddress }
     *     
     */
    public UnparsedAddress getUnparsedAddress() {
        return unparsedAddress;
    }

    /**
     * Sets the value of the unparsedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnparsedAddress }
     *     
     */
    public void setUnparsedAddress(UnparsedAddress value) {
        this.unparsedAddress = value;
    }

    /**
     * Gets the value of the scrubbedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ScrubbedAddress }
     *     
     */
    public ScrubbedAddress getScrubbedAddress() {
        return scrubbedAddress;
    }

    /**
     * Sets the value of the scrubbedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScrubbedAddress }
     *     
     */
    public void setScrubbedAddress(ScrubbedAddress value) {
        this.scrubbedAddress = value;
    }

    /**
     * Gets the value of the reportOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ReportOptions }
     *     
     */
    public ReportOptions getReportOptions() {
        return reportOptions;
    }

    /**
     * Sets the value of the reportOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportOptions }
     *     
     */
    public void setReportOptions(ReportOptions value) {
        this.reportOptions = value;
    }

}
