//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:19:26 PM MDT 
//


package services.verisk.iso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimsPartyRole1Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimsPartyRole2Cd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ClaimsParty1Ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="ClaimsParty2Ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "claimsPartyRole1Cd",
    "claimsPartyRole2Cd"
})
@XmlRootElement(name = "ClaimsPartyRelationship")
public class ClaimsPartyRelationship {

    @XmlElement(name = "ClaimsPartyRole1Cd")
    protected java.lang.String claimsPartyRole1Cd;
    @XmlElement(name = "ClaimsPartyRole2Cd")
    protected java.lang.String claimsPartyRole2Cd;
    @XmlAttribute(name = "ClaimsParty1Ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object claimsParty1Ref;
    @XmlAttribute(name = "ClaimsParty2Ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object claimsParty2Ref;

    /**
     * Gets the value of the claimsPartyRole1Cd property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getClaimsPartyRole1Cd() {
        return claimsPartyRole1Cd;
    }

    /**
     * Sets the value of the claimsPartyRole1Cd property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setClaimsPartyRole1Cd(java.lang.String value) {
        this.claimsPartyRole1Cd = value;
    }

    /**
     * Gets the value of the claimsPartyRole2Cd property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getClaimsPartyRole2Cd() {
        return claimsPartyRole2Cd;
    }

    /**
     * Sets the value of the claimsPartyRole2Cd property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setClaimsPartyRole2Cd(java.lang.String value) {
        this.claimsPartyRole2Cd = value;
    }

    /**
     * Gets the value of the claimsParty1Ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getClaimsParty1Ref() {
        return claimsParty1Ref;
    }

    /**
     * Sets the value of the claimsParty1Ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setClaimsParty1Ref(Object value) {
        this.claimsParty1Ref = value;
    }

    /**
     * Gets the value of the claimsParty2Ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getClaimsParty2Ref() {
        return claimsParty2Ref;
    }

    /**
     * Sets the value of the claimsParty2Ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setClaimsParty2Ref(Object value) {
        this.claimsParty2Ref = value;
    }

}
