//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:19:26 PM MDT 
//


package services.verisk.iso;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}INSUREDORPRINCIPALENTITY">
 *       &lt;sequence>
 *         &lt;element name="InsuredOrPrincipalRoleCd" type="{}StringCd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insuredOrPrincipalRoleCd"
})
@XmlRootElement(name = "InsuredOrPrincipalInfo")
public class InsuredOrPrincipalInfo
    extends INSUREDORPRINCIPALENTITY
{

    @XmlElement(name = "InsuredOrPrincipalRoleCd")
    protected StringCd insuredOrPrincipalRoleCd;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the insuredOrPrincipalRoleCd property.
     * 
     * @return
     *     possible object is
     *     {@link StringCd }
     *     
     */
    public StringCd getInsuredOrPrincipalRoleCd() {
        return insuredOrPrincipalRoleCd;
    }

    /**
     * Sets the value of the insuredOrPrincipalRoleCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringCd }
     *     
     */
    public void setInsuredOrPrincipalRoleCd(StringCd value) {
        this.insuredOrPrincipalRoleCd = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
