//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:19:26 PM MDT 
//


package services.verisk.iso;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the broker.objects.verisk.iso package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransactionResponseDt_QNAME = new QName("", "TransactionResponseDt");
    private final static QName _SuppressMatchInd_QNAME = new QName("", "SuppressMatchInd");
    private final static QName _PendingResponseExpDt_QNAME = new QName("", "PendingResponseExpDt");
    private final static QName _Org_QNAME = new QName("", "Org");
    private final static QName _CurCd_QNAME = new QName("", "CurCd");
    private final static QName _RqUID_QNAME = new QName("", "RqUID");
    private final static QName _Addr_QNAME = new QName("", "Addr");
    private final static QName _TransactionRequestDt_QNAME = new QName("", "TransactionRequestDt");
    private final static QName _ReferralInd_QNAME = new QName("", "ReferralInd");
    private final static QName _MsgNameCd_QNAME = new QName("", "MsgNameCd");
    private final static QName _StatusDesc_QNAME = new QName("", "StatusDesc");
    private final static QName _SearchBasisCd_QNAME = new QName("", "SearchBasisCd");
    private final static QName _MsgRqUID_QNAME = new QName("", "MsgRqUID");
    private final static QName _Language_QNAME = new QName("", "Language");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _GenSessKey_QNAME = new QName("", "GenSessKey");
    private final static QName _SuppressNotificationInd_QNAME = new QName("", "SuppressNotificationInd");
    private final static QName _ServerDt_QNAME = new QName("", "ServerDt");
    private final static QName _CustLoginId_QNAME = new QName("", "CustLoginId");
    private final static QName _ClientDt_QNAME = new QName("", "ClientDt");
    private final static QName _CustLangPref_QNAME = new QName("", "CustLangPref");
    private final static QName _PolicyNumber_QNAME = new QName("", "PolicyNumber");
    private final static QName _SessKey_QNAME = new QName("", "SessKey");
    private final static QName _SPName_QNAME = new QName("", "SPName");
    private final static QName _StatusCd_QNAME = new QName("", "StatusCd");
    private final static QName _ExpDt_QNAME = new QName("", "ExpDt");
    private final static QName _SignonRoleCd_QNAME = new QName("", "SignonRoleCd");
    private final static QName _NotificationDt_QNAME = new QName("", "NotificationDt");
    private final static QName _CustIdCustPermId_QNAME = new QName("", "CustPermId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: broker.objects.verisk.iso
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PassportInqRq }
     * 
     */
    public PassportInqRq createPassportInqRq() {
        return new PassportInqRq();
    }

    /**
     * Create an instance of {@link CommlName }
     * 
     */
    public CommlName createCommlName() {
        return new CommlName();
    }

    /**
     * Create an instance of {@link NameInfo }
     * 
     */
    public NameInfo createNameInfo() {
        return new NameInfo();
    }

    /**
     * Create an instance of {@link GeneralPartyInfo }
     * 
     */
    public GeneralPartyInfo createGeneralPartyInfo() {
        return new GeneralPartyInfo();
    }

    /**
     * Create an instance of {@link Communications }
     * 
     */
    public Communications createCommunications() {
        return new Communications();
    }

    /**
     * Create an instance of {@link InsuredOrPrincipal }
     * 
     */
    public InsuredOrPrincipal createInsuredOrPrincipal() {
        return new InsuredOrPrincipal();
    }

    /**
     * Create an instance of {@link ReportOptions }
     * 
     */
    public ReportOptions createReportOptions() {
        return new ReportOptions();
    }

    /**
     * Create an instance of {@link ChangeStatus }
     * 
     */
    public ChangeStatus createChangeStatus() {
        return new ChangeStatus();
    }

    /**
     * Create an instance of {@link MsgStatus }
     * 
     */
    public MsgStatus createMsgStatus() {
        return new MsgStatus();
    }

    /**
     * Create an instance of {@link SignonRq }
     * 
     */
    public SignonRq createSignonRq() {
        return new SignonRq();
    }

    /**
     * Create an instance of {@link ItemIdInfo }
     * 
     */
    public ItemIdInfo createItemIdInfo() {
        return new ItemIdInfo();
    }

    /**
     * Create an instance of {@link PassportSvcRq }
     * 
     */
    public PassportSvcRq createPassportSvcRq() {
        return new PassportSvcRq();
    }

    /**
     * Create an instance of {@link ISO }
     * 
     */
    public ISO createISO() {
        return new ISO();
    }

    /**
     * Create an instance of {@link ConversionRate }
     * 
     */
    public ConversionRate createConversionRate() {
        return new ConversionRate();
    }

    /**
     * Create an instance of {@link FORMATTEDNUMBER }
     * 
     */
    public FORMATTEDNUMBER createFORMATTEDNUMBER() {
        return new FORMATTEDNUMBER();
    }

    /**
     * Create an instance of {@link PCCREDITSURCHARGE }
     * 
     */
    public PCCREDITSURCHARGE createPCCREDITSURCHARGE() {
        return new PCCREDITSURCHARGE();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs }
     * 
     */
    public ISO.PassportSvcRs createISOPassportSvcRs() {
        return new ISO.PassportSvcRs();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.Reports }
     * 
     */
    public ISO.PassportSvcRs.Reports createISOPassportSvcRsReports() {
        return new ISO.PassportSvcRs.Reports();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.Reports.Report }
     * 
     */
    public ISO.PassportSvcRs.Reports.Report createISOPassportSvcRsReportsReport() {
        return new ISO.PassportSvcRs.Reports.Report();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.ErrorMsgs }
     * 
     */
    public ISO.PassportSvcRs.ErrorMsgs createISOPassportSvcRsErrorMsgs() {
        return new ISO.PassportSvcRs.ErrorMsgs();
    }

    /**
     * Create an instance of {@link SignonRq.SignonCert }
     * 
     */
    public SignonRq.SignonCert createSignonRqSignonCert() {
        return new SignonRq.SignonCert();
    }

    /**
     * Create an instance of {@link SignonRq.SignonPswd }
     * 
     */
    public SignonRq.SignonPswd createSignonRqSignonPswd() {
        return new SignonRq.SignonPswd();
    }

    /**
     * Create an instance of {@link SignonRq.SignonPswd.CustPswd }
     * 
     */
    public SignonRq.SignonPswd.CustPswd createSignonRqSignonPswdCustPswd() {
        return new SignonRq.SignonPswd.CustPswd();
    }

    /**
     * Create an instance of {@link INQPARTY }
     * 
     */
    public INQPARTY createINQPARTY() {
        return new INQPARTY();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest }
     * 
     */
    public PassportInqRq.PropertyRequest createPassportInqRqPropertyRequest() {
        return new PassportInqRq.PropertyRequest();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest.RawDataSegments }
     * 
     */
    public PassportInqRq.PropertyRequest.RawDataSegments createPassportInqRqPropertyRequestRawDataSegments() {
        return new PassportInqRq.PropertyRequest.RawDataSegments();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment }
     * 
     */
    public PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment createPassportInqRqPropertyRequestRawDataSegmentsRawDataSegment() {
        return new PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest }
     * 
     */
    public PassportInqRq.AutoRequest createPassportInqRqAutoRequest() {
        return new PassportInqRq.AutoRequest();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Vehicles }
     * 
     */
    public PassportInqRq.AutoRequest.Vehicles createPassportInqRqAutoRequestVehicles() {
        return new PassportInqRq.AutoRequest.Vehicles();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Vehicles.Vehicle }
     * 
     */
    public PassportInqRq.AutoRequest.Vehicles.Vehicle createPassportInqRqAutoRequestVehiclesVehicle() {
        return new PassportInqRq.AutoRequest.Vehicles.Vehicle();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.RawDataSegments }
     * 
     */
    public PassportInqRq.AutoRequest.RawDataSegments createPassportInqRqAutoRequestRawDataSegments() {
        return new PassportInqRq.AutoRequest.RawDataSegments();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment }
     * 
     */
    public PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment createPassportInqRqAutoRequestRawDataSegmentsRawDataSegment() {
        return new PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment();
    }

    /**
     * Create an instance of {@link PersonInfo }
     * 
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link StringCd }
     * 
     */
    public StringCd createStringCd() {
        return new StringCd();
    }

    /**
     * Create an instance of {@link services.verisk.iso.String }
     * 
     */
    public services.verisk.iso.String createString() {
        return new services.verisk.iso.String();
    }

    /**
     * Create an instance of {@link BusinessInfo }
     * 
     */
    public BusinessInfo createBusinessInfo() {
        return new BusinessInfo();
    }

    /**
     * Create an instance of {@link ExtendedStatus }
     * 
     */
    public ExtendedStatus createExtendedStatus() {
        return new ExtendedStatus();
    }

    /**
     * Create an instance of {@link PassportInqRq.Header }
     * 
     */
    public PassportInqRq.Header createPassportInqRqHeader() {
        return new PassportInqRq.Header();
    }

    /**
     * Create an instance of {@link PassportInqRq.Products }
     * 
     */
    public PassportInqRq.Products createPassportInqRqProducts() {
        return new PassportInqRq.Products();
    }

    /**
     * Create an instance of {@link ClaimsSvcRs }
     * 
     */
    public ClaimsSvcRs createClaimsSvcRs() {
        return new ClaimsSvcRs();
    }

    /**
     * Create an instance of {@link services.verisk.iso.Status }
     * 
     */
    public services.verisk.iso.Status createStatus() {
        return new services.verisk.iso.Status();
    }

    /**
     * Create an instance of {@link CustId }
     * 
     */
    public CustId createCustId() {
        return new CustId();
    }

    /**
     * Create an instance of {@link CommlName.SupplementaryNameInfo }
     * 
     */
    public CommlName.SupplementaryNameInfo createCommlNameSupplementaryNameInfo() {
        return new CommlName.SupplementaryNameInfo();
    }

    /**
     * Create an instance of {@link FamilyName }
     * 
     */
    public FamilyName createFamilyName() {
        return new FamilyName();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link TaxIdentity }
     * 
     */
    public TaxIdentity createTaxIdentity() {
        return new TaxIdentity();
    }

    /**
     * Create an instance of {@link NameInfo.NonTaxIdentity }
     * 
     */
    public NameInfo.NonTaxIdentity createNameInfoNonTaxIdentity() {
        return new NameInfo.NonTaxIdentity();
    }

    /**
     * Create an instance of {@link GeneralPartyInfo.Addresses }
     * 
     */
    public GeneralPartyInfo.Addresses createGeneralPartyInfoAddresses() {
        return new GeneralPartyInfo.Addresses();
    }

    /**
     * Create an instance of {@link Communications.PhoneInfo }
     * 
     */
    public Communications.PhoneInfo createCommunicationsPhoneInfo() {
        return new Communications.PhoneInfo();
    }

    /**
     * Create an instance of {@link Communications.EmailInfo }
     * 
     */
    public Communications.EmailInfo createCommunicationsEmailInfo() {
        return new Communications.EmailInfo();
    }

    /**
     * Create an instance of {@link Communications.WebsiteInfo }
     * 
     */
    public Communications.WebsiteInfo createCommunicationsWebsiteInfo() {
        return new Communications.WebsiteInfo();
    }

    /**
     * Create an instance of {@link InsuredOrPrincipalInfo }
     * 
     */
    public InsuredOrPrincipalInfo createInsuredOrPrincipalInfo() {
        return new InsuredOrPrincipalInfo();
    }

    /**
     * Create an instance of {@link INSUREDORPRINCIPALENTITY }
     * 
     */
    public INSUREDORPRINCIPALENTITY createINSUREDORPRINCIPALENTITY() {
        return new INSUREDORPRINCIPALENTITY();
    }

    /**
     * Create an instance of {@link PrincipalInfo }
     * 
     */
    public PrincipalInfo createPrincipalInfo() {
        return new PrincipalInfo();
    }

    /**
     * Create an instance of {@link InsuredOrPrincipal.LengthTimeKnownByAgentBroker }
     * 
     */
    public InsuredOrPrincipal.LengthTimeKnownByAgentBroker createInsuredOrPrincipalLengthTimeKnownByAgentBroker() {
        return new InsuredOrPrincipal.LengthTimeKnownByAgentBroker();
    }

    /**
     * Create an instance of {@link ProxyClient }
     * 
     */
    public ProxyClient createProxyClient() {
        return new ProxyClient();
    }

    /**
     * Create an instance of {@link ReportOptions.ReportOption }
     * 
     */
    public ReportOptions.ReportOption createReportOptionsReportOption() {
        return new ReportOptions.ReportOption();
    }

    /**
     * Create an instance of {@link Business }
     * 
     */
    public Business createBusiness() {
        return new Business();
    }

    /**
     * Create an instance of {@link Owners }
     * 
     */
    public Owners createOwners() {
        return new Owners();
    }

    /**
     * Create an instance of {@link ChangeStatus.ActionCd }
     * 
     */
    public ChangeStatus.ActionCd createChangeStatusActionCd() {
        return new ChangeStatus.ActionCd();
    }

    /**
     * Create an instance of {@link ChangeStatus.PreviousValue }
     * 
     */
    public ChangeStatus.PreviousValue createChangeStatusPreviousValue() {
        return new ChangeStatus.PreviousValue();
    }

    /**
     * Create an instance of {@link ChangeStatus.RefNameCd }
     * 
     */
    public ChangeStatus.RefNameCd createChangeStatusRefNameCd() {
        return new ChangeStatus.RefNameCd();
    }

    /**
     * Create an instance of {@link ChangeStatus.ChangeDesc }
     * 
     */
    public ChangeStatus.ChangeDesc createChangeStatusChangeDesc() {
        return new ChangeStatus.ChangeDesc();
    }

    /**
     * Create an instance of {@link MsgStatus.PendingResponseAvailDt }
     * 
     */
    public MsgStatus.PendingResponseAvailDt createMsgStatusPendingResponseAvailDt() {
        return new MsgStatus.PendingResponseAvailDt();
    }

    /**
     * Create an instance of {@link MsgStatus.PendingResponseExpDt }
     * 
     */
    public MsgStatus.PendingResponseExpDt createMsgStatusPendingResponseExpDt() {
        return new MsgStatus.PendingResponseExpDt();
    }

    /**
     * Create an instance of {@link SignonRs }
     * 
     */
    public SignonRs createSignonRs() {
        return new SignonRs();
    }

    /**
     * Create an instance of {@link ClientApp }
     * 
     */
    public ClientApp createClientApp() {
        return new ClientApp();
    }

    /**
     * Create an instance of {@link SignonRq.SignonTransport }
     * 
     */
    public SignonRq.SignonTransport createSignonRqSignonTransport() {
        return new SignonRq.SignonTransport();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link ReferralInfo }
     * 
     */
    public ReferralInfo createReferralInfo() {
        return new ReferralInfo();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link PendingResponseInqRs }
     * 
     */
    public PendingResponseInqRs createPendingResponseInqRs() {
        return new PendingResponseInqRs();
    }

    /**
     * Create an instance of {@link PendingResponseInfo }
     * 
     */
    public PendingResponseInfo createPendingResponseInfo() {
        return new PendingResponseInfo();
    }

    /**
     * Create an instance of {@link CodeList }
     * 
     */
    public CodeList createCodeList() {
        return new CodeList();
    }

    /**
     * Create an instance of {@link PendingResponseInqRq }
     * 
     */
    public PendingResponseInqRq createPendingResponseInqRq() {
        return new PendingResponseInqRq();
    }

    /**
     * Create an instance of {@link MiscParty }
     * 
     */
    public MiscParty createMiscParty() {
        return new MiscParty();
    }

    /**
     * Create an instance of {@link ItemIdInfo.OtherIdentifier }
     * 
     */
    public ItemIdInfo.OtherIdentifier createItemIdInfoOtherIdentifier() {
        return new ItemIdInfo.OtherIdentifier();
    }

    /**
     * Create an instance of {@link DriversLicense }
     * 
     */
    public DriversLicense createDriversLicense() {
        return new DriversLicense();
    }

    /**
     * Create an instance of {@link ClaimsPartyRelationship }
     * 
     */
    public ClaimsPartyRelationship createClaimsPartyRelationship() {
        return new ClaimsPartyRelationship();
    }

    /**
     * Create an instance of {@link RemarkText }
     * 
     */
    public RemarkText createRemarkText() {
        return new RemarkText();
    }

    /**
     * Create an instance of {@link PassportSvcRq.PassportGetDataRq }
     * 
     */
    public PassportSvcRq.PassportGetDataRq createPassportSvcRqPassportGetDataRq() {
        return new PassportSvcRq.PassportGetDataRq();
    }

    /**
     * Create an instance of {@link MiscPartyInfo }
     * 
     */
    public MiscPartyInfo createMiscPartyInfo() {
        return new MiscPartyInfo();
    }

    /**
     * Create an instance of {@link CreditScoreInfo }
     * 
     */
    public CreditScoreInfo createCreditScoreInfo() {
        return new CreditScoreInfo();
    }

    /**
     * Create an instance of {@link TaxCodeInfo }
     * 
     */
    public TaxCodeInfo createTaxCodeInfo() {
        return new TaxCodeInfo();
    }

    /**
     * Create an instance of {@link ConversionRate.TargetMeasurement }
     * 
     */
    public ConversionRate.TargetMeasurement createConversionRateTargetMeasurement() {
        return new ConversionRate.TargetMeasurement();
    }

    /**
     * Create an instance of {@link ConversionRate.TargetCurrency }
     * 
     */
    public ConversionRate.TargetCurrency createConversionRateTargetCurrency() {
        return new ConversionRate.TargetCurrency();
    }

    /**
     * Create an instance of {@link MatchReasonInfo }
     * 
     */
    public MatchReasonInfo createMatchReasonInfo() {
        return new MatchReasonInfo();
    }

    /**
     * Create an instance of {@link SignoffRs }
     * 
     */
    public SignoffRs createSignoffRs() {
        return new SignoffRs();
    }

    /**
     * Create an instance of {@link CURRENCY }
     * 
     */
    public CURRENCY createCURRENCY() {
        return new CURRENCY();
    }

    /**
     * Create an instance of {@link PCDEDUCTIBLE }
     * 
     */
    public PCDEDUCTIBLE createPCDEDUCTIBLE() {
        return new PCDEDUCTIBLE();
    }

    /**
     * Create an instance of {@link ScrubbedAddress }
     * 
     */
    public ScrubbedAddress createScrubbedAddress() {
        return new ScrubbedAddress();
    }

    /**
     * Create an instance of {@link UnparsedAddress }
     * 
     */
    public UnparsedAddress createUnparsedAddress() {
        return new UnparsedAddress();
    }

    /**
     * Create an instance of {@link ADDRESS }
     * 
     */
    public ADDRESS createADDRESS() {
        return new ADDRESS();
    }

    /**
     * Create an instance of {@link MEASUREMENT }
     * 
     */
    public MEASUREMENT createMEASUREMENT() {
        return new MEASUREMENT();
    }

    /**
     * Create an instance of {@link ODOMETER }
     * 
     */
    public ODOMETER createODOMETER() {
        return new ODOMETER();
    }

    /**
     * Create an instance of {@link ParsedAddress }
     * 
     */
    public ParsedAddress createParsedAddress() {
        return new ParsedAddress();
    }

    /**
     * Create an instance of {@link FORMATTEDNUMBER.FormatCurrencyAmt }
     * 
     */
    public FORMATTEDNUMBER.FormatCurrencyAmt createFORMATTEDNUMBERFormatCurrencyAmt() {
        return new FORMATTEDNUMBER.FormatCurrencyAmt();
    }

    /**
     * Create an instance of {@link PCCREDITSURCHARGE.NumericValue }
     * 
     */
    public PCCREDITSURCHARGE.NumericValue createPCCREDITSURCHARGENumericValue() {
        return new PCCREDITSURCHARGE.NumericValue();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.Status }
     * 
     */
    public ISO.PassportSvcRs.Status createISOPassportSvcRsStatus() {
        return new ISO.PassportSvcRs.Status();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.Reports.Report.Status }
     * 
     */
    public ISO.PassportSvcRs.Reports.Report.Status createISOPassportSvcRsReportsReportStatus() {
        return new ISO.PassportSvcRs.Reports.Report.Status();
    }

    /**
     * Create an instance of {@link ISO.PassportSvcRs.ErrorMsgs.ErrorMsg }
     * 
     */
    public ISO.PassportSvcRs.ErrorMsgs.ErrorMsg createISOPassportSvcRsErrorMsgsErrorMsg() {
        return new ISO.PassportSvcRs.ErrorMsgs.ErrorMsg();
    }

    /**
     * Create an instance of {@link SignonRq.SignonCert.Certificate }
     * 
     */
    public SignonRq.SignonCert.Certificate createSignonRqSignonCertCertificate() {
        return new SignonRq.SignonCert.Certificate();
    }

    /**
     * Create an instance of {@link SignonRq.SignonPswd.CustPswd.EncryptedPswd }
     * 
     */
    public SignonRq.SignonPswd.CustPswd.EncryptedPswd createSignonRqSignonPswdCustPswdEncryptedPswd() {
        return new SignonRq.SignonPswd.CustPswd.EncryptedPswd();
    }

    /**
     * Create an instance of {@link INQPARTY.PriorDriversLicense }
     * 
     */
    public INQPARTY.PriorDriversLicense createINQPARTYPriorDriversLicense() {
        return new INQPARTY.PriorDriversLicense();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest.Parties }
     * 
     */
    public PassportInqRq.PropertyRequest.Parties createPassportInqRqPropertyRequestParties() {
        return new PassportInqRq.PropertyRequest.Parties();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest.Addresses }
     * 
     */
    public PassportInqRq.PropertyRequest.Addresses createPassportInqRqPropertyRequestAddresses() {
        return new PassportInqRq.PropertyRequest.Addresses();
    }

    /**
     * Create an instance of {@link PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment.RawDataString }
     * 
     */
    public PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment.RawDataString createPassportInqRqPropertyRequestRawDataSegmentsRawDataSegmentRawDataString() {
        return new PassportInqRq.PropertyRequest.RawDataSegments.RawDataSegment.RawDataString();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Drivers }
     * 
     */
    public PassportInqRq.AutoRequest.Drivers createPassportInqRqAutoRequestDrivers() {
        return new PassportInqRq.AutoRequest.Drivers();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Addresses }
     * 
     */
    public PassportInqRq.AutoRequest.Addresses createPassportInqRqAutoRequestAddresses() {
        return new PassportInqRq.AutoRequest.Addresses();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Vehicles.Vehicle.Addresses }
     * 
     */
    public PassportInqRq.AutoRequest.Vehicles.Vehicle.Addresses createPassportInqRqAutoRequestVehiclesVehicleAddresses() {
        return new PassportInqRq.AutoRequest.Vehicles.Vehicle.Addresses();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.Vehicles.Vehicle.OdometerReadings }
     * 
     */
    public PassportInqRq.AutoRequest.Vehicles.Vehicle.OdometerReadings createPassportInqRqAutoRequestVehiclesVehicleOdometerReadings() {
        return new PassportInqRq.AutoRequest.Vehicles.Vehicle.OdometerReadings();
    }

    /**
     * Create an instance of {@link PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment.RawDataString }
     * 
     */
    public PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment.RawDataString createPassportInqRqAutoRequestRawDataSegmentsRawDataSegmentRawDataString() {
        return new PassportInqRq.AutoRequest.RawDataSegments.RawDataSegment.RawDataString();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionResponseDt")
    public JAXBElement<java.lang.String> createTransactionResponseDt(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_TransactionResponseDt_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.verisk.iso.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SuppressMatchInd")
    public JAXBElement<services.verisk.iso.String> createSuppressMatchInd(services.verisk.iso.String value) {
        return new JAXBElement<services.verisk.iso.String>(_SuppressMatchInd_QNAME, services.verisk.iso.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PendingResponseExpDt")
    public JAXBElement<XMLGregorianCalendar> createPendingResponseExpDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PendingResponseExpDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Org")
    public JAXBElement<java.lang.String> createOrg(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Org_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.verisk.iso.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CurCd")
    public JAXBElement<services.verisk.iso.String> createCurCd(services.verisk.iso.String value) {
        return new JAXBElement<services.verisk.iso.String>(_CurCd_QNAME, services.verisk.iso.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.verisk.iso.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RqUID")
    public JAXBElement<services.verisk.iso.String> createRqUID(services.verisk.iso.String value) {
        return new JAXBElement<services.verisk.iso.String>(_RqUID_QNAME, services.verisk.iso.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Addr")
    public JAXBElement<java.lang.String> createAddr(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Addr_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.verisk.iso.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionRequestDt")
    public JAXBElement<services.verisk.iso.String> createTransactionRequestDt(services.verisk.iso.String value) {
        return new JAXBElement<services.verisk.iso.String>(_TransactionRequestDt_QNAME, services.verisk.iso.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.verisk.iso.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferralInd")
    public JAXBElement<services.verisk.iso.String> createReferralInd(services.verisk.iso.String value) {
        return new JAXBElement<services.verisk.iso.String>(_ReferralInd_QNAME, services.verisk.iso.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgNameCd")
    public JAXBElement<java.lang.String> createMsgNameCd(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_MsgNameCd_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatusDesc")
    public JAXBElement<java.lang.String> createStatusDesc(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_StatusDesc_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringCd }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SearchBasisCd")
    public JAXBElement<StringCd> createSearchBasisCd(StringCd value) {
        return new JAXBElement<StringCd>(_SearchBasisCd_QNAME, StringCd.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgRqUID")
    public JAXBElement<java.lang.String> createMsgRqUID(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_MsgRqUID_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Language")
    public JAXBElement<java.lang.String> createLanguage(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Language_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<java.lang.String> createVersion(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_Version_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GenSessKey")
    public JAXBElement<java.lang.String> createGenSessKey(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_GenSessKey_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SuppressNotificationInd")
    public JAXBElement<java.lang.String> createSuppressNotificationInd(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_SuppressNotificationInd_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ServerDt")
    public JAXBElement<java.lang.String> createServerDt(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ServerDt_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustLoginId")
    public JAXBElement<java.lang.String> createCustLoginId(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_CustLoginId_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClientDt")
    public JAXBElement<XMLGregorianCalendar> createClientDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ClientDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustLangPref")
    public JAXBElement<java.lang.String> createCustLangPref(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_CustLangPref_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PolicyNumber")
    public JAXBElement<java.lang.String> createPolicyNumber(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_PolicyNumber_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SessKey")
    public JAXBElement<java.lang.String> createSessKey(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_SessKey_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPName")
    public JAXBElement<java.lang.String> createSPName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_SPName_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatusCd")
    public JAXBElement<java.lang.String> createStatusCd(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_StatusCd_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpDt")
    public JAXBElement<java.lang.String> createExpDt(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_ExpDt_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SignonRoleCd")
    public JAXBElement<java.lang.String> createSignonRoleCd(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_SignonRoleCd_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NotificationDt")
    public JAXBElement<XMLGregorianCalendar> createNotificationDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NotificationDt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPName", scope = CustId.class)
    public JAXBElement<java.lang.String> createCustIdSPName(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_SPName_QNAME, java.lang.String.class, CustId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustPermId", scope = CustId.class)
    public JAXBElement<java.lang.String> createCustIdCustPermId(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_CustIdCustPermId_QNAME, java.lang.String.class, CustId.class, value);
    }

}
