//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 01:50:47 PM MST 
//


package services.broker.objects.lexisnexis.cbr.response.actual;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for null.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType>
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Attached - 1 Car"/>
 *     &lt;enumeration value="Attached - 2 Car"/>
 *     &lt;enumeration value="Attached - 3 Car"/>
 *     &lt;enumeration value="Enclosed - 1 Car"/>
 *     &lt;enumeration value="Enclosed - 2 Car"/>
 *     &lt;enumeration value="Enclosed - 3 Car"/>
 *     &lt;enumeration value="Attached - Finished"/>
 *     &lt;enumeration value="Enclosed - Finished"/>
 *     &lt;enumeration value="Attached - Unfinished"/>
 *     &lt;enumeration value="Enclosed - Unfinished"/>
 *     &lt;enumeration value="No Parking"/>
 *     &lt;enumeration value="Carport - 1 Car"/>
 *     &lt;enumeration value="Carport - 2 Car"/>
 *     &lt;enumeration value="Carport - 3 Car"/>
 *     &lt;enumeration value="Breezway - 1 Car"/>
 *     &lt;enumeration value="Breezway - 2 Car"/>
 *     &lt;enumeration value="Breezway - 3 Car"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "")
@XmlEnum
public enum ParkingMaterialTypeEnum {

    @XmlEnumValue("Attached - 1 Car")
    ATTACHED_1_CAR("Attached - 1 Car"),
    @XmlEnumValue("Attached - 2 Car")
    ATTACHED_2_CAR("Attached - 2 Car"),
    @XmlEnumValue("Attached - 3 Car")
    ATTACHED_3_CAR("Attached - 3 Car"),
    @XmlEnumValue("Enclosed - 1 Car")
    ENCLOSED_1_CAR("Enclosed - 1 Car"),
    @XmlEnumValue("Enclosed - 2 Car")
    ENCLOSED_2_CAR("Enclosed - 2 Car"),
    @XmlEnumValue("Enclosed - 3 Car")
    ENCLOSED_3_CAR("Enclosed - 3 Car"),
    @XmlEnumValue("Attached - Finished")
    ATTACHED_FINISHED("Attached - Finished"),
    @XmlEnumValue("Enclosed - Finished")
    ENCLOSED_FINISHED("Enclosed - Finished"),
    @XmlEnumValue("Attached - Unfinished")
    ATTACHED_UNFINISHED("Attached - Unfinished"),
    @XmlEnumValue("Enclosed - Unfinished")
    ENCLOSED_UNFINISHED("Enclosed - Unfinished"),
    @XmlEnumValue("No Parking")
    NO_PARKING("No Parking"),
    @XmlEnumValue("Carport - 1 Car")
    CARPORT_1_CAR("Carport - 1 Car"),
    @XmlEnumValue("Carport - 2 Car")
    CARPORT_2_CAR("Carport - 2 Car"),
    @XmlEnumValue("Carport - 3 Car")
    CARPORT_3_CAR("Carport - 3 Car"),
    @XmlEnumValue("Breezway - 1 Car")
    BREEZWAY_1_CAR("Breezway - 1 Car"),
    @XmlEnumValue("Breezway - 2 Car")
    BREEZWAY_2_CAR("Breezway - 2 Car"),
    @XmlEnumValue("Breezway - 3 Car")
    BREEZWAY_3_CAR("Breezway - 3 Car"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ParkingMaterialTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParkingMaterialTypeEnum fromValue(String v) {
        for (ParkingMaterialTypeEnum c: ParkingMaterialTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
