//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 01:39:33 PM MST 
//


package services.broker.objects.address.requestresponse;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalAddress" type="{http://www.idfbins.com/AddressDTO}Address" minOccurs="0"/>
 *         &lt;element name="standardizedAddresses" type="{http://www.idfbins.com/AddressDTO}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addressStatus" type="{http://www.idfbins.com/AddressDTO}AddressStatus"/>
 *         &lt;element name="serviceStatus" type="{http://www.idfbins.com/common/ServiceStatus}ServiceStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressResponse", propOrder = {
    "originalAddress",
    "standardizedAddresses",
    "addressStatus",
    "serviceStatus"
})
public class AddressResponse {

    protected Address originalAddress;
    protected List<Address> standardizedAddresses;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AddressStatus addressStatus;
    @XmlElement(required = true)
    protected ServiceStatus serviceStatus;

    /**
     * Gets the value of the originalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.address.requestresponse.Address }
     *     
     */
    public Address getOriginalAddress() {
        return originalAddress;
    }

    /**
     * Sets the value of the originalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.address.requestresponse.Address }
     *     
     */
    public void setOriginalAddress(Address value) {
        this.originalAddress = value;
    }

    /**
     * Gets the value of the standardizedAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardizedAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardizedAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link broker.objects.address.requestresponse.Address }
     * 
     * 
     */
    public List<Address> getStandardizedAddresses() {
        if (standardizedAddresses == null) {
            standardizedAddresses = new ArrayList<Address>();
        }
        return this.standardizedAddresses;
    }

    /**
     * Gets the value of the addressStatus property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.address.requestresponse.AddressStatus }
     *     
     */
    public AddressStatus getAddressStatus() {
        return addressStatus;
    }

    /**
     * Sets the value of the addressStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.address.requestresponse.AddressStatus }
     *     
     */
    public void setAddressStatus(AddressStatus value) {
        this.addressStatus = value;
    }

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.address.requestresponse.ServiceStatus }
     *     
     */
    public ServiceStatus getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.address.requestresponse.ServiceStatus }
     *     
     */
    public void setServiceStatus(ServiceStatus value) {
        this.serviceStatus = value;
    }

}
