//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 10:33:19 AM MDT 
//


package services.services.com.idfbins.policyxml.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Activities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Activities"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LocationOfActivities" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WhatActivites" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Activities", propOrder = {
    "locationOfActivities",
    "whatActivites"
})
public class Activities {

    @XmlElement(name = "LocationOfActivities", required = true)
    protected String locationOfActivities;
    @XmlElement(name = "WhatActivites", required = true)
    protected String whatActivites;

    /**
     * Gets the value of the locationOfActivities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationOfActivities() {
        return locationOfActivities;
    }

    /**
     * Sets the value of the locationOfActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationOfActivities(String value) {
        this.locationOfActivities = value;
    }

    /**
     * Gets the value of the whatActivites property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhatActivites() {
        return whatActivites;
    }

    /**
     * Sets the value of the whatActivites property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhatActivites(String value) {
        this.whatActivites = value;
    }

}
