//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 10:33:19 AM MDT 
//


package services.services.com.idfbins.policyxml.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancelNotices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancelNotices"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="currentCancel" type="{http://www.idfbins.com/Policy}CancelNotice"/&gt;
 *         &lt;element name="previousCancel" type="{http://www.idfbins.com/Policy}CancelNotice" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelNotices", propOrder = {
    "currentCancel",
    "previousCancel"
})
public class CancelNotices {

    @XmlElement(required = true)
    protected services.services.com.idfbins.policyxml.policy.CancelNotice currentCancel;
    protected services.services.com.idfbins.policyxml.policy.CancelNotice previousCancel;

    /**
     * Gets the value of the currentCancel property.
     * 
     * @return
     *     possible object is
     *     {@link services.services.com.idfbins.policyxml.policy.CancelNotice }
     *     
     */
    public services.services.com.idfbins.policyxml.policy.CancelNotice getCurrentCancel() {
        return currentCancel;
    }

    /**
     * Sets the value of the currentCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link services.services.com.idfbins.policyxml.policy.CancelNotice }
     *     
     */
    public void setCurrentCancel(services.services.com.idfbins.policyxml.policy.CancelNotice value) {
        this.currentCancel = value;
    }

    /**
     * Gets the value of the previousCancel property.
     * 
     * @return
     *     possible object is
     *     {@link services.services.com.idfbins.policyxml.policy.CancelNotice }
     *     
     */
    public services.services.com.idfbins.policyxml.policy.CancelNotice getPreviousCancel() {
        return previousCancel;
    }

    /**
     * Sets the value of the previousCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link services.services.com.idfbins.policyxml.policy.CancelNotice }
     *     
     */
    public void setPreviousCancel(CancelNotice value) {
        this.previousCancel = value;
    }

}
