package repository.gw.enums;

import java.util.*;

public enum CPUWIssues {

	ClassCode0931_3_CarWasheshavesignificantbuiltinequipmentMakesurethevalueisincludedinthebuilding("Location: ${Location #}, Property: ${Property #}. Class Code 0931(3) Car Washes have significant built in equipment. Make sure the value is included in the building."),
	Reviewprotectivemeasuresforcontrolledsubstancesfromtheft("Location: ${Location #}, Property: ${Property #}. Review protective measures for controlled substances from theft."),
	ProvideUnderwritingwithapplicant_insuredslosscontrolprogramtoavoidspontaneouscombustionofhay("Location: ${Location #}, Property: ${Property #}. Provide Underwriting with applicant/insureds loss control program to avoid spontaneous combustion of hay."),
	ProvideUnderwritingwithmaintenanceprocedures("Location: ${Location #}, Property: ${Property #}. Provide Underwriting with maintenance procedures."),
	Mercantileoccupanciesover15000squarefeetarespecificallyratedContactUnderwritingforassistance("Location: ${Location #}, Property: ${Property #}. Mercantile occupancies over 15,000 square feet are specifically rated. Contact Underwriting for assistance."),
	ReplacementcosthasbeenrequestedonBusinessPersonalPropertyCoverageThepolicyhasrestrictionsonartantiquesorrarearticlesAspecializedfloatermaybeavailablethroughBrokerageInformapplicantlimitationofcoverage("Location: ${Location #}, Property: ${Property #}. Replacement cost has been requested on Business Personal Property Coverage. The policy has restrictions on art, antiques or rare articles. A specialized floater may be available through Brokerage. Inform applicant limitation of coverage."),
	ClassCode0570_27_RidingAcademiesisonthepolicypleasecontactBrokerageforGeneralLiabilitycoverage("Location: ${Location #}, Property: ${Property #}. Class Code 0570(27) Riding Academies is on the policy, please contact Brokerage for General Liability coverage."),
	Applicant_Insuredhasclass0844_20_RifleorPistolRangesonthepolicyGeneralLiabilitycoverageisnotavailableforRifleorPistolRangesPleasecontactBrokerageforGeneralLiabilitycoverage("Location: ${Location #}, Property: ${Property #}. Applicant/Insured has class 0844(20) Rifle or Pistol Ranges on the policy. General Liability coverage is not available for Rifle or Pistol Ranges. Please contact Brokerage for General Liability coverage."),
	ClassCode0844_23_isonthepolicyGeneralLiabilitycoverageisnotavailableforthisclassofbusiness("Location: ${Location #}, Property: ${Property #}. Class Code 0844(23) is on the policy. General Liability coverage is not available for this class of business."),
	ClassCode0921_23_TattooParlorsisonthepolicyCrimecoverageislimitedto$10000forInsideThePremisesTheftOfMoneyAndSecuritiesandOutsideThePremisesIfadditionalcoverageisrequiredcontactUnderwritingregardinganexception("Class Code 0921(23) Tattoo Parlors is on the policy. Crime coverage is limited to $10,000 for Inside The Premises � Theft Of Money And Securities and Outside The Premises. If additional coverage is required contact Underwriting regarding an exception."),
	ClassCode0921_23_TattooParlorsisonthepolicyGeneralLiabilitycoverageisnotavailablePleasecontactBrokeragefordesiredcoverage("Location: ${Location #}, Property: ${Property #}. Class Code 0921(23) Tattoo Parlors is on the policy. General Liability coverage is not available. Please contact Brokerage for desired coverage."),
	Thereisnocoverageforgrainhaystraworothercropsintheopen("Location: ${Location #}, Property: ${Property #}. There is no coverage for grain, hay, straw, or other crops in the open."),
	DiscretionaryPayrollExpenseCP1504hasmorethan180daysselectedpleasecontactUnderwritingforapproval("Location: ${Location #}, Property: ${Property #}. Discretionary Payroll Expense CP 15 04 has more than 180 days selected, please contact Underwriting for approval."),
	BusinessPersonalPropertylimitisover$200000inahazardousclass2400_1_PleasesubmittoUnderwritingforreviewUnderwriterpleasereviewwithUnderwritersupervisor("Location: ${Location #}, Property: ${Property #}. Business Personal Property limit is over $200,000 in a hazardous class 2400(1). Please submit to Underwriting for review. Underwriter please review with Underwriter supervisor."),
	HealthCareFacilitiesHomesfortheagedandhomesforthephysicallyhandicappedororphanedInpatientalcoholanddrugtreatmentandMentalarenoteligibleforGeneralLiabilityPleasecontactBrokeragefordesiredcoverage("Location: ${Location #}, Property: ${Property #}. Health Care Facilities � Homes for the aged and homes for the physically handicapped or orphaned, Inpatient alcohol and drug treatment, and Mental are not eligible for General Liability. Please contact Brokerage for desired coverage."),
	ReplacementCostdoesnotapplytocontentsofaresidenceInformclientofthislimitationorchangeittoActualCashValue("Location: ${Location #}, Property: ${Property #}. Replacement Cost does not apply to contents of a residence. Inform client of this limitation or change it to Actual Cash Value."),
	Applicant_InsuredisamachineryorequipmentdealerwedonothavedealerinventorycoveragePleasecontactBrokerageforcoverage("Location: ${Location #}, Property: ${Property #}. Applicant/Insured is a machinery or equipment dealer; we do not have dealer inventory coverage. Please contact Brokerage for coverage."),
	ModelhomefurnishingscanbeincludedasBusinessPersonalPropertyorcoveredintheInlandMarinesectionVisitwithclientregardingbestapproachforthem("Location: ${Location #}, Property: ${Property #}. Model home furnishings can be included as Business Personal Property or covered in the Inland Marine section. Visit with client regarding best approach for them."),
	ClassCode0702_7_isonthepolicyThedwellingmustbeinsuredtoreplacementvalueusingMS_B("Location: ${Location #}, Property: ${Property #}. Class Code 0702(7) is on the policy. The dwelling must be insured to replacement value using MS/B."),
	ClassCode0570_25_isonthepolicyRefertoUnderwritingduetoflammableandcombustiblematerialsandtoreviewthelosscontrolproceduresforchemicalstorage("Location: ${Location #}, Property: ${Property #}. Class Code 0570(25) is on the policy. Refer to Underwriting due to flammable and combustible materials and to review the loss control procedures for chemical storage."),
	ClassCode0570_25_PestcontrolserviceswithchemicalstorageisahazardousclassInordertoevaluateriskpleaseforwardinteriorphotosofchemicalstorageareas("Location: ${Location #}, Property: ${Property #}. Class Code 0570(25) Pest control services with chemical storage is a hazardous class. In order to evaluate risk please forward interior photos of chemical storage areas."),
	LiabilitycoverageforClassCode0567_84_PileDrivingcontractorsstorageisnotavailablePleasecontactBrokeragefordesiredcoverage("Location: ${Location #}, Property: ${Property #}. Liability coverage for Class Code 0567(84) Pile Driving � contractors storage is not available. Please contact Brokerage for desired coverage."),
	LiabilitycoverageforClassCode0567_85_PipelineConstructioncontractorsstorageisnotavailablePleasecontactBrokeragefordesiredcoverage("Location: ${Location #}, Property: ${Property #}. Liability coverage for Class Code 0567(85) Pipeline Construction � contractors storage is not available. Please contact Brokerage for desired coverage."),
	ClassCode0567_92_RailroadConstruction_contractorsarenoteligibleforGeneralLiabilityContactUnderwritingregardingtypeofpropertystoredlocationetcforpropertyconsideration("Location: ${Location #}, Property: ${Property #}. Class Code 0567(92) Railroad Construction-contractors are not eligible for General Liability. Contact Underwriting regarding type of property stored, location etc. for property consideration."),
	ClassCode0532_18_Restaurants_nocookingisforsaleoffoodproductslikeretailbakeriesandbeveragesexcludingalcoholicbeverages("Location: ${Location #}, Property: ${Property #}. Class Code 0532(18) Restaurants-no cooking is for sale of food products like retail bakeries and beverages excluding alcoholic beverages."),
	ClassCode2800_12_TextileMfgotherthanwearingapparelTextileSpinningWeavingorKnittingMillsisonthepolicyProvideUnderwritingwithlosscontrolprogramregardingfabricdustandlint("Location: ${Location #}, Property: ${Property #}. Class Code 2800(12) Textile Mfg. other than wearing apparel; Textile Spinning, Weaving or Knitting Mills is on the policy. Provide Underwriting with loss control program regarding fabric dust and lint."),
	ClassCode2800_12_TextileMfgotherthanwearingapparelTextileSpinningWeavingorKnittingMillsisonthepolicyThisclassofbusinessisextremelyhazardousProvideUnderwritingwithinteriorphotosforconsiderationIfwrittenalosscontrolreportmaybeordered("Location: ${Location #}, Property: ${Property #}. Class Code 2800(12) Textile Mfg. other than wearing apparel; Textile Spinning, Weaving or Knitting Mills is on the policy. This class of business is extremely hazardous. Provide Underwriting with interior photos for consideration. If written a loss control report maybe ordered."),
	ClassCode3009_12_TextileProductsMfgwearingapparelisonthepolicyProvideUnderwritingwithlosscontrolprogramregardingfabricdustandlint("Location: ${Location #}, Property: ${Property #}. Class Code 3009(12) Textile Products Mfg. � wearing apparel is on the policy. Provide Underwriting with loss control program regarding fabric dust and lint."),
	ClassCode3009_12_TextileProductsMfgwearingapparelisonthepolicyThisclassofbusinessisextremelyhazardousProvideUnderwritingwithinteriorphotosforconsiderationIfwrittenalosscontrolreportmaybeordered("Location: ${Location #}, Property: ${Property #}. Class Code 3009(12) Textile Products Mfg. � wearing apparel is on the policy. This class of business is extremely hazardous. Provide Underwriting with interior photos for consideration. If written a loss control report maybe ordered."),
	ClassCodePublicwarehousescanvarysignificantlyPleaseprovidetypesandquantitiesofproductsstoredmultipleinteriorphotosandlossrunsetcDependingonthetypeofgoodsstoredUnderwritingmayaskforadditionalinformation("Location: ${Location #}, Property: ${Property #}. Class Code ${Class Code} Public warehouses can vary significantly. Please provide types and quantities of products stored, multiple interior photos, and loss runs etc. Depending on the type of goods stored, Underwriting may ask for additional information."),
	ClassCodeisonthepolicyWarehouseshaveaBaileeexposureandWarehouseOperatorsLegalLiabilityexposureWesternCommunityInsuranceCompanydoesnotprovidecoverageforthesecoveragesPleasecontactBrokeragefordesiredcoverage("Location: ${Location #}, Property: ${Property #}. Class Code ${Class Code} is on the policy. Warehouses have a Bailee exposure and Warehouse Operators Legal Liability exposure. Western Community Insurance Company does not provide coverage for these coverages. Please contact Brokerage for desired coverage."),
	ClassCode6850_48_isonthepolicyUnderwriterpleasereviewlosscontrolprocedurestopreventsparksfromignitingproperty("Location: ${Location #}, Property: ${Property #}. Class Code 6850(48) is on the policy. Underwriter please review loss control procedures to prevent sparks from igniting property."),
	Applicant_InsuredisatradeorvocationalschoolProvidedetailsofoccupancytoUnderwritingforassistanceinclassifyingtherisk("Location: ${Location #}, Property: ${Property #}. Applicant/Insured is a trade or vocational school. Provide details of occupancy to Underwriting for assistance in classifying the risk."),
	ClassCode0567_138_SoapMfgisonthepolicySmallhobbyfarmermarkettypeofexposuresaregenerallyacceptableLargercommercialventurearenotduetochemicalsandheavyfireload("Location: ${Location #}, Property: ${Property #}. Class Code 0567(138) Soap Mfg. is on the policy. Small hobby, farmer market type of exposures are generally acceptable. Larger commercial venture are not due to chemicals and heavy fire load."),
	ClassCode0567_138_SoapMfgisonthepolicyPleaseprovideUnderwritingasamplelabelshowingtheingredientsTreatyexceptionisrequiredforliabilitycoverage("Location: ${Location #}, Property: ${Property #}. Class Code 0567(138) Soap Mfg. is on the policy. Please provide Underwriting a sample label showing the ingredients. Treaty exception is required for liability coverage."),
	ElectronicDatalimitinexcessof$50000requirespriorapprovalPleaseprovidedetailsregardingfirewallsvirusprotectionandoffpremisesbackupprocedures("Electronic Data limit in excess of $50,000 requires prior approval. Please provide details regarding firewalls, virus protection, and off premises back up procedures."),
	AutomaticIncreaseof8PERCENTorgreateraresubjecttoUnderwritingapproval("Location: ${Location #}, Property: ${Property #}. Automatic Increase of 8% or greater are subject to Underwriting approval."),
	Acopyoftheassociationagreementisrequiredpleaseuploadtofile("Location: ${Location #}, Property: ${Property #}. A copy of the association agreement is required, please upload to file."),
	BusinessIncomeexceeds$150000Pleasehaveapplicant_insuredcompleteaBusinessIncomeReport_WorkSheetCP1515orprovideotherfinancialstatementsthatshowthesameinformation("Location: ${Location #}, Property: ${Property #}. Business Income exceeds $150,000. Please have applicant/insured complete a Business Income Report/Work Sheet CP 15 15 or provide other financial statements that show the same information."),
	ExtraExpenseCoverageFormCP0050exceeds$150000Pleasehaveapplicant_insuredcompleteaBusinessIncomeReport_WorkSheetCP1515orprovideotherfinancialstatementsthatshowthesameinformation("Location: ${Location #}, Property: ${Property #}. Extra Expense Coverage Form CP 00 50 exceeds $150,000. Please have applicant/insured complete a Business Income Report/Work Sheet CP 15 15 or provide other financial statements that show the same information."),
	OrdinanceorLawCoverageCP0405hasbeenselectedandtheDemolitionCostLimitisinexcessof$50000thisrequiresUnderwritingapprovalPleaseprovideinformationregardingcostofdemolition("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 has been selected and the Demolition Cost Limit is in excess of $50,000, this requires Underwriting approval. Please provide information regarding cost of demolition."),
	OrdinanceorLawCoverageCP0405hasbeenselectedandtheDemolitionCostLimitisinexcessof$50000thisrequiresUnderwritingapprovalPleaseprovideinformationregardingcostofincreasedcostofconstruction("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 has been selected and the Demolition Cost Limit is in excess of $50,000, this requires Underwriting approval. Please provide information regarding cost of increased cost of construction."),
	OrdinanceorLawCoverageCP0405hasbeenselectedandtheCombinedLimitofInsuranceLimitisinexcessof$100000thisrequiresUnderwritingapprovalPleaseprovidedetailsofbuildingupdatesforelectricalplumbingheatingandlifesafetyWhatordinanceisapplicant_insuredconcernedabout("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 has been selected and the Combined Limit of Insurance Limit is in excess of $100,000, this requires Underwriting approval. Please provide details of building updates for electrical, plumbing, heating and life safety. What ordinance is applicant/insured concerned about?"),
	YouhaveindicatedthatasprinklersystemispresentSpecificrateswillapplytorisksotherthanapartmentordwellingUnderwritingwillvalidatesprinklersystemwithISRBandreclassifyaccordingly("Location: ${Location #}, Property: ${Property #}. You have indicated that a sprinkler system is present. Specific rates will apply to risks other than apartment or dwelling. Underwriting will validate sprinkler system with ISRB and reclassify accordingly."),
	MiscellaneousRealPropertyCoverageinexcessof$50000requirespriorapprovalSubmitacopyoftheAssociationAgreementforreview("Location: ${Location #}, Property: ${Property #}. Miscellaneous Real Property Coverage in excess of $50,000 requires prior approval. Submit a copy of the Association Agreement for review."),
	BuildinglimitforFunctionalBuildingValuationincludescostofdemolitionandincreasedcosttorebuildaccordingtocurrentordinancesandlaw("Location: ${Location #}, Property: ${Property #}. Building limit for Functional Building Valuation includes cost of demolition and increased cost to rebuild according to current ordinances and law."),
	FunctionalBuildingValuationistobeusedforolderbuildingsthatthearchitecturalstyleisobsoleteorunnecessaryduetocurrentuseofthebuildingBuildingmusthavesignificantupgradeswhereoriginalmaterialsarenolongeravailableandbewellmaintainedMS_Bisrequired("Location: ${Location #}, Property: ${Property #}. Functional Building Valuation is to be used for older buildings that the architectural style is obsolete or unnecessary due to current use of the building. Building must have significant upgrades where original materials are no longer available and be well maintained. MS/B is required."),
	Buildingislessthan50yearsoldpleaseexplainwhyFunctionalBuildingValuationisbeingrequested("Location: ${Location #}, Property: ${Property #}. Building is less than 50 years old, please explain why Functional Building Valuation is being requested."),
	FunctionalBuildingValuationisrequestedprovideexteriorinteriorphotosincludingheatingplumbingandelectricalSubmittoUnderwritingforconsideration("Location: ${Location #}, Property: ${Property #}. Functional Building Valuation is requested, provide exterior & interior photos including heating, plumbing and electrical. Submit to Underwriting for consideration."),
	SpoilageCoverageCP0440Limitexceeds$25000PleasecontactUnderwritingforapproval("Location: ${Location #}, Property: ${Property #}. Spoilage Coverage CP 04 40 Limit exceeds $25,000. Please contact Underwriting for approval."),
	SpoilageCoverageCP0440isinexcessof$50000whichrequiresamaintenanceagreementbeforecoveragecanbebound("Location: ${Location #}, Property: ${Property #}. Spoilage Coverage CP 04 40 is in excess of $50,000 which requires a maintenance agreement before coverage can be bound."),
	FoodContamination_BusinessInterruptionAndExtraExpense_CP1505Limitexceeds$25000PleasecontactUnderwritingforapproval("Location: ${Location #}, Property: ${Property #}. Food Contamination (Business Interruption And Extra Expense) CP 15 05 Limit exceeds $25,000. Please contact Underwriting for approval."),
	FoodContamination_BusinessInterruptionAndExtraExpense_CP1505Limitisinexcessof$50000whichrequiresamaintenanceagreementbeforecoveragecanbebound("Location: ${Location #}, Property: ${Property #}. Food Contamination (Business Interruption And Extra Expense) CP 15 05 Limit is in excess of $50,000 which requires a maintenance agreement before coverage can be bound."),
	TheftOfBuildingMaterialsAndSupplies_OtherThanBuildersRisk_CP1044limitsisinexcessof$25000thiswillrequireapprovalProvideUnderwriterwithadescriptionoftheprojecttheftsafeguardsanticipatedcompletiondateetc("Location: ${Location #}, Property: ${Property #}. Theft Of Building Materials And Supplies (Other Than Builders Risk) CP 10 44 limits is in excess of $25,000 this will require approval. Provide Underwriter with a description of the project, theft safeguards, anticipated completion date, etc."),
	Notifytheapplicant_insuredthatCP1055VandalismExclusionappliesto("Notify the applicant/insured that CP 10 55 Vandalism Exclusion applies to Location: ${Location #}, Property: ${Property #}."),
	SprinklerleakageExclusionappliestoInformclientoflimitation("Sprinkler leakage Exclusion applies to Location: ${Location #}, Property: ${Property #}. Inform client of limitation."),
	BurglaryandRobberyProtectiveSafeguardshasbeenaddedexplaintheconditionstotheinsured("Location: ${Location #}, Property: ${Property #}. Burglary and Robbery Protective Safeguards has been added, explain the conditions to the insured."),
	AdditionalInsuredBuildingOwnerCP1219hasbeenselectedprovidecopyofleaseatissuetodocumentinsurableinterest("Location: ${Location #}, Property: ${Property #}. Additional Insured � Building Owner CP 12 19 has been selected; provide copy of lease at issue to document insurable interest."),
	ProvideUnderwritingwithjustificationastowhythefixturesmachineryorequipmentnotattachedtothebuildingshouldnotbeconsideredBusinessPersonalProperty("Location: ${Location #}, Property: ${Property #}. Provide Underwriting with justification as to why the fixtures, machinery, or equipment not attached to the building should not be considered Business Personal Property."),
	AdditionalBuildingPropertyCP1415isonthebuildingPleaseincludevalueoffixturesmachineryorequipmentinthebuildingamountandshowontheMS_Bvalueestimate("Location: ${Location #}, Property: ${Property #}. Additional Building Property CP 14 15 is on the building. Please include value of fixtures, machinery or equipment in the building amount and show on the MS/B value estimate."),
	OutdoorSignsCP1440hasalimitover$50000thiswillrequireUnderwritingapprovalPleaseprovidephotosofthesignandinformationregardingvalue("Location: ${Location #}, Property: ${Property #}. Outdoor Signs CP 14 40 has a limit over $50,000, this will require Underwriting approval. Please provide photos of the sign and information regarding value."),
	OutdoorSignsCP1440isonthebuildingpleasesendphotosofthesigntoUnderwriting("Location: ${Location #}, Property: ${Property #}. Outdoor Signs CP 14 40 is on the building please send photos of the sign to Underwriting."),
	RadioOrTelevisionAntennasCP1450andthePropertyInTheOpenlimitisover$50000thiswillrequireUnderwritingapprovalPleaseprovidephotosheighthowtheyarestabilizedandinformationregardingvalue("Location: ${Location #}, Property: ${Property #}. Radio Or Television Antennas CP 14 50 and the Property In The Open limit is over $50,000, this will require Underwriting approval. Please provide photos, height, how they are stabilized, and information regarding value."),
	AgreedValuerequiresannualstatementofvaluescontractualagreementandupdatedMS_Bnotifytheinsured("Location: ${Location #}, Property: ${Property #}. Agreed Value requires annual statement of values, contractual agreement, and updated MS/B, notify the insured."),
	VerifythecorrectGLclassappliestothetypeofconstruction("Location: ${Location #}, Property: ${Property #}. Verify the correct GL class applies to the type of construction."),
	BuildersRiskinPC9or10withalimitof$500000ormorerequirespriorhomeofficeapprovalProvidephotosanddescriptionofclearspaceforconsideration("Location: ${Location #}, Property: ${Property #}. Builders� Risk in PC 9 or 10 with a limit of $500,000 or more requires prior home office approval. Provide photos and description of clear space for consideration."),
	IncreasetheBusinessIncomeLimittoreflecttheadditionalcoverageinDiscretionaryPayrollExpenseCP1504("Location: ${Location #}, Property: ${Property #}. Increase the Business Income Limit to reflect the additional coverage in Discretionary Payroll Expense CP 15 04."),
	TheFoodContamination_BusinessInterruptionAndExtraExpense_CP1505limitforAnnualAggregateAdditionalAdvertisingExpenseLimitexceeds$5000ContactUnderwritingwithinformationtojustifythislimitofcoverage("Location: ${Location #}, Property: ${Property #}. The Food Contamination (Business Interruption And Extra Expense) CP 15 05 limit for Annual Aggregate Additional Advertising Expense Limit exceeds $5,000. Contact Underwriting with information to justify this limit of coverage."),
	InsideThePremisesTheftOfMoneyAndSecuritieshasexceeded$30000UnderwritingapprovalisrequiredProvidedetailssuchasnumberofbankdepositsperweekaverageamountofdepositaverageamountkeptonpremisestypeofsafeguardsorsafeetc("Inside The Premises � Theft Of Money And Securities has exceeded $30,000. Underwriting approval is required. Provide details such as number of bank deposits per week, average amount of deposit, average amount kept on premises, type of safeguards or safe, etc.."),
	OutsideThePremiseshasexceeded$30000UnderwritingapprovalisrequiredProvidedetailssuchasnumberofbankdepositsperweekaverageamountofdepositaverageamountkeptonpremisestypeofsafeguardsorsafeetc("Outside The Premises has exceeded $30,000. Underwriting approval is required. Provide details such as number of bank deposits per week, average amount of deposit, average amount kept on premises, type of safeguards or safe, etc.."),
	ContactUnderwritingtoestablishEquipmentBreakdownreinsurance("Contact Underwriting to establish Equipment Breakdown reinsurance."),
	Thecombinedlimitatthislocationexceeds$750000andrequirespriorhomeofficeapproval("Loc: ${Location #}. The combined limit at this location exceeds $750,000 and requires prior home office approval."),
	Thecombinedlimitatthislocationexceeds$2000000andrequirespriorhomeofficeapprovalSubmitphotslossrunsandcostestimatorforconsideration("Loc: ${Location #}. The combined limit at this location exceeds $2,000,000 and requires prior home office approval. Submit phots, loss runs, and cost estimator for consideration."),
	ThecombinedlimitforBuildingCoverageBusinessPersonalPropertyCoveragePropertyInTheOpenPersonalPropertyOfOthersandBusinessIncomeCoverageFormexceeds$10000000AAICapprovalisrequired("Loc: ${Location #}. The combined limit for Building Coverage, Business Personal Property Coverage, Property In The Open, Personal Property Of Others, and Business Income Coverage Form exceeds $10,000,000. AAIC approval is required."),
	UtilityServicesDirectDamageCP0417hasUtilityasnotpublicPleaseprovideUnderwritingwithownershipsubscriptionagreementsandreliabilityoftheservice("Location: ${Location #}, Property: ${Property #}. Utility Services � Direct Damage CP 04 17 has Utility as not public. Please provide Underwriting with ownership, subscription agreements and reliability of the service."),
	AlarmcredithasbeengivenpleaseverifywithISRBorrequestcertificatefromthealarmcompany("Location: ${Location #}, Property: ${Property #}. Alarm credit has been given, please verify with ISRB or request certificate from the alarm company."),
	Notifytheapplicant_insuredthatCP1054WindorHailExclusionappliestopropertyonthispolicy("Location: ${Location #}, Property: ${Property #}. Notify the applicant/insured that CP 10 54 Wind or Hail Exclusion applies to property on this policy."),
	AlarmTypeofhasbeenselectedPleaseprovideUnderwritingwithcopiesofthecontractorcertificates("Location: ${Location #}, Property: ${Property #}. Alarm Type of ${Alarm Type option selected} has been selected. Please provide Underwriting with copies of the contract or certificates."),
	AdditionalCoveredPropertyCP1410hasbeenselectedIncludeadditionalcoveredpropertyvalueinthelimitofinsuranceasitwillbesubjecttothecoinsuranceclause("Location: ${Location #}, Property: ${Property #}. Additional Covered Property CP 14 10 has been selected. Include additional covered property value in the limit of insurance as it will be subject to the coinsurance clause."),
	BuildingisTentativeratedpleaseorderaspecificrate("Location: ${Location #}, Property: ${Property #}. Building is Tentative rated please order a specific rate."),
	ClassCodehasbeenselectedDetermineifEquipmentBreakdowntreatyexceptionisrequiredforthisclass("Class Code ${Class Code} has been selected. Determine if Equipment Breakdown treaty exception is required for this class."),
	ClassCodehasbeenselectedDetermineifEquipmentBreakdowntreatyexceptionisrequiredforthisclass2("Class Code ${Class Code} has been selected. Determine if Equipment Breakdown treaty exception is required for this class."),
	ExteriorHouseKeepingandMaintenanceneedsimprovementpleaseprovideUnderwritingwithmoredetails("Location: ${Location #}, Property: ${Property #}. Exterior House Keeping and Maintenance needs improvement please provide Underwriting with more details."),
	InteriorHouseKeepingandMaintenanceneedsimprovementpleaseprovideUnderwritingwithmoredetails("Location: ${Location #}, Property: ${Property #}. Interior House Keeping and Maintenance needs improvement please provide Underwriting with more details."),
	DocumentationofthetotalguttingwillberequiredBuildingisinexcellentconditionandreflectsgoodhousekeepingandmaintenanceSubmitrequeststoUnderwritingonatrialbasiswiththeappropriateinformationStructureswithoutsolidconcretefoundationsarenoteligible("Location: ${Location #}, Property: ${Property #}. Documentation of the total gutting will be required. Building is in excellent condition and reflects good housekeeping and maintenance. Submit requests to Underwriting on a trial basis with the appropriate information. Structures without solid concrete foundations are not eligible."),
	Propertycoveragewrittenonspecialformbasislimitscoveragefortheftofjewelrywatchesjewelspearlsetcto$2500("Location: ${Location #}, Property: ${Property #}. Property coverage written on special form basis limits coverage for theft of jewelry, watches, jewels, pearls etc. to $2,500."),
	IftheinsuredhasanobligationtoprotecttheinterestofContractorsorsub_contractorsinpoliciescoveringtenantsorlesseesofpremisesorTenantslesseesconcessionairesorexhibitorsinpoliciescoveringgenerallesseesmanagersoroperatorsofpremisescoverageisnoteligibleforLegalLiabilityFormpleasecontactBrokerageforcoverage("Location: ${Location #}, Property: ${Property #}. If the insured has an obligation to protect the interest of Contractors or sub-contractors, in policies covering tenants or lessees of premises or Tenants, lessees, concessionaires or exhibitors in policies covering general lessees, managers or operators of premises coverage is not eligible for Legal Liability Form, please contact Brokerage for coverage."),
	ElectronicDataisnoteligibleforthispolicypleaseremovethecoverage("Electronic Data is not eligible for this policy, please remove the coverage."),
	BecauseTheftExclusionCP1033isaddedtoabuildingwithBurglaryAndRobberyProtectiveSafeguardsCP1211nocreditwillbegivenforCP1211("Location: ${Location #}, Property: ${Property #}. Because Theft Exclusion CP 10 33 is added to a building with Burglary And Robbery Protective Safeguards CP 12 11, no credit will be given for CP 12 11."),
	ThisbuildingisaSpecificRatedbuildingpleasecontactUnderwritingsothattheymayenterarate("Location: ${Location #}, Property: ${Property #}. This building is a Specific Rated building, please contact Underwriting so that they may enter a rate."),
	UnderwriterAdditionalPropertyNotCoveredCP1420hasbeenaddedtothepropertyPleasecompletetheendorsement("Location: ${Location #}, Property: ${Property #}. Underwriter Additional Property Not Covered CP 14 20 has been added to the property. Please complete the endorsement."),
	AManualPublicProtectionClasshasbeenenteredthatdoesnotmatchtheAutoPublicProtectionClassUnderwriterpleaseverifytheProtectionClassiscorrect("Location: ${Location #}, Property: ${Property #}. A Manual Public Protection Class has been entered that does not match the Auto Public Protection Class. Underwriter please verify the Protection Class is correct."),
	ContactUnderwritingwithdetailsregardingwhenrepairsareanticipated("Location: ${Location #}, Property: ${Property #}. Contact Underwriting with details regarding when repairs are anticipated."),
	ContactUnderwritingwithdetailsofconditionofroofnoteifacceptableendorsementBP1404WindstormorHailLossesToRoofSurfacingActualCashValueLossSettlementwillbeattached("Location: ${Location #}, Property: ${Property #}. Contact Underwriting with details of condition of roof, note if acceptable endorsement BP 14 04 Windstorm or Hail Losses To Roof Surfacing Actual Cash Value Loss Settlement will be attached."),
	PleasedescribeconditionoftherooffortheUnderwritersconsideration("Location: ${Location #}, Property: ${Property #}. Please describe condition of the roof for the Underwriter's consideration."),
	Buildingisover3storiespleasecontactUnderwritingtoseeifthebuildingiseligibleforcoverage("Location: ${Location #}, Property: ${Property #}. Building is over 3 stories, please contact Underwriting to see if the building is eligible for coverage."),
	FlatroofsneedregularmaintenanceNotifyapplicant_insuredthatincreasedlosscontrolisrecommendedPolicyhaslimitationsforwaterdamagewearandtearandmaintenance("Location: ${Location #}, Property: ${Property #}. Flat roofs need regular maintenance. Notify applicant/insured that increased loss control is recommended. Policy has limitations for water damage, wear and tear and maintenance."),
	ThispropertyisgenerallynoteligibleforcoveragewiththisrooftypePleaserefertoUnderwritingforconsideration("Location: ${Location #}, Property: ${Property #}. This property is generally not eligible for coverage with this roof type. Please refer to Underwriting for consideration."),
	PleaseverifyaddressonpolicylocationsCouldresultinaProtectionClasschangePleasecontactUnderwritingwithdetails("Please verify address on policy locations. Could result in a Protection Class change. Please contact Underwriting with details."),
	ManualentryofLongitudeandLatituderequiresUnderwritingapproval("Manual entry of Longitude and Latitude requires Underwriting approval."),
	CostestimatoryearisrequiredatPolicyIssuancePleaseverifythatwehavereceivedthecostestimatorandentertheyearbeforeapproving("Location: ${Location #}, Property: ${Property #}. Cost estimator year is required at Policy Issuance. Please verify that we have received the cost estimator and enter the year before approving."),
	PhotoyearisrequiredatPolicyIssuancePleaseverifythatwehavereceivedthephotosandentertheyearbeforeapproving("Location: ${Location #}, Property: ${Property #}. Photo year is required at Policy Issuance. Please verify that we have received the photos and enter the year before approving."),
	Manufactured_MobileHomeisolderthan30yearsRefertoUnderwritingforconsideration("Location: ${Location #}, Property: ${Property #}. Manufactured/Mobile Home is older than 30 years. Refer to Underwriting for consideration."),
	Thehood_ductworkislessthan18inchesfromthecombustiblematerialspleaserefertoUnderwritertodetermineeligibility("Location: ${Location #}, Property: ${Property #}. The hood/duct work is less than18 inches from the combustible materials, please refer to Underwriter to determine eligibility."),
	ClassCode0921_23_TattooParlorsisonthepolicyCrimecoverageislimitedto$10000forInsideThePremisesTheftOfMoneyAndSecuritiesandOutsideThePremisesThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexception("Class Code 0921(23) Tattoo Parlors is on the policy. Crime coverage is limited to $10,000 for Inside The Premises � Theft Of Money And Securities and Outside The Premises. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception."),
	BusinessPersonalPropertylimitisover$200000inahazardousclass2400_1_ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionUnderwriterpleasereviewwithUnderwritersupervisor("Location: ${Location #}, Property: ${Property #}. Business Personal Property limit is over $200,000 in a hazardous class 2400(1). The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Underwriter please review with Underwriter supervisor."),
	ElectronicDatalimitisover$50000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleaseprovidedetailsregardingfirewallsvirusprotectionandoffpremisesbackupprocedures("Electronic Data limit is over $50,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please provide details regarding firewalls, virus protection, and off premises back up procedures."),
	BusinessIncomeexceeds$150000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleasehaveapplicant_insuredcompleteaBusinessIncomeReport_WorkSheetCP1515orprovideotherfinancialstatementsthatshowthesameinformation("Location: ${Location #}, Property: ${Property #}. Business Income exceeds $150,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please have applicant/insured complete a Business Income Report/Work Sheet CP 15 15 or provide other financial statements that show the same information."),
	ExtraExpenseCoverageFormCP0050exceeds$150000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleasehaveapplicant_insuredcompleteaBusinessIncomeReport_WorkSheetCP1515orprovideotherfinancialstatementsthatshowthesameinformation("Location: ${Location #}, Property: ${Property #}. Extra Expense Coverage Form CP 00 50 exceeds $150,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please have applicant/insured complete a Business Income Report/Work Sheet CP 15 15 or provide other financial statements that show the same information."),
	OrdinanceorLawCoverageCP0405andtheDemolitionCostLimitisover$50000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleaseprovideinformationregardingcostofdemolition("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 and the Demolition Cost Limit is over $50,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please provide information regarding cost of demolition."),
	OrdinanceorLawCoverageCP0405andtheIncreasedCostOfConstructionCoverageLimitisover$50000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleaseprovideinformationregardingtheincreasedcostofconstruction("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 and the Increased Cost Of Construction Coverage Limit is over $50,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please provide information regarding the increased cost of construction."),
	OrdinanceorLawCoverageCP0405andtheCombinedLimitofInsuranceLimitisover$100000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionPleaseprovidedetailsofbuildingupdatesforelectricalplumbingheatingandlifesafetyWhatordinanceisapplicant_insuredconcernedabout("Location: ${Location #}, Property: ${Property #}. Ordinance or Law Coverage CP 04 05 and the Combined Limit of Insurance Limit is over $100,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Please provide details of building updates for electrical, plumbing, heating and life safety. What ordinance is applicant/insured concerned about?"),
	MiscellaneousRealPropertyCoverageisover$50000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionSubmitacopyoftheAssociationAgreementforreview("Location: ${Location #}, Property: ${Property #}. Miscellaneous Real Property Coverage is over $50,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Submit a copy of the Association Agreement for review."),
	FoodContamination_BusinessInterruptionAndExtraExpense_CP1505Limitisover$50000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexception("Location: ${Location #}, Property: ${Property #}. Food Contamination (Business Interruption And Extra Expense) CP 15 05 Limit is over $50,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception."),
	TheftOfBuildingMaterialsAndSupplies_OtherThanBuildersRisk_CP1044limitisover$25000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionProvideUnderwriterwithadescriptionoftheprojecttheftsafeguardsanticipatedcompletiondateetc("Location: ${Location #}, Property: ${Property #}. Theft Of Building Materials And Supplies (Other Than Builders Risk) CP 10 44 limit is over $25,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Provide Underwriter with a description of the project, theft safeguards, anticipated completion date, etc."),
	TheFoodContamination_BusinessInterruptionAndExtraExpense_CP1505limitforAnnualAggregateAdditionalAdvertisingExpenseLimitisover$5000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexception("Location: ${Location #}, Property: ${Property #}. The Food Contamination (Business Interruption And Extra Expense) CP 15 05 limit for Annual Aggregate Additional Advertising Expense Limit is over $5,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception."),
	InsideThePremisesTheftOfMoneyAndSecuritieslimitisover$30000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionProvidedetailssuchasnumberofbankdepositsperweekaverageamountofdepositaverageamountkeptonpremisestypeofsafeguardsorsafeetc("Inside The Premises � Theft Of Money And Securities limit is over $30,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Provide details such as number of bank deposits per week, average amount of deposit, average amount kept on premises, type of safeguards or safe, etc.."),
	OutsideThePremiseslimitisover$30000ThelimithasbeenincreasedfromapriorapprovaloftoPleasecontactUnderwritingregardinganexceptionProvidedetailssuchasnumberofbankdepositsperweekaverageamountofdepositaverageamountkeptonpremisestypeofsafeguardsorsafeetc("Outside The Premises limit is over $30,000. The limit has been increased from a prior approval of ${Prior policy period limit} to ${Current policy period limit}. Please contact Underwriting regarding an exception. Provide details such as number of bank deposits per week, average amount of deposit, average amount kept on premises, type of safeguards or safe, etc.."),
	TheManualPublicProtectionClassCodehasbeenchangedfromtoUnderwriterpleaseverifytheProtectionClassiscorrect("Location: ${Location #}, Property: ${Property #}. The Manual Public Protection Class Code has been changed from ${Prior policy period manual protection class number} to ${Current policy period manual protection class number}. Underwriter please verify the Protection Class is correct."),
	UnderwriterpleasereviewtheWiringtypeasotherhasbeenselected("Location: ${Location #}, Property: ${Property #}. Underwriter please review the Wiring type as other has been selected."),
	Theapplicant_insuredisafraternalorganizationorlaborunionPleaseexplainthatthepolicydoesnotprovidecoverageforlossresultingfromunauthorizedadvancestoamemberfordelinquentduesorassessmentsThereisarequirementforanannualauditofthebooksandaccountsincludingallsecuritiesandbankbalancespertainingtoeachemployee("The applicant/insured is a fraternal organization or labor union. Please explain that the policy does not provide coverage for loss resulting from unauthorized advances to a member for delinquent dues or assessments. There is a requirement for an annual audit of the books and accounts including all securities and bank balances, pertaining to each employee."),
	EquipmentBreakdownEnhancementEndorsementIDCP311002isonthepolicyThisendorsementdoesnotextendcoveragetoBuildersRisk("Equipment Breakdown Enhancement Endorsement IDCP 31 1002 is on the policy. This endorsement does not extend coverage to Builders' Risk.");
	String value;
	
	private CPUWIssues(String type){
		value = type;
	}
	
	public String getValue(){
		return value;
	}
	
	
	 public static CPUWIssues fromString(String text) {
		    for (CPUWIssues b : CPUWIssues.values()) {
		      if (b.getValue().equalsIgnoreCase(text)) {
		        return b;
		      }
		    }
		    return null;
	 }//end fromString
	
	
	
	private static final List<CPUWIssues> VALUES = Collections.unmodifiableList(Arrays.asList(values()));
	private static final int SIZE = VALUES.size();
	private static final Random RANDOM = new Random();

	public static CPUWIssues random()  {
		return VALUES.get(RANDOM.nextInt(SIZE));
	}
	
	public static List<CPUWIssues> random(int listSize)  {
		List<CPUWIssues> returnList = new ArrayList<CPUWIssues>();
		for(int i = 0; i<= listSize; i++) {
			CPUWIssues issue;
			do {
				issue = random();
			} while(returnList.contains(issue));
			
			returnList.add(issue);
		}
		return returnList;
	}
	
	
}





















