package repository.gw.enums;

public enum CPUWQuestions {
	
	ClassCode0921_1_Isshippingpackingandcratingmaterialsproperlystoredandfreeofdebris("Shipping, packing, and crating materials are improperly stored and not free of debris. Describe and photograph conditions and contact underwriting regarding acceptability."),
	ClassCode0921_1_AreallchemicalsstoredinNFPAapprovedstoragereceptacles("Chemicals are not stored in NFPA approved storage receptacles. Provide underwriting with details to determine acceptability."),
	ClassCode0921_1_Arechemicalsoakedragsdisposedofproperly("Chemical soaked rags are not disposed of properly. Advise if insured is willing to change their procedures and contact underwriting regarding acceptability."),
	ClassCode0921_1_Isstockcoverageforfineartsdesired("Stock consisting of fine arts is limited to ACV. Contact brokerage for specialized coverage."),
	ClassCode2400_1_Doesapplicantinsuredhaveamaintenanceagreementonproductionmachinery("Provide a copy of the maintenance agreement when bound."),
	ClassCode0841_Arelanesfinishedwithlacquerbasedfinishes("Lanes are finished with lacquer based finishes. Increased pricing may be required."),
	ClassCode0841_Doesapplicantinsuredhaveafullscheduleofleaguebowling("Applicant/Insured does not have an active bowling league program which is a sign of a declining business. Provide financial statements to underwriting for consideration."),
	ClassCode0841_Howmanydaysaweekarebowlingleaguesactive("Applicant/Insured does not have a full league schedule. Provide financial information to underwriting for consideration."),
	ClassCode0841_Isthepremisescomprisedofonemainfiredivision("Premises comprised of one main fire division- no fire walls are present. Please provide interior photos to underwriting for consideration."),
	ClassCode0841_Laneresurfacingisperformedby("Lane resurfacing is performed by insured. Describe experience in this activity as well as fire rating of products used."),
	ClassCode0841_Istherearestaurant("There is a restaurant on premises please add correct class."),
	ClassCode0841_Arethereretailsalesofequipmentclothingetc("There are retail sales please add correct class."),
	ClassCode1150_Apartment("Applicant/Insured's building is a structure that is not an apartment or dwelling. Contact underwriting regarding acceptability. Verify General Liability classes are correct."),
	ClassCode1150_ColdStorage("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode1150_Dwelling("Applicant/Insured's building is a structure that is not an apartment or dwelling. Contact underwriting regarding acceptability. Verify General Liability classes are correct."),
	ClassCode1150_Electricalpower_boilersturbinegeneratorsfuelcellsorsolar("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode1150_Hospitalormedicalfacilities("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode1150_Printer("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode1150_SewageTreatment("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode1150_WaterTreatment("Applicant/Insured's building is a structure that requires reinsurance approval for equipment breakdown."),
	ClassCode0567_15_Isstockcoveragetobeincluded("Stock coverage can also be covered under Camera and Musical Instruments Dealers Form as well. Consider coverage differences."),
	ClassCode0931_3_Doespropertyhavebarrierstopreventvehiclesfromhittingthebuilding("Property does not have barriers to prevent vehicles from hitting the building. Contact underwriting regarding deductibles offered and surcharges."),
	ClassCode0562_2_Hasapplicantinsuredhadpriorburglaryortheftlosses("Applicant/Insured has prior burglary or theft losses, please describe what has been done to prevent future losses and submit a loss run for consideration."),
	ClassCode0570_7_Doesapplicantinsuredhaveanhydrousammoniaonpremises("Applicant/Insured has anhydrous ammonia on premises. Please explain loss control for: leaks, ventilation, theft, safeguards to prevent losses for consideration."),
	ClassCode0570_7_Doesapplicantinsuredhavebulkfertilizer("Applicant/Insured has bulk fertilizer. Provide loss control programs, amount of product and other information for underwriting consideration."),
	ClassCode0580_2_Areflammableitemsiechemicalsfuelsandsolventsstoredawayfrompotentialignitionsources("Flammable items i.e. chemicals, fuels and solvents are not stored away from potential ignition sources. Inform applicant/insured that we are unable to insure the exposure unless this loss control measure is implemented. Describe changes to be made."),
	ClassCode0580_2_Aremulchesandcompostpileslocatedawayfromthebuilding("Mulches and compost piles are next to the building. These materials are prone to spontaneous combustion. Please have the applicant/insured relocate them. Please let underwriting know date when they will be removed."),
	ClassCode0570_13_Isstockofthehatcherycoveragedesired("Stock of hatcheries is not eligible for special form coverage."),
	ClassCode0570_14_Hasapplicantinsuredhadahayorstrawfire("Applicant has prior hay or straw fires submit loss runs for consideration."),
	ClassCode0570_14_Ishayorstrawstoredinthebuilding("Hay or straw is stored in the building, provide details to underwriting regarding amount and send interior photos for consideration and advice on IRPM."),
	ClassCode0196_Arethereadditionalstructuresorbuildingsatthedwellinglocation("Additional structures or buildings are present. Please add as separate building as there is no automatic coverage for it."),
	ClassCode0742_Doestheapplicanthavekitchenunitsavailabletoguests("Underwriting please review applicant has kitchen units available to guests."),
	ClassCode0743_Doestheapplicanthavekitchenunitsavailabletoguests("Underwriting please review applicant has kitchen units available to guests."),
	ClassCode0744_Doestheapplicanthavekitchenunitsavailabletoguests("Underwriting please review applicant has kitchen units available to guests."),
	ClassCode0520_9_Doesapplicantinsuredpressclothes("Applicant insured press clothes change to class 0911 � Laundry and Dry Cleaning or Dyeing Receiving Stations � With pressing."),
	ClassCode0520_9_Doesapplicantinsuredprovidetheactualdrycleaningservice("Applicant/Insured provide the actual dry cleaning service. Rate as Laundries and dry cleaning plants or stores."),
	ClassCode0911_1_Doesapplicantinsuredprovidetheactualdrycleaningservice("Applicant/Insured provides the actual dry cleaning service. Rate as Laundries and dry cleaning plants or stores."),
	ClassCode0912_1_Aresolventfilterschangedregularly("Solvent filters are not changed regularly. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0912_1_Islintandfilterresiduedisposedincoveredoutsidecontainers("Lint and filter residue is not disposed in covered outside containers. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0912_1_Arechemicalsproperlystored("Chemicals are not properly stored. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0912_1_Aresteammachinesleftunattendedwhentheyareon("Steam machines left unattended when they are on. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0913_2_Aresolventfilterschangedregularly("Solvent filters are not changed regularly. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0913_2_Islintandfilterresiduedisposedincoveredoutsidecontainers("Lint and filter residue is not disposed in covered outside containers. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0913_2_Arechemicalsproperlystored("Chemicals are not properly stored. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0913_2_Aresteammachinesleftunattendedwhentheyareon("Steam machines left unattended when they are on. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0565_2_Doesapplicantinsuredhaveindividualjewelryitemsover$100("Applicant/Insured has individual jewelry items over $100. Special form coverage limits theft to $2,500. Jewelers Block Coverage is recommended for all causes of loss. Notify applicant/insured of limitations of coverage."),
	ClassCode6900_12_Doesapplicantinsuredhaveindividualjewelryorpreciousstonesover$100("Applicant/Insured has individual jewelry or precious stones over $100. Special form coverage limits theft to $2,500. Jewelers Block Coverage is recommended for all causes of loss. Notify applicant/insured of limitations of coverage."),
	ClassCode0563_14_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0563_14_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode0563_14_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode0563_14_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0922_26_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0922_26_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode0922_26_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode0922_26_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0933_8_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0933_8_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode0933_8_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode0933_8_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode6850_27_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode6850_27_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode6850_27_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode6850_27_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0932_2_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0932_2_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode0932_2_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode0932_2_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0932_2_IfautobodyworkisperformeddoestheclienthaveaULapprovedpaintboothonpremises("Auto body work is performed and there is no UL approved paint booth on premises. Contact underwriting for review of property exposure, if any."),
	ClassCode0933_3_Isthefuelstoredanddispensedawayfromthebuilding("Fuel is not stored and dispensed away from the building. This practice is unacceptable. If applicant/insured is unwilling to change, refer to brokerage. Let underwriting know future plans."),
	ClassCode0933_3_Dopartscleaningequipmenthaveanoperationaltrapdoorwhichautomaticallyclosesintheeventofafire("Flammable chemicals used in parts cleaning machines without automatic trap door. Provide underwriting with details so pricing can be determined."),
	ClassCode0933_3_Doesapplicantinsuredhaveaspraypaintingbooth("Applicant/Insured has a spray painting booth. Risk should be specifically rated contact underwriting for assistance."),
	ClassCode0933_3_WhenchemicalsarenotinusearetheyproperlystoredinaNFPAapprovedfireresistantcabinet("Chemicals are not properly stored in a NFPA approved fire resistant cabinet. If applicant/insured is unwilling to do so, refer to brokerage. Let underwriting know future plans."),
	ClassCode0933_3_IfautobodyworkisperformeddoestheclienthaveaULapprovedpaintboothonpremises("Auto body work is performed and there is no UL approved paint booth on premises. Contact underwriting for review of property exposure, if any."),
	ClassCode0562_3_Hasapplicantinsuredhadpriorburglaryortheftlosses("Applicant/Insured has prior burglary or theft losses, please describe what has been done to prevent future losses and submit a loss run for consideration."),
	ClassCode0567_71_Doesthemuseumhavefinearts("The museum's has fine arts. They need specialized fine arts coverage. Contact brokerage for assistance. If other coverage is secured contact underwriting to determine if a Property Not Covered endorsement is appropriate."),
	ClassCode0567_71_Doesapplicantinsuredhavepersonalpropertyofothersonloan("Museum has personal property of others on loan. A separate limit should be scheduled or owner should have coverage. Property will be valued at ACV. If additional protection is required contact brokerage for potential coverage."),
	ClassCode1051_3_Doesthemuseumhavefinearts("The museum's has fine arts. They need specialized fine arts coverage. Contact brokerage for assistance. If other coverage is secured contact underwriting to determine if a Property Not Covered endorsement is appropriate."),
	ClassCode1051_3_Doesapplicantinsuredhavepersonalpropertyofothersonloan("Museum has personal property of others on loan. A separate limit should be scheduled or owner should have coverage. Property will be valued at ACV. If additional protection is required contact brokerage for potential coverage."),
	ClassCode0580_3_Other("green house has unusual construction. Contact Underwriting with details for approval."),
	ClassCode0580_3_Areflammableitemsiechemicalsfuelsandsolventsstoredawayfrompotentialignitionsources("Flammable items i.e. chemicals, fuels and solvents are not stored away from potential ignition sources. Inform applicant/insured that we are unable to insure the exposure unless this loss control measure is implemented. Describe changes to be made."),
	ClassCode0580_3_Aremulchesandcompostpileslocatedawayfromthebuilding("Mulches and compost piles are next to the building. These materials are prone to spontaneous combustion. Please have the applicant/insured relocate them. Please let underwriting know date when they will be removed."),
	ClassCode0570_20_Aremulchesandcompostpileslocatedawayfromthebuilding("Mulches and compost piles are next to the building. These materials are prone to spontaneous combustion. Please have the applicant/insured relocate them. Please let underwriting know date when they will be removed."),
	ClassCode0570_20_Areflammableitemsiechemicalsfuelsandsolventsstoredawayfrompotentialignitionsources("Flammable items i.e. chemicals, fuels and solvents are not stored away from potential ignition sources. Inform applicant/insured that we are unable to insure the exposure unless this loss control measure is implemented. Describe changes to be made."),
	ClassCode0922_10_Isthelaundrysuserestrictedtotenantsonly("Laundry is not restricted to tenants only. Please classify laundries and dry cleaners-self-service class 0913(1)."),
	ClassCode3959_7_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode3959_7_Isdustsuppressionequipmentventedtotheoutsideofthebuilding("Dust suppression equipment is not vented to the outside of the building. Please provide interior photos and loss control measures for consideration."),
	ClassCode3959_7_Haveemployeesbeentrainedinuseoffireextinguishers("Employees are not trained in use of fire extinguishers. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode3959_10_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode3959_10_Isdustsuppressionequipmentventedtotheoutsideofthebuilding("Dust suppression equipment is not vented to the outside of the building. Please provide interior photos and loss control measures for consideration."),
	ClassCode3959_10_Haveemployeesbeentrainedinuseoffireextinguishers("Employees are not trained in use of fire extinguishers. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode0844_23_Doestheapplicantinsuredhaveashootinggallery("Applicant/Insured has a shooting gallery. Contact underwriting for assistance in rating."),
	ClassCode0844_23_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode0844_23_Doestheapplicantinsuredprovidefoodservice("Applicant/Insured provides food service. Please add a restaurant class to cover the exposure."),
	ClassCode0922_36_Doesapplicantinsuredstorehayorstrawinthebuilding("Applicant/Insured stores hay or straw in the building. Provide quantities and interior photos to underwriting for consideration and advice on IRPM."),
	ClassCode0570_29_DoesApplicantInsuredstorehayorstrawinthebuilding("Applicant/Insured stores hay or straw in the building. Provide quantities and interior photos to underwriting for consideration and advice on IRPM."),
	ClassCode0520_11_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode3009_11_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode0570_27_Doesapplicantinsuredstorehayorstrawinthebuilding("Applicant/Insured stores hay or straw in the building. Provide quantities and interior photos to underwriting for consideration and advice on IRPM."),
	ClassCode0844_20_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode0921_23_Areautoclavesequippedwithtemperatureprotectiondevicesorautomaticshut_offcontrols("Autoclaves are not equipped with temperature protection devices or automatic shut-off controls. Please provide underwriting loss control details regarding potential overheating."),
	ClassCode0844_19_Isthisacampgroundrecreationalfacility("Recreational facility is a campground- due to the number of options refer to rules in the campground description."),
	ClassCode0844_19_Isthisaclubrecreationalfacility("Recreational facility is a club- due to the number of options refer to rules in the club description."),
	ClassCode0844_19_Isthisagolfclubandsimilarexposurerecreationalfacility("Recreational facility is a golf club contact underwriting for assistance due to the number of classes that could apply."),
	ClassCode0844_19_Isthisaskatingrinkrecreationalfacility("Recreational facility is a skating rink-refer to skating rink for correct classification."),
	ClassCode0844_19_Isthisarecreationalfacilitythatwasnotmentionedabove("Recreational facility is not classified contact underwriting for assistance due to the number of classes that could apply."),
	ClassCode0545_Other("Refer heating source to underwriting for review of acceptability."),
	ClassCode1230_2_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode1211_3_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode1220_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode1213_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode1212_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode6850_48_Doesapplicantinsuredhaveadesignatedsmokingareaequippedwithself_closingfire_resistantreceptacles("Applicant/Insured allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode6850_48_Areequipmentoperatorsprohibitedfromleavinganypieceofmetal_workingmachineryunattendedwhileitisinoperation("Equipment operators can leave metal-working machinery unattended while it is in operation. Determine if they are willing to change their procedures and contact underwriting with details."),
	ClassCode6850_48_Doestheinsuredweldonsite("Welding shops are specifically rated. Contact underwriting for pricing."),
	ClassCode2459_2_Doesapplicantinsuredallowsmokingonpremises("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode2459_2_Doesapplicantinsuredhaveadesignatedsmokingareaequippedself_closingfire_resistantreceptacles("Applicant allows smoking and does not have designated smoking areas with self-closing, fire-resistant receptacles. Determine if they are willing to implement this loss control suggestion and contact underwriting."),
	ClassCode2459_2_Doesapplicantinsuredhaveamaintenanceagreementfortheproductionmachinery("Applicant/Insured does not have a maintenance agreement for the production machinery. Please provide qualifications of in house maintenance engineers for consideration.");

	String value;
	
	private CPUWQuestions(String type) {
		value = type;
	}
	
	public String getValue(){
		return value;
	}
	
	public static CPUWQuestions fromString(String text) {
	    for (CPUWQuestions b : CPUWQuestions.values()) {
	      if (b.getValue().equalsIgnoreCase(text)) {
	        return b;
	      }
	    }
	    return null;
	}//end fromString
	
}
