//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 03:05:28 PM MDT 
//


package services.verisk.tu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HM_SEG_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}HM_SEG_LENGTH" minOccurs="0"/>
 *         &lt;element ref="{}HM_MSG_CODE" minOccurs="0"/>
 *         &lt;element ref="{}HM_SRC_IND" minOccurs="0"/>
 *         &lt;element ref="{}HM_ADDR_MATCH_FLAG" minOccurs="0"/>
 *         &lt;element ref="{}HM_POB_TEL_IND" minOccurs="0"/>
 *         &lt;element ref="{}HM_POB_TEL_NUM" minOccurs="0"/>
 *         &lt;element ref="{}HM_THRESH_NUM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hmsegtype",
    "hmseglength",
    "hmmsgcode",
    "hmsrcind",
    "hmaddrmatchflag",
    "hmpobtelind",
    "hmpobtelnum",
    "hmthreshnum"
})
@XmlRootElement(name = "HAWK-MSG-CODE")
public class HAWKMSGCODE {

    @XmlElement(name = "HM_SEG_TYPE")
    protected String hmsegtype;
    @XmlElement(name = "HM_SEG_LENGTH")
    protected String hmseglength;
    @XmlElement(name = "HM_MSG_CODE")
    protected String hmmsgcode;
    @XmlElement(name = "HM_SRC_IND")
    protected String hmsrcind;
    @XmlElement(name = "HM_ADDR_MATCH_FLAG")
    protected String hmaddrmatchflag;
    @XmlElement(name = "HM_POB_TEL_IND")
    protected String hmpobtelind;
    @XmlElement(name = "HM_POB_TEL_NUM")
    protected String hmpobtelnum;
    @XmlElement(name = "HM_THRESH_NUM")
    protected String hmthreshnum;

    /**
     * Gets the value of the hmsegtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMSEGTYPE() {
        return hmsegtype;
    }

    /**
     * Sets the value of the hmsegtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMSEGTYPE(String value) {
        this.hmsegtype = value;
    }

    /**
     * Gets the value of the hmseglength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMSEGLENGTH() {
        return hmseglength;
    }

    /**
     * Sets the value of the hmseglength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMSEGLENGTH(String value) {
        this.hmseglength = value;
    }

    /**
     * Gets the value of the hmmsgcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMMSGCODE() {
        return hmmsgcode;
    }

    /**
     * Sets the value of the hmmsgcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMMSGCODE(String value) {
        this.hmmsgcode = value;
    }

    /**
     * Gets the value of the hmsrcind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMSRCIND() {
        return hmsrcind;
    }

    /**
     * Sets the value of the hmsrcind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMSRCIND(String value) {
        this.hmsrcind = value;
    }

    /**
     * Gets the value of the hmaddrmatchflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMADDRMATCHFLAG() {
        return hmaddrmatchflag;
    }

    /**
     * Sets the value of the hmaddrmatchflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMADDRMATCHFLAG(String value) {
        this.hmaddrmatchflag = value;
    }

    /**
     * Gets the value of the hmpobtelind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMPOBTELIND() {
        return hmpobtelind;
    }

    /**
     * Sets the value of the hmpobtelind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMPOBTELIND(String value) {
        this.hmpobtelind = value;
    }

    /**
     * Gets the value of the hmpobtelnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMPOBTELNUM() {
        return hmpobtelnum;
    }

    /**
     * Sets the value of the hmpobtelnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMPOBTELNUM(String value) {
        this.hmpobtelnum = value;
    }

    /**
     * Gets the value of the hmthreshnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHMTHRESHNUM() {
        return hmthreshnum;
    }

    /**
     * Sets the value of the hmthreshnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHMTHRESHNUM(String value) {
        this.hmthreshnum = value;
    }

}
