//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.05 at 09:41:16 AM MST 
//


package services.services.com.idfbins.membernumber;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.com.idfbins.membernumber package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MembershipQueryResponse_QNAME = new QName("http://www.idfbins.com/Membership", "membershipQueryResponse");
    private final static QName _MembershipQueryRequest_QNAME = new QName("http://www.idfbins.com/Membership", "membershipQueryRequest");
    private final static QName _ServiceStatus_QNAME = new QName("http://www.idfbins.com/common/ServiceStatus", "serviceStatus");
    private final static QName _MembershipRecordsRequest_QNAME = new QName("http://www.idfbins.com/Membership", "MembershipRecordsRequest");
    private final static QName _MembershipRecordsResponse_QNAME = new QName("http://www.idfbins.com/Membership", "MembershipRecordsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.com.idfbins.membernumber
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.MembershipRecordsRequest }
     * 
     */
    public services.services.com.idfbins.membernumber.MembershipRecordsRequest createMembershipRecordsRequest() {
        return new services.services.com.idfbins.membernumber.MembershipRecordsRequest();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.MembershipRecords }
     * 
     */
    public services.services.com.idfbins.membernumber.MembershipRecords createMembershipRecords() {
        return new services.services.com.idfbins.membernumber.MembershipRecords();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.MembershipQueryResponse }
     * 
     */
    public services.services.com.idfbins.membernumber.MembershipQueryResponse createMembershipQueryResponse() {
        return new services.services.com.idfbins.membernumber.MembershipQueryResponse();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.MembershipQueryRequest }
     * 
     */
    public services.services.com.idfbins.membernumber.MembershipQueryRequest createMembershipQueryRequest() {
        return new services.services.com.idfbins.membernumber.MembershipQueryRequest();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.FedRecord }
     * 
     */
    public services.services.com.idfbins.membernumber.FedRecord createFedRecord() {
        return new FedRecord();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.Years }
     * 
     */
    public services.services.com.idfbins.membernumber.Years createYears() {
        return new Years();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.Contacts }
     * 
     */
    public services.services.com.idfbins.membernumber.Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.MembershipRecord }
     * 
     */
    public services.services.com.idfbins.membernumber.MembershipRecord createMembershipRecord() {
        return new MembershipRecord();
    }

    /**
     * Create an instance of {@link ContactRecord }
     * 
     */
    public ContactRecord createContactRecord() {
        return new ContactRecord();
    }

    /**
     * Create an instance of {@link services.services.com.idfbins.membernumber.ServiceStatus }
     * 
     */
    public services.services.com.idfbins.membernumber.ServiceStatus createServiceStatus() {
        return new services.services.com.idfbins.membernumber.ServiceStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.services.com.idfbins.membernumber.MembershipQueryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.idfbins.com/Membership", name = "membershipQueryResponse")
    public JAXBElement<services.services.com.idfbins.membernumber.MembershipQueryResponse> createMembershipQueryResponse(services.services.com.idfbins.membernumber.MembershipQueryResponse value) {
        return new JAXBElement<services.services.com.idfbins.membernumber.MembershipQueryResponse>(_MembershipQueryResponse_QNAME, MembershipQueryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.services.com.idfbins.membernumber.MembershipQueryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.idfbins.com/Membership", name = "membershipQueryRequest")
    public JAXBElement<services.services.com.idfbins.membernumber.MembershipQueryRequest> createMembershipQueryRequest(services.services.com.idfbins.membernumber.MembershipQueryRequest value) {
        return new JAXBElement<services.services.com.idfbins.membernumber.MembershipQueryRequest>(_MembershipQueryRequest_QNAME, MembershipQueryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.services.com.idfbins.membernumber.ServiceStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.idfbins.com/common/ServiceStatus", name = "serviceStatus")
    public JAXBElement<services.services.com.idfbins.membernumber.ServiceStatus> createServiceStatus(services.services.com.idfbins.membernumber.ServiceStatus value) {
        return new JAXBElement<services.services.com.idfbins.membernumber.ServiceStatus>(_ServiceStatus_QNAME, ServiceStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.services.com.idfbins.membernumber.MembershipRecordsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.idfbins.com/Membership", name = "MembershipRecordsRequest")
    public JAXBElement<services.services.com.idfbins.membernumber.MembershipRecordsRequest> createMembershipRecordsRequest(services.services.com.idfbins.membernumber.MembershipRecordsRequest value) {
        return new JAXBElement<services.services.com.idfbins.membernumber.MembershipRecordsRequest>(_MembershipRecordsRequest_QNAME, MembershipRecordsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link services.services.com.idfbins.membernumber.MembershipRecords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.idfbins.com/Membership", name = "MembershipRecordsResponse")
    public JAXBElement<services.services.com.idfbins.membernumber.MembershipRecords> createMembershipRecordsResponse(services.services.com.idfbins.membernumber.MembershipRecords value) {
        return new JAXBElement<services.services.com.idfbins.membernumber.MembershipRecords>(_MembershipRecordsResponse_QNAME, MembershipRecords.class, null, value);
    }

}
