//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 04:26:02 PM MDT 
//


package services.broker.objects.lexisnexis.mvr.response.actual;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mortgageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mortgageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="holder" type="{http://cp.com/rules/client}mortgageHolderType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://cp.com/rules/client}parameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fsi_mortgage_loan_number" type="{http://cp.com/rules/client}yesNoType" minOccurs="0"/>
 *         &lt;element name="fsi_mortgage_company_name" type="{http://cp.com/rules/client}yesNoType" minOccurs="0"/>
 *         &lt;element name="mortgage_type" type="{http://cp.com/rules/client}mortgageTypeCode" minOccurs="0"/>
 *         &lt;element name="loanAmount" type="{http://cp.com/rules/client}amountType" minOccurs="0"/>
 *         &lt;element name="loanType" type="{http://cp.com/rules/client}loanTypeCode" minOccurs="0"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interestRateType" type="{http://cp.com/rules/client}interestRateType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classification" type="{http://cp.com/rules/client}mortgageClassificationCode" />
 *       &lt;attribute name="group_sequence_number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mortgageType", propOrder = {
    "company",
    "holderList",
    "parameterList",
    "fsiMortgageLoanNumber",
    "fsiMortgageCompanyName",
    "mortgageType",
    "loanAmount",
    "loanType",
    "interestRate",
    "interestRateType"
})
public class MortgageType {

    protected String company;
    @XmlElement(name = "holder")
    protected List<MortgageHolderType> holderList;
    @XmlElement(name = "parameter")
    protected List<ParameterType> parameterList;
    @XmlElement(name = "fsi_mortgage_loan_number")
    @XmlSchemaType(name = "string")
    protected YesNoType fsiMortgageLoanNumber;
    @XmlElement(name = "fsi_mortgage_company_name")
    @XmlSchemaType(name = "string")
    protected YesNoType fsiMortgageCompanyName;
    @XmlElement(name = "mortgage_type")
    @XmlSchemaType(name = "string")
    protected MortgageTypeCodeEnum mortgageType;
    protected String loanAmount;
    @XmlSchemaType(name = "string")
    protected LoanTypeCodeEnum loanType;
    protected String interestRate;
    @XmlSchemaType(name = "string")
    protected InterestRateTypeCodeEnum interestRateType;
    @XmlAttribute(name = "number")
    protected String number;
    @XmlAttribute(name = "classification")
    protected MortgageClassificationCodeEnum classification;
    @XmlAttribute(name = "group_sequence_number")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger groupSequenceNumber;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the holderList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the holderList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHolderList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MortgageHolderType }
     * 
     * 
     */
    public List<MortgageHolderType> getHolderList() {
        if (holderList == null) {
            holderList = new ArrayList<MortgageHolderType>();
        }
        return this.holderList;
    }

    /**
     * Gets the value of the parameterList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getParameterList() {
        if (parameterList == null) {
            parameterList = new ArrayList<ParameterType>();
        }
        return this.parameterList;
    }

    /**
     * Gets the value of the fsiMortgageLoanNumber property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getFsiMortgageLoanNumber() {
        return fsiMortgageLoanNumber;
    }

    /**
     * Sets the value of the fsiMortgageLoanNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setFsiMortgageLoanNumber(YesNoType value) {
        this.fsiMortgageLoanNumber = value;
    }

    /**
     * Gets the value of the fsiMortgageCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getFsiMortgageCompanyName() {
        return fsiMortgageCompanyName;
    }

    /**
     * Sets the value of the fsiMortgageCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setFsiMortgageCompanyName(YesNoType value) {
        this.fsiMortgageCompanyName = value;
    }

    /**
     * Gets the value of the mortgageType property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.MortgageTypeCodeEnum }
     *     
     */
    public MortgageTypeCodeEnum getMortgageType() {
        return mortgageType;
    }

    /**
     * Sets the value of the mortgageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.MortgageTypeCodeEnum }
     *     
     */
    public void setMortgageType(MortgageTypeCodeEnum value) {
        this.mortgageType = value;
    }

    /**
     * Gets the value of the loanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanAmount() {
        return loanAmount;
    }

    /**
     * Sets the value of the loanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanAmount(String value) {
        this.loanAmount = value;
    }

    /**
     * Gets the value of the loanType property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.LoanTypeCodeEnum }
     *     
     */
    public LoanTypeCodeEnum getLoanType() {
        return loanType;
    }

    /**
     * Sets the value of the loanType property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.LoanTypeCodeEnum }
     *     
     */
    public void setLoanType(LoanTypeCodeEnum value) {
        this.loanType = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestRate(String value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the interestRateType property.
     * 
     * @return
     *     possible object is
     *     {@link InterestRateTypeCodeEnum }
     *     
     */
    public InterestRateTypeCodeEnum getInterestRateType() {
        return interestRateType;
    }

    /**
     * Sets the value of the interestRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestRateTypeCodeEnum }
     *     
     */
    public void setInterestRateType(InterestRateTypeCodeEnum value) {
        this.interestRateType = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link MortgageClassificationCodeEnum }
     *     
     */
    public MortgageClassificationCodeEnum getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortgageClassificationCodeEnum }
     *     
     */
    public void setClassification(MortgageClassificationCodeEnum value) {
        this.classification = value;
    }

    /**
     * Gets the value of the groupSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGroupSequenceNumber() {
        return groupSequenceNumber;
    }

    /**
     * Sets the value of the groupSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGroupSequenceNumber(BigInteger value) {
        this.groupSequenceNumber = value;
    }

}
