//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 04:26:02 PM MDT 
//


package services.broker.objects.lexisnexis.mvr.response.actual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for realPropMaterialChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="realPropMaterialChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://cp.com/rules/client}rp_construction_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_foundation_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_exterior_wall_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_floor_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_roof_cover_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_style_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_basement_finish_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_garage_carport_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_fireplace_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_heating_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_heating_fuel_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_air_conditioning_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_pool_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_water_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_sewer_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}rp_parking_type"/>
 *         &lt;element ref="{http://cp.com/rules/client}unknown_material_type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "realPropMaterialChoiceType", propOrder = {
    "rpConstructionType",
    "rpFoundationType",
    "rpExteriorWallType",
    "rpFloorType",
    "rpRoofCoverType",
    "rpStyleType",
    "rpBasementFinishType",
    "rpGarageCarportType",
    "rpFireplaceType",
    "rpHeatingType",
    "rpHeatingFuelType",
    "rpAirConditioningType",
    "rpPoolType",
    "rpWaterType",
    "rpSewerType",
    "rpParkingType",
    "unknownMaterialType"
})
public class RealPropMaterialChoiceType {

    @XmlElement(name = "rp_construction_type")
    protected RpConstructionTypeEnum rpConstructionType;
    @XmlElement(name = "rp_foundation_type")
    protected RpFoundationTypeEnum rpFoundationType;
    @XmlElement(name = "rp_exterior_wall_type")
    protected RpExteriorWallTypeEnum rpExteriorWallType;
    @XmlElement(name = "rp_floor_type")
    protected RpFloorTypeEnum rpFloorType;
    @XmlElement(name = "rp_roof_cover_type")
    protected RpRoofCoverTypeEnum rpRoofCoverType;
    @XmlElement(name = "rp_style_type")
    protected RpStyleTypeEnum rpStyleType;
    @XmlElement(name = "rp_basement_finish_type")
    protected RpBasementFinishTypeEnum rpBasementFinishType;
    @XmlElement(name = "rp_garage_carport_type")
    protected RpGarageCarportTypeEnum rpGarageCarportType;
    @XmlElement(name = "rp_fireplace_type")
    protected RpFireplaceTypeEnum rpFireplaceType;
    @XmlElement(name = "rp_heating_type")
    protected RpHeatingTypeEnum rpHeatingType;
    @XmlElement(name = "rp_heating_fuel_type")
    protected RpHeatingFuelTypeEnum rpHeatingFuelType;
    @XmlElement(name = "rp_air_conditioning_type")
    protected RpAirConditioningTypeEnum rpAirConditioningType;
    @XmlElement(name = "rp_pool_type")
    protected RpPoolTypeEnum rpPoolType;
    @XmlElement(name = "rp_water_type")
    protected RpWaterTypeEnum rpWaterType;
    @XmlElement(name = "rp_sewer_type")
    protected RpSewerTypeEnum rpSewerType;
    @XmlElement(name = "rp_parking_type")
    protected RpParkingTypeEnum rpParkingType;
    @XmlElement(name = "unknown_material_type")
    protected String unknownMaterialType;

    /**
     * Gets the value of the rpConstructionType property.
     * 
     * @return
     *     possible object is
     *     {@link RpConstructionTypeEnum }
     *     
     */
    public RpConstructionTypeEnum getRpConstructionType() {
        return rpConstructionType;
    }

    /**
     * Sets the value of the rpConstructionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpConstructionTypeEnum }
     *     
     */
    public void setRpConstructionType(RpConstructionTypeEnum value) {
        this.rpConstructionType = value;
    }

    /**
     * Gets the value of the rpFoundationType property.
     * 
     * @return
     *     possible object is
     *     {@link RpFoundationTypeEnum }
     *     
     */
    public RpFoundationTypeEnum getRpFoundationType() {
        return rpFoundationType;
    }

    /**
     * Sets the value of the rpFoundationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpFoundationTypeEnum }
     *     
     */
    public void setRpFoundationType(RpFoundationTypeEnum value) {
        this.rpFoundationType = value;
    }

    /**
     * Gets the value of the rpExteriorWallType property.
     * 
     * @return
     *     possible object is
     *     {@link RpExteriorWallTypeEnum }
     *     
     */
    public RpExteriorWallTypeEnum getRpExteriorWallType() {
        return rpExteriorWallType;
    }

    /**
     * Sets the value of the rpExteriorWallType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpExteriorWallTypeEnum }
     *     
     */
    public void setRpExteriorWallType(RpExteriorWallTypeEnum value) {
        this.rpExteriorWallType = value;
    }

    /**
     * Gets the value of the rpFloorType property.
     * 
     * @return
     *     possible object is
     *     {@link RpFloorTypeEnum }
     *     
     */
    public RpFloorTypeEnum getRpFloorType() {
        return rpFloorType;
    }

    /**
     * Sets the value of the rpFloorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpFloorTypeEnum }
     *     
     */
    public void setRpFloorType(RpFloorTypeEnum value) {
        this.rpFloorType = value;
    }

    /**
     * Gets the value of the rpRoofCoverType property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.RpRoofCoverTypeEnum }
     *     
     */
    public RpRoofCoverTypeEnum getRpRoofCoverType() {
        return rpRoofCoverType;
    }

    /**
     * Sets the value of the rpRoofCoverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.RpRoofCoverTypeEnum }
     *     
     */
    public void setRpRoofCoverType(RpRoofCoverTypeEnum value) {
        this.rpRoofCoverType = value;
    }

    /**
     * Gets the value of the rpStyleType property.
     * 
     * @return
     *     possible object is
     *     {@link RpStyleTypeEnum }
     *     
     */
    public RpStyleTypeEnum getRpStyleType() {
        return rpStyleType;
    }

    /**
     * Sets the value of the rpStyleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpStyleTypeEnum }
     *     
     */
    public void setRpStyleType(RpStyleTypeEnum value) {
        this.rpStyleType = value;
    }

    /**
     * Gets the value of the rpBasementFinishType property.
     * 
     * @return
     *     possible object is
     *     {@link RpBasementFinishTypeEnum }
     *     
     */
    public RpBasementFinishTypeEnum getRpBasementFinishType() {
        return rpBasementFinishType;
    }

    /**
     * Sets the value of the rpBasementFinishType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpBasementFinishTypeEnum }
     *     
     */
    public void setRpBasementFinishType(RpBasementFinishTypeEnum value) {
        this.rpBasementFinishType = value;
    }

    /**
     * Gets the value of the rpGarageCarportType property.
     * 
     * @return
     *     possible object is
     *     {@link RpGarageCarportTypeEnum }
     *     
     */
    public RpGarageCarportTypeEnum getRpGarageCarportType() {
        return rpGarageCarportType;
    }

    /**
     * Sets the value of the rpGarageCarportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpGarageCarportTypeEnum }
     *     
     */
    public void setRpGarageCarportType(RpGarageCarportTypeEnum value) {
        this.rpGarageCarportType = value;
    }

    /**
     * Gets the value of the rpFireplaceType property.
     * 
     * @return
     *     possible object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.RpFireplaceTypeEnum }
     *     
     */
    public RpFireplaceTypeEnum getRpFireplaceType() {
        return rpFireplaceType;
    }

    /**
     * Sets the value of the rpFireplaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link broker.objects.lexisnexis.mvr.response.actual.RpFireplaceTypeEnum }
     *     
     */
    public void setRpFireplaceType(RpFireplaceTypeEnum value) {
        this.rpFireplaceType = value;
    }

    /**
     * Gets the value of the rpHeatingType property.
     * 
     * @return
     *     possible object is
     *     {@link RpHeatingTypeEnum }
     *     
     */
    public RpHeatingTypeEnum getRpHeatingType() {
        return rpHeatingType;
    }

    /**
     * Sets the value of the rpHeatingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpHeatingTypeEnum }
     *     
     */
    public void setRpHeatingType(RpHeatingTypeEnum value) {
        this.rpHeatingType = value;
    }

    /**
     * Gets the value of the rpHeatingFuelType property.
     * 
     * @return
     *     possible object is
     *     {@link RpHeatingFuelTypeEnum }
     *     
     */
    public RpHeatingFuelTypeEnum getRpHeatingFuelType() {
        return rpHeatingFuelType;
    }

    /**
     * Sets the value of the rpHeatingFuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpHeatingFuelTypeEnum }
     *     
     */
    public void setRpHeatingFuelType(RpHeatingFuelTypeEnum value) {
        this.rpHeatingFuelType = value;
    }

    /**
     * Gets the value of the rpAirConditioningType property.
     * 
     * @return
     *     possible object is
     *     {@link RpAirConditioningTypeEnum }
     *     
     */
    public RpAirConditioningTypeEnum getRpAirConditioningType() {
        return rpAirConditioningType;
    }

    /**
     * Sets the value of the rpAirConditioningType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpAirConditioningTypeEnum }
     *     
     */
    public void setRpAirConditioningType(RpAirConditioningTypeEnum value) {
        this.rpAirConditioningType = value;
    }

    /**
     * Gets the value of the rpPoolType property.
     * 
     * @return
     *     possible object is
     *     {@link RpPoolTypeEnum }
     *     
     */
    public RpPoolTypeEnum getRpPoolType() {
        return rpPoolType;
    }

    /**
     * Sets the value of the rpPoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpPoolTypeEnum }
     *     
     */
    public void setRpPoolType(RpPoolTypeEnum value) {
        this.rpPoolType = value;
    }

    /**
     * Gets the value of the rpWaterType property.
     * 
     * @return
     *     possible object is
     *     {@link RpWaterTypeEnum }
     *     
     */
    public RpWaterTypeEnum getRpWaterType() {
        return rpWaterType;
    }

    /**
     * Sets the value of the rpWaterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpWaterTypeEnum }
     *     
     */
    public void setRpWaterType(RpWaterTypeEnum value) {
        this.rpWaterType = value;
    }

    /**
     * Gets the value of the rpSewerType property.
     * 
     * @return
     *     possible object is
     *     {@link RpSewerTypeEnum }
     *     
     */
    public RpSewerTypeEnum getRpSewerType() {
        return rpSewerType;
    }

    /**
     * Sets the value of the rpSewerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpSewerTypeEnum }
     *     
     */
    public void setRpSewerType(RpSewerTypeEnum value) {
        this.rpSewerType = value;
    }

    /**
     * Gets the value of the rpParkingType property.
     * 
     * @return
     *     possible object is
     *     {@link RpParkingTypeEnum }
     *     
     */
    public RpParkingTypeEnum getRpParkingType() {
        return rpParkingType;
    }

    /**
     * Sets the value of the rpParkingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpParkingTypeEnum }
     *     
     */
    public void setRpParkingType(RpParkingTypeEnum value) {
        this.rpParkingType = value;
    }

    /**
     * Gets the value of the unknownMaterialType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnknownMaterialType() {
        return unknownMaterialType;
    }

    /**
     * Sets the value of the unknownMaterialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnknownMaterialType(String value) {
        this.unknownMaterialType = value;
    }

}
